from . import test_account_move_reconcile
from . import test_marin_account_account_fixes
from . import test_marin_account_move_line_fixes
from . import test_account_move_payments_widget
from . import test_account_move_out_invoice
from . import test_account_move_out_refund
from . import test_account_move_in_invoice
from . import test_account_move_in_refund
from . import test_account_move_duplicate
from . import test_account_move_catalog
from . import test_account_move_entry
from . import test_post_contract
from . import test_account_move_date_algorithm
from . import test_account_inalterable_hash
from . import test_account_journal
from . import test_account_account
from . import test_account_tax
from . import test_account_tax_settings_company
from . import test_account_tax_merge_wizard
from . import test_account_to_check
from . import test_account_analytic
from . import test_account_payment
from . import test_account_payment_channel
from . import test_account_payment_duplicate
from . import test_account_bank_statement
from . import test_account_invoice_report
from . import test_account_move_line_tax_details
from . import test_account_journal_dashboard_common
from . import test_account_journal_dashboard
from . import test_account_journal_sample_bill
from . import test_account_lock_exception
from . import test_audit_trail
from . import test_chart_template
from . import test_company_branch
from . import test_digest
from . import test_download_docs
from . import test_fiscal_position
from . import test_kpi_provider
from . import test_sequence_mixin
from . import test_tax
from . import test_taxes_base_lines_tax_details
from . import test_taxes_computation
from . import test_taxes_tax_totals_summary
from . import test_taxes_global_discount
from . import test_taxes_downpayment
from . import test_taxes_dispatching_base_lines
from . import test_taxes_repartition_amounts
from . import test_invoice_taxes
from . import test_account_move_send
from . import test_account_all_l10n
from . import test_portal_attachment
from . import test_portal_invoice
from . import test_portal_page_view_params
from . import test_tax_report
from . import test_transfer_wizard
from . import test_account_incoming_supplier_invoice
from . import test_payment_term
from . import test_account_payment_items
from . import test_account_payment_register
from . import test_account_reconcile_model
from . import test_account_report
from . import test_account_section_and_subsection
from . import test_tour
from . import test_early_payment_discount
from . import test_ir_actions_report
from . import test_multivat
from . import test_account_partner
from . import test_setup_wizard
from . import test_account_cash_rounding
from . import test_fiscal_country_codes
from . import test_product
from . import test_marin_account_move_audit
from . import test_marin_account_move_fixes
from . import test_marin_account_move_sync_fixes
from . import test_marin_outstanding_widget_guards
from . import test_marin_payment_audit
from . import test_marin_payment_receipt_report
from . import test_marin_taxes_country_constraint
from . import test_marin_wizard_audit
from . import test_unexpected_invoice
from . import test_mail_tracking_value
from . import test_res_partner_merge
from . import test_account_merge_wizard
from . import test_account_move_attachment
from . import test_account_move_view
from . import test_inactive_account_ui
from . import test_account_bill_deductibility
from . import test_duplicate_res_partner_bank
from . import test_res_partner_bank_trust
from . import test_account_move_import_template
from . import test_res_company
from . import test_res_currency
from . import test_account_move_marin_depends
