from . import badge
from . import challenge
from . import ir_http
from . import res_lang
from . import res_partner
from . import survey_category
from . import survey_question_statistics
from . import survey_question
from . import survey_question_answer
from . import survey_quota
from . import survey_survey
from . import survey_tag
from . import survey_user_input
from . import templates
