# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (
    barcode,
    ir_actions_report,
    product_strategy,
    res_company,
    res_partner,
    res_users,
    res_config_settings,
    stock_location,
    stock_move,
    stock_move_line,
    stock_orderpoint,
    stock_lot,
    stock_picking,
    stock_quant,
    stock_reference,
    stock_replenish_mixin,
    stock_rule,
    stock_warehouse,
    stock_scrap,
    product,
    product_catalog_mixin,
    stock_package_history,
    stock_package_type,
    stock_package,
    stock_storage_category,
)
