from collections import defaultdict

from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.fields import Domain


class ProductTemplate(models.Model):
    _inherit = "product.template"
    _check_company_auto = True

    # ------------------------------------------------------------
    # FIELDS
    # ------------------------------------------------------------

    is_storable = fields.Boolean(
        string="Track Inventory",
        default=False,
        compute="_compute_is_storable",
        store=True,
        precompute=True,
        readonly=False,
        tracking=True,
        help="A storable product is a product for which you manage stock.",
    )
    responsible_id = fields.Many2one(
        comodel_name="res.users",
        string="Responsible",
        default=lambda self: self._default_responsible_id(),
        company_dependent=True,
        check_company=True,
        help="This user will be responsible of the next activities related to logistic operations for this product.",
    )
    property_stock_production = fields.Many2one(
        comodel_name="stock.location",
        string="Production Location",
        company_dependent=True,
        check_company=True,
        domain="[('usage', '=', 'production'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by manufacturing orders.",
    )
    property_stock_inventory = fields.Many2one(
        comodel_name="stock.location",
        string="Inventory Location",
        company_dependent=True,
        check_company=True,
        domain="[('usage', '=', 'inventory'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated when you do an inventory.",
    )
    sale_delay = fields.Integer(
        string="Customer Lead Time",
        default=0,
        help="Delivery lead time, in days. It's the number of days, promised to the customer, between the confirmation of the sales order and the delivery.",
    )
    tracking = fields.Selection(
        selection=[
            ("serial", "By Unique Serial Number"),
            ("lot", "By Lots"),
            ("none", "By Quantity"),
        ],
        string="Tracking",
        required=True,
        default="none",
        compute="_compute_tracking",
        store=True,
        precompute=True,
        readonly=False,
        help="Ensure the traceability of a storable product in your warehouse.",
    )
    lot_sequence_id = fields.Many2one(
        comodel_name="ir.sequence",
        string="Serial/Lot Numbers Sequence",
        default=lambda self: self.env.ref(
            "stock.sequence_production_lots",
            raise_if_not_found=False,
        ),
        help="Technical Field: The Ir.Sequence record that is used to generate serial/lot numbers for this product",
    )
    serial_prefix_format = fields.Char(
        string="Custom Lot/Serial",
        compute="_compute_serial_prefix_format",
        inverse="_inverse_serial_prefix_format",
        help="""
            If multiple products share the same prefix, they will share the same sequence, otherwise the sequence will be dedicated to the product.

            * Legend (for prefix):
            - Current Year with Century: %(year)s
            - Current Year without Century: %(y)s
            - Month: %(month)s
            - Day: %(day)s
            - Day of the Year: %(doy)s
            - Week of the Year: %(woy)s
            - Day of the Week (0:Monday): %(weekday)s
            - Hour 00->24: %(h24)s
            - Hour 00->12: %(h12)s
            - Minute: %(min)s
            - Second: %(sec)s
        """,
    )
    next_serial = fields.Char(compute="_compute_next_serial")
    description_picking = fields.Text(string="Description on Picking", translate=True)
    description_pickingout = fields.Text(
        string="Description on Delivery Orders",
        translate=True,
    )
    description_pickingin = fields.Text(
        string="Description on Receptions",
        translate=True,
    )
    qty_available = fields.Float(
        string="Quantity On Hand",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        inverse="_inverse_qty_available",
        search="_search_qty_available",
    )
    qty_available_virtual = fields.Float(
        string="Forecasted Quantity",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_virtual_available",
    )
    qty_incoming = fields.Float(
        string="Incoming",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_incoming_qty",
    )
    qty_outgoing = fields.Float(
        string="Outgoing",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_outgoing_qty",
    )
    # Dummy fields: not stored, only used to inject 'location'/'warehouse_id' into the
    # context from the search view so they can influence the computed quantity fields.
    location_id = fields.Many2one(
        comodel_name="stock.location",
        string="Location",
        store=False,
    )
    warehouse_id = fields.Many2one(
        comodel_name="stock.warehouse",
        string="Warehouse",
        store=False,
    )
    has_available_route_ids = fields.Boolean(
        string="Routes can be selected on this product",
        compute="_compute_has_available_route_ids",
    )
    route_ids = fields.Many2many(
        comodel_name="stock.route",
        relation="stock_route_product",
        column1="product_id",
        column2="route_id",
        string="Routes",
        domain=[("product_selectable", "=", True)],
        help="Depending on the modules installed, this will allow you to define the route of the product: whether it will be bought, manufactured, replenished on order, etc.",
        depends_context=["company", "allowed_companies"],
    )
    count_moves_in = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of incoming stock moves in the past 12 months",
    )
    count_moves_out = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of outgoing stock moves in the past 12 months",
    )
    count_reordering_rules = fields.Integer(
        string="Reordering Rules",
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_min = fields.Float(
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_max = fields.Float(
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    # Only used to show the category's routes on the product form view.
    route_from_categ_ids = fields.Many2many(
        related="categ_id.total_route_ids",
        string="Category Routes",
        related_sudo=False,
    )
    show_on_hand_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_forecasted_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_qty_update_button = fields.Boolean(compute="_compute_show_qty_update_button")
    count_lot_ids = fields.Integer(
        string="Lots Count",
        compute="_compute_count_lot_ids",
    )

    # ------------------------------------------------------------
    # CRUD METHODS
    # ------------------------------------------------------------

    @api.model_create_multi
    def create(self, vals_list):
        product_tmpl_quantities = [vals.pop("qty_available", 0) for vals in vals_list]

        product_templates = super().create(vals_list)

        if any(product_tmpl_quantities):
            for product_tmpl, qty in zip(
                product_templates, product_tmpl_quantities, strict=True
            ):
                if qty > 0 and product_tmpl.tracking == "none":
                    product_tmpl.product_variant_id.qty_available = qty
        return product_templates

    def write(self, vals):
        if vals.get("company_id"):
            products_changing_company = self.filtered(
                lambda product: product.company_id.id != vals["company_id"],
            )
            if products_changing_company:
                move = (
                    self.env["stock.move"]
                    .sudo()
                    .search(
                        [
                            (
                                "product_id",
                                "in",
                                products_changing_company.product_variant_ids.ids,
                            ),
                            ("company_id", "not in", [vals["company_id"], False]),
                        ],
                        order=None,
                        limit=1,
                    )
                )
                if move:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are stock moves of it belonging to another company.",
                        ),
                    )

                quant = (
                    self.env["stock.quant"]
                    .sudo()
                    .search(
                        [
                            (
                                "product_id",
                                "in",
                                products_changing_company.product_variant_ids.ids,
                            ),
                            ("company_id", "not in", [vals["company_id"], False]),
                            ("quantity", "!=", 0),
                        ],
                        order=None,
                        limit=1,
                    )
                )
                if quant:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are quantities of it belonging to another company.",
                        ),
                    )

        # Switching a product to storable drops stale reservations and rebuilds its
        # inventory from move history. Only templates actually transitioning are reset;
        # those already storable are skipped.
        clean_inventory = False
        templates_to_reset = self.env["product.template"]
        if vals.get("is_storable"):
            templates_to_reset = self.filtered(lambda tmpl: not tmpl.is_storable)
            clean_inventory = bool(templates_to_reset)

        res = super().write(vals)
        if clean_inventory:
            self.env["stock.quant"].sudo()._clean_reservations()
            templates_to_reset._reset_inventory()
        return res

    def copy(self, default=None):
        new_products = super().copy(default=default)
        # Variants aren't copied directly, so match each template's new variants to the
        # originals by attribute value and carry over their storage category capacity.
        # The mapping MUST be rebuilt per template: copy() is batched, so a global key
        # lets templates sharing an attribute value (e.g. both "Color: Red") overwrite
        # each other -- wrong variant, or a (product, category) uniqueness crash.
        storage_category_capacity_vals = []
        for old_template, new_template in zip(self, new_products, strict=True):
            new_variant_id_by_value = {
                variant.product_template_attribute_value_ids.product_attribute_value_id: variant.id
                for variant in new_template.product_variant_ids
            }
            for (
                capacity
            ) in old_template.product_variant_ids.storage_category_capacity_ids:
                attribute_value = capacity.product_id.product_template_attribute_value_ids.product_attribute_value_id
                storage_category_capacity_vals.append(
                    capacity.copy_data(
                        {"product_id": new_variant_id_by_value[attribute_value]},
                    )[0],
                )
        self.env["stock.storage.category.capacity"].create(
            storage_category_capacity_vals,
        )
        return new_products

    # ------------------------------------------------------------
    # DEFAULT METHODS
    # ------------------------------------------------------------

    def _default_responsible_id(self):
        # Default to the current user, but leave it unset for OdooBot.
        return False if self.env.user._is_superuser() else self.env.uid

    # ------------------------------------------------------------
    # COMPUTE METHODS
    # ------------------------------------------------------------

    def _compute_count_lot_ids(self):
        # Aggregate lot counts per variant in one query, then roll up per template.
        # Iterating ``product_variant_ids`` (active-filtered) keeps archived variants'
        # lots out of the count, matching the original per-record ``search_count``.
        counts = defaultdict(int)
        for product, count in self.env["stock.lot"]._read_group(
            [("product_id", "in", self.product_variant_ids.ids)],
            ["product_id"],
            ["__count"],
        ):
            counts[product.id] += count
        for template in self:
            template.count_lot_ids = sum(
                counts[variant.id] for variant in template.product_variant_ids
            )

    def _compute_count_reordering_rules(self):
        # Aggregate every variant's orderpoints up to the template: count, min and
        # max all sum across variants (a template rolls up its variants' rules).
        # A missing template defaults to zeros, which also covers unsaved records.
        res = defaultdict(lambda: {"count": 0, "min": 0.0, "max": 0.0})
        for product, count, product_min_qty, product_max_qty in self.env[
            "stock.warehouse.orderpoint"
        ]._read_group(
            [("product_id.product_tmpl_id", "in", self.ids)],
            ["product_id"],
            ["__count", "product_min_qty:sum", "product_max_qty:sum"],
        ):
            agg = res[product.product_tmpl_id.id]
            agg["count"] += count
            agg["min"] += product_min_qty
            agg["max"] += product_max_qty
        for template in self:
            agg = res[template.id]
            template.count_reordering_rules = agg["count"]
            template.reordering_qty_min = agg["min"]
            template.reordering_qty_max = agg["max"]

    @api.depends("type")
    def _compute_is_storable(self):
        self.filtered(lambda t: t.type != "consu" and t.is_storable).is_storable = False

    @api.depends("is_storable")
    def _compute_tracking(self):
        self.filtered(
            lambda t: not t.is_storable and t.tracking != "none",
        ).tracking = "none"

    @api.depends("lot_sequence_id", "lot_sequence_id.prefix")
    def _compute_serial_prefix_format(self):
        for template in self:
            template.serial_prefix_format = template.lot_sequence_id.prefix or ""

    @api.depends("lot_sequence_id.number_next_actual")
    def _compute_next_serial(self):
        for template in self:
            if template.lot_sequence_id:
                template.next_serial = "{:0{}d}{}".format(
                    template.lot_sequence_id.number_next_actual,
                    template.lot_sequence_id.padding,
                    template.lot_sequence_id.suffix or "",
                )
            else:
                template.next_serial = "0000001"

    @api.depends("is_storable")
    def _compute_show_qty_status_button(self):
        for template in self:
            template.show_on_hand_qty_status_button = template.is_storable
            template.show_forecasted_qty_status_button = (
                template.is_storable and template.product_variant_id
            )

    def _compute_has_available_route_ids(self):
        # Global flag: true iff any selectable route exists, so it's the same for every
        # record with no field/context dependency to declare (it tracks stock.route
        # config). Only existence matters, so limit=1 avoids counting the whole table.
        self.has_available_route_ids = bool(
            self.env["stock.route"].search_count(
                [("product_selectable", "=", True)],
                limit=1,
            )
        )

    @api.depends("product_variant_count", "tracking")
    def _compute_show_qty_update_button(self):
        for product in self:
            product.show_qty_update_button = (
                product._should_open_product_quants()
                or product.product_variant_count > 1
            )

    @api.depends(
        "product_variant_ids.qty_available",
        "product_variant_ids.qty_available_virtual",
        "product_variant_ids.qty_incoming",
        "product_variant_ids.qty_outgoing",
        "tracking",
    )
    # Mirror product.product._compute_quantities: the template value sums its variants'
    # quantities, so it depends on every context key the variant does. Declaring only
    # "warehouse_id" aliased the cache across location/date/owner/lot/package/company --
    # a template read under one location returned a value computed under another.
    @api.depends_context(
        "lot_id",
        "owner_id",
        "package_id",
        "from_date",
        "to_date",
        "location",
        "warehouse_id",
        "allowed_company_ids",
        "is_storable",
    )
    def _compute_quantities(self):
        res = self._prepare_quantities_vals()
        for template in self.with_context(skip_qty_available_update=True):
            template.qty_available = res[template.id]["qty_available"]
            template.qty_available_virtual = res[template.id]["qty_available_virtual"]
            template.qty_incoming = res[template.id]["qty_incoming"]
            template.qty_outgoing = res[template.id]["qty_outgoing"]

    def _prepare_quantities_vals(self):
        variants_available = {
            p["id"]: p
            for p in self.product_variant_ids._origin.read(
                [
                    "qty_available",
                    "qty_available_virtual",
                    "qty_incoming",
                    "qty_outgoing",
                ],
            )
        }
        prod_available = {}
        for template in self:
            qty_available = 0
            qty_available_virtual = 0
            qty_incoming = 0
            qty_outgoing = 0
            for p in template.product_variant_ids._origin:
                qty_available += variants_available[p.id]["qty_available"]
                qty_available_virtual += variants_available[p.id][
                    "qty_available_virtual"
                ]
                qty_incoming += variants_available[p.id]["qty_incoming"]
                qty_outgoing += variants_available[p.id]["qty_outgoing"]
            prod_available[template.id] = {
                "qty_available": qty_available,
                "qty_available_virtual": qty_available_virtual,
                "qty_incoming": qty_incoming,
                "qty_outgoing": qty_outgoing,
            }
        return prod_available

    def _compute_count_moves(self):
        res = defaultdict(lambda: {"moves_in": 0, "moves_out": 0})
        # picking_code is a non-stored related field: it works in a domain but can't be
        # a _read_group key, so incoming/outgoing stay two queries. The 12-month cutoff
        # and shared filters are built once so both queries use an identical boundary.
        one_year_ago = fields.Datetime.now() - relativedelta(years=1)
        base_domain = [
            ("product_id.product_tmpl_id", "in", self.ids),
            ("state", "=", "done"),
            ("date", ">=", one_year_ago),
        ]
        incoming_moves = self.env["stock.move.line"]._read_group(
            [*base_domain, ("picking_code", "=", "incoming")],
            ["product_id"],
            ["__count"],
        )
        outgoing_moves = self.env["stock.move.line"]._read_group(
            [*base_domain, ("picking_code", "=", "outgoing")],
            ["product_id"],
            ["__count"],
        )
        for product, count in incoming_moves:
            product_tmpl_id = product.product_tmpl_id.id
            res[product_tmpl_id]["moves_in"] += count
        for product, count in outgoing_moves:
            product_tmpl_id = product.product_tmpl_id.id
            res[product_tmpl_id]["moves_out"] += count
        for template in self:
            template.count_moves_in = res[template.id]["moves_in"]
            template.count_moves_out = res[template.id]["moves_out"]

    # ------------------------------------------------------------
    # INVERSE METHODS
    # ------------------------------------------------------------

    def _inverse_serial_prefix_format(self):
        valid_sequences = self.env["ir.sequence"].search(
            [("prefix", "in", self.mapped("serial_prefix_format"))],
        )
        sequences_by_prefix = {seq.prefix: seq for seq in valid_sequences}
        for template in self:
            if template.serial_prefix_format:
                if template.serial_prefix_format in sequences_by_prefix:
                    template.lot_sequence_id = sequences_by_prefix[
                        template.serial_prefix_format
                    ]
                else:
                    new_sequence = self.env["ir.sequence"].create(
                        {
                            "name": f"{template.name} Serial Sequence",
                            "code": "stock.lot.serial",
                            "prefix": template.serial_prefix_format,
                            "padding": 7,
                            "company_id": False,
                        },
                    )
                    template.lot_sequence_id = new_sequence
                    sequences_by_prefix[template.serial_prefix_format] = new_sequence
            else:
                template.lot_sequence_id = self.env.ref(
                    "stock.sequence_production_lots",
                    raise_if_not_found=False,
                )

    def _inverse_qty_available(self):
        if self.env.context.get("skip_qty_available_update", False):
            return
        for template in self:
            if template.qty_available and not template.product_variant_id:
                raise UserError(
                    _("Save the product form before updating the Quantity On Hand."),
                )
            template.product_variant_id.qty_available = template.qty_available

    # ------------------------------------------------------------
    # SEARCH METHODS
    # ------------------------------------------------------------

    def _search_variant_quantity(self, field_name, operator, value):
        # The quantity fields are aggregates of the variants', so a template
        # matches when any of its variants matches the same criterion.
        variant_query = self.env["product.product"]._search(
            [(field_name, operator, value)]
        )
        return [("product_variant_ids", "in", variant_query)]

    def _search_qty_available(self, operator, value):
        return self._search_variant_quantity("qty_available", operator, value)

    def _search_virtual_available(self, operator, value):
        return self._search_variant_quantity("qty_available_virtual", operator, value)

    def _search_incoming_qty(self, operator, value):
        return self._search_variant_quantity("qty_incoming", operator, value)

    def _search_outgoing_qty(self, operator, value):
        return self._search_variant_quantity("qty_outgoing", operator, value)

    @api.onchange("tracking")
    def _onchange_tracking(self):
        return self.mapped("product_variant_ids")._onchange_tracking()

    # ------------------------------------------------------------
    # ONCHANGE METHODS
    # ------------------------------------------------------------

    @api.onchange("type")
    def _onchange_type(self):
        res = super()._onchange_type()
        if (
            self.ids
            and self.product_variant_ids.ids
            and self.env["stock.move.line"]
            .sudo()
            .search_count(
                [
                    ("product_id", "in", self.product_variant_ids.ids),
                    ("state", "!=", "cancel"),
                ],
            )
        ):
            res["warning"] = {
                "title": _("Warning!"),
                "message": _(
                    "This product has been used in at least one inventory movement. "
                    "It is not advised to change the Product Type since it can lead to inconsistencies. "
                    "A better solution could be to archive the product and create a new one instead."
                ),
            }
        return res

    # ------------------------------------------------------------
    # ACTION METHODS
    # ------------------------------------------------------------

    def action_view_quants(self):
        if "product_variant" in self.env.context:
            return (
                self.env["product.product"]
                .browse(self.env.context["default_product_id"])
                .action_view_quants()
            )
        return self.product_variant_ids.filtered(
            lambda p: p.active or p.qty_available != 0,
        ).action_view_quants()

    def action_view_related_putaway_rules(self):
        self.ensure_one()
        domain = [
            "|",
            ("product_id.product_tmpl_id", "=", self.id),
            ("category_id", "=", self.categ_id.id),
        ]
        return self._get_action_view_related_putaway_rules(domain)

    def action_view_storage_category_capacity(self):
        self.ensure_one()
        return self.product_variant_ids.action_view_storage_category_capacity()

    def action_view_orderpoints(self):
        return self.product_variant_ids.action_view_orderpoints()

    def action_view_stock_move_lines(self):
        self.ensure_one()
        action = self.env["ir.actions.actions"]._for_xml_id(
            "stock.stock_move_line_action",
        )
        action["domain"] = [("product_id.product_tmpl_id", "in", self.ids)]
        return action

    def action_view_product_lot(self):
        self.ensure_one()
        action = self.env["ir.actions.actions"]._for_xml_id(
            "stock.action_stock_lot_form_2",
        )
        action["domain"] = [
            ("product_id.product_tmpl_id", "=", self.id),
            "|",
            ("location_id", "=", False),
            (
                "location_id",
                "any",
                self.env["stock.location"]._check_company_domain(
                    self.env.context["allowed_company_ids"]
                ),
            ),
        ]
        action["context"] = {
            "default_product_tmpl_id": self.id,
            "search_default_group_by_location": True,
        }
        if self.product_variant_count == 1:
            action["context"].update(
                {
                    "default_product_id": self.product_variant_id.id,
                },
            )
        return action

    def action_view_routes_diagram(self):
        products = False
        if self.env.context.get("default_product_id"):
            products = self.env["product.product"].browse(
                self.env.context["default_product_id"]
            )
        if not products and self.env.context.get("default_product_tmpl_id"):
            products = (
                self.env["product.template"]
                .browse(self.env.context["default_product_tmpl_id"])
                .product_variant_ids
            )
        if (
            not self.env.user.has_group("stock.group_stock_multi_warehouses")
            and len(products) == 1
        ):
            company = products.company_id or self.env.company
            warehouse = self.env["stock.warehouse"].search(
                [("company_id", "=", company.id)],
                limit=1,
            )
            return self.env.ref("stock.action_report_stock_rule").report_action(
                None,
                data={
                    "product_id": products.id,
                    "warehouse_ids": warehouse.ids,
                },
                config=False,
            )
        action = self.env["ir.actions.actions"]._for_xml_id(
            "stock.action_stock_rules_report",
        )
        action["context"] = self.env.context
        return action

    def action_product_tmpl_forecast_report(self):
        self.ensure_one()
        if not self.env.user._get_default_warehouse_id():
            self.env["stock.warehouse"]._warehouse_redirect_warning()
        return self.env["ir.actions.actions"]._for_xml_id(
            "stock.stock_forecasted_product_template_action",
        )

    # ------------------------------------------------------------
    # HELPER METHODS
    # ------------------------------------------------------------

    def _reset_inventory(self):
        """Create quants matching the move history of products that just became
        storable, then reset them via inventory adjustment. Needed to keep product
        valuation consistent once stock tracking starts.
        """
        move_line_domain = Domain(
            [
                ("product_id", "in", self.product_variant_ids.ids),
                ("state", "=", "done"),
                "|",
                ("location_usage", "in", ("internal", "transit")),
                ("location_dest_usage", "in", ("internal", "transit")),
            ],
        )
        # Fetch the stored fields the ledger loop reads. ``location_usage`` /
        # ``location_dest_usage`` are non-stored related fields and can't be folded
        # into the query, but pulling ``location_dest_id`` up front spares a prefetch
        # round-trip.
        move_lines_to_match = self.env["stock.move.line"].search_fetch(
            move_line_domain,
            [
                "product_id",
                "location_id",
                "location_dest_id",
                "quantity_product_uom",
            ],
        )
        inventory_ledger = defaultdict(float)
        for move_line in move_lines_to_match:
            if move_line.location_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_id] -= (
                    move_line.quantity_product_uom
                )
            if move_line.location_dest_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_dest_id] += (
                    move_line.quantity_product_uom
                )
        quants_to_reset = self.env["stock.quant"].create(
            [
                {
                    "product_id": product.id,
                    "location_id": location.id,
                    "quantity": quantity,
                    "inventory_quantity": 0.0,
                }
                for (product, location), quantity in inventory_ledger.items()
                if not product.uom_id.is_zero(quantity)
            ],
        )
        quants_to_reset._apply_inventory()

    @api.model
    def _get_action_view_related_putaway_rules(self, domain):
        return {
            "name": _("Putaway Rules"),
            "type": "ir.actions.act_window",
            "res_model": "stock.putaway.rule",
            "view_mode": "list",
            "domain": domain,
        }

    # ------------------------------------------------------------
    # VALIDATION METHODS
    # ------------------------------------------------------------

    def _should_open_product_quants(self):
        self.ensure_one()
        advanced_option_groups = [
            "stock.group_stock_multi_locations",
            "stock.group_tracking_owner",
            "stock.group_tracking_lot",
        ]
        return (
            any(self.env.user.has_group(g) for g in advanced_option_groups)
            or self.tracking != "none"
        )
