from collections import defaultdict

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.fields import Domain

from odoo.addons.stock.const import PY_OPERATORS, TEMPLATE_QUANTITY_FIELDS


class ProductTemplate(models.Model):
    _inherit = "product.template"
    _check_company_auto = True

    is_storable = fields.Boolean(
        string="Track Inventory",
        default=False,
        compute="_compute_is_storable",
        store=True,
        precompute=True,
        readonly=False,
        tracking=True,
        help="A storable product is a product for which you manage stock.",
    )
    responsible_id = fields.Many2one(
        comodel_name="res.users",
        string="Responsible",
        default=lambda self: self._default_responsible_id(),
        company_dependent=True,
        check_company=True,
        help="This user will be responsible of the next activities related to logistic operations for this product.",
    )
    property_stock_production = fields.Many2one(
        comodel_name="stock.location",
        string="Production Location",
        company_dependent=True,
        check_company=True,
        domain="[('usage', '=', 'production'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by manufacturing orders.",
    )
    property_stock_inventory = fields.Many2one(
        comodel_name="stock.location",
        string="Inventory Location",
        company_dependent=True,
        check_company=True,
        domain="[('usage', '=', 'inventory'), ('company_id', 'in', [False, allowed_company_ids[0]])]",
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated when you do an inventory.",
    )
    sale_delay = fields.Integer(
        string="Customer Lead Time",
        default=0,
        help="Delivery lead time, in days. It's the number of days, promised to the customer, between the confirmation of the sales order and the delivery.",
    )
    tracking = fields.Selection(
        selection=[
            ("serial", "By Unique Serial Number"),
            ("lot", "By Lots"),
            ("none", "By Quantity"),
        ],
        string="Tracking",
        required=True,
        default="none",
        compute="_compute_tracking",
        store=True,
        precompute=True,
        readonly=False,
        help="Ensure the traceability of a storable product in your warehouse.",
    )
    lot_sequence_id = fields.Many2one(
        comodel_name="ir.sequence",
        string="Serial/Lot Numbers Sequence",
        default=lambda self: self.env.ref(
            "stock.sequence_production_lots",
            raise_if_not_found=False,
        ),
        help="Technical Field: The Ir.Sequence record that is used to generate serial/lot numbers for this product",
    )
    lot_name_format = fields.Char(
        string="Lot/Serial Name Format",
        help="Shape this product's lot/serial names take, in the same "
        "placeholder form as a sequence prefix (%(year)s, %(month)s, %(day)s, "
        "...) plus %(ref)s for the manufacturer's lot number.\n"
        "Set it when the name has to carry information — a manufacturing date, "
        "a supplier's own lot number — rather than just be unique. Left empty, "
        "names are drawn from the sequence as usual.",
    )
    serial_prefix_format = fields.Char(
        string="Custom Lot/Serial",
        compute="_compute_serial_prefix_format",
        inverse="_inverse_serial_prefix_format",
        help="""
            If multiple products share the same prefix, they will share the same sequence, otherwise the sequence will be dedicated to the product.

            * Legend (for prefix):
            - Current Year with Century: %(year)s
            - Current Year without Century: %(y)s
            - Month: %(month)s
            - Day: %(day)s
            - Day of the Year: %(doy)s
            - Week of the Year: %(woy)s
            - Day of the Week (0:Monday): %(weekday)s
            - Hour 00->24: %(h24)s
            - Hour 00->12: %(h12)s
            - Minute: %(min)s
            - Second: %(sec)s
        """,
    )
    next_serial = fields.Char(compute="_compute_next_serial")
    description_picking = fields.Text(string="Description on Picking", translate=True)
    description_pickingout = fields.Text(
        string="Description on Delivery Orders",
        translate=True,
    )
    description_pickingin = fields.Text(
        string="Description on Receptions",
        translate=True,
    )
    qty_available = fields.Float(
        string="Quantity On Hand",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        inverse="_inverse_qty_available",
        search="_search_qty_available",
        help="Sum of the quantity on hand of every variant of this product, "
        "scoped by the location or warehouse selected in the search view.",
    )
    qty_available_virtual = fields.Float(
        string="Forecasted Quantity",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_qty_available_virtual",
        help="Sum of the forecasted quantity (on hand - outgoing + incoming) of "
        "every variant of this product.",
    )
    qty_incoming = fields.Float(
        string="Incoming",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_qty_incoming",
        help="Sum of the planned incoming quantity of every variant of this product.",
    )
    qty_outgoing = fields.Float(
        string="Outgoing",
        digits="Product Unit",
        compute="_compute_quantities",
        compute_sudo=False,
        search="_search_qty_outgoing",
        help="Sum of the planned outgoing quantity of every variant of this product.",
    )
    location_id = fields.Many2one(
        comodel_name="stock.location",
        string="Location",
        store=False,
    )
    warehouse_id = fields.Many2one(
        comodel_name="stock.warehouse",
        string="Warehouse",
        store=False,
    )
    has_available_route_ids = fields.Boolean(
        string="Routes can be selected on this product",
        compute="_compute_has_available_route_ids",
        default=lambda self: self._default_has_available_route_ids(),
    )
    route_ids = fields.Many2many(
        comodel_name="stock.route",
        relation="stock_route_product",
        column1="product_id",
        column2="route_id",
        string="Routes",
        domain=[("product_selectable", "=", True)],
        help="Depending on the modules installed, this will allow you to define the route of the product: whether it will be bought, manufactured, replenished on order, etc.",
        depends_context=["company", "allowed_companies"],
    )
    count_moves_in = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of incoming stock moves in the past 12 months",
    )
    count_moves_out = fields.Integer(
        compute="_compute_count_moves",
        compute_sudo=False,
        help="Number of outgoing stock moves in the past 12 months",
    )
    count_reordering_rules = fields.Integer(
        string="Reordering Rules",
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_min = fields.Float(
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    reordering_qty_max = fields.Float(
        compute="_compute_count_reordering_rules",
        compute_sudo=False,
    )
    route_from_categ_ids = fields.Many2many(
        related="categ_id.total_route_ids",
        string="Category Routes",
        related_sudo=False,
    )
    show_on_hand_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_forecasted_qty_status_button = fields.Boolean(
        compute="_compute_show_qty_status_button"
    )
    show_qty_update_button = fields.Boolean(compute="_compute_show_qty_update_button")

    @api.model_create_multi
    def create(self, vals_list):
        product_tmpl_quantities = [vals.get("qty_available") or 0 for vals in vals_list]
        if any("qty_available" in vals for vals in vals_list):
            vals_list = [
                {key: val for key, val in vals.items() if key != "qty_available"}
                for vals in vals_list
            ]

        product_templates = super().create(vals_list)

        if any(product_tmpl_quantities):
            templates_to_update = self.browse()
            quantities = []
            for product_tmpl, qty in zip(
                product_templates, product_tmpl_quantities, strict=True
            ):
                if not qty:
                    continue
                templates_to_update |= product_tmpl
                quantities.append(qty)
            templates_to_update._set_qty_available(quantities)
        return product_templates

    def _check_qty_available_update(self, quantities):
        for template, qty in zip(self, quantities, strict=True):
            if template.type != "consu" or not template.is_storable:
                raise UserError(
                    _(
                        "%(product)s does not track inventory, so it cannot have a"
                        " quantity on hand. Enable Track Inventory first.",
                        product=template.display_name,
                    ),
                )
            if template.tracking != "none":
                raise UserError(
                    _(
                        "%(product)s is tracked by lot/serial number: set its quantity"
                        " through an inventory adjustment so lot/serial numbers can be"
                        " assigned.",
                        product=template.display_name,
                    ),
                )
            if template.product_variant_count > 1:
                raise UserError(
                    _(
                        "%(product)s has several variants: update the quantity of each"
                        " variant instead.",
                        product=template.display_name,
                    ),
                )
            if not template.product_variant_id:
                raise UserError(
                    _("Save the product form before updating the Quantity On Hand."),
                )
            if template.uom_id.compare(qty, 0) < 0:
                raise UserError(
                    _(
                        "The quantity on hand of %(product)s cannot be set to a negative value.",
                        product=template.display_name,
                    ),
                )

    def _set_qty_available(self, quantities):
        templates_to_apply = self.browse()
        quantities_to_apply = []
        for template, qty in zip(self, quantities, strict=True):
            if not qty and (template.type != "consu" or not template.is_storable):
                continue
            templates_to_apply |= template
            quantities_to_apply.append(qty)
        if not templates_to_apply:
            return
        templates_to_apply._check_qty_available_update(quantities_to_apply)
        templates_to_apply.product_variant_id._apply_qty_available(quantities_to_apply)

    def write(self, vals):
        if vals.get("company_id"):
            products_changing_company = self.filtered(
                lambda product: product.company_id.id != vals["company_id"],
            )
            if products_changing_company:
                variant_ids = products_changing_company.with_context(
                    active_test=False
                ).product_variant_ids.ids
                other_company = Domain(
                    "company_id", "not in", [vals["company_id"], False]
                )
                move = (
                    self.env["stock.move"]
                    .sudo()
                    .search(
                        Domain("product_id", "in", variant_ids) & other_company,
                        order=None,
                        limit=1,
                    )
                )
                if move:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are stock moves of it belonging to another company.",
                        ),
                    )

                quant = (
                    self.env["stock.quant"]
                    .sudo()
                    .search(
                        Domain("product_id", "in", variant_ids)
                        & other_company
                        & Domain("quantity", "!=", 0),
                        order=None,
                        limit=1,
                    )
                )
                if quant:
                    raise UserError(
                        _(
                            "This product's company cannot be changed as long as there are quantities of it belonging to another company.",
                        ),
                    )

        templates_to_reset = self.browse()
        if vals.get("is_storable"):
            templates_to_reset = self.filtered(lambda tmpl: not tmpl.is_storable)

        res = super().write(vals)
        if templates_to_reset:
            products = templates_to_reset.with_context(
                active_test=False
            ).product_variant_ids
            self.env["stock.quant"].sudo()._clean_reservations(products=products)
            templates_to_reset._reset_inventory()
        return res

    def copy(self, default=None):
        new_products = super().copy(default=default)
        Capacity = self.env["stock.storage.category.capacity"]
        storage_category_capacity_vals = []
        for old_template, new_template in zip(self, new_products, strict=True):
            new_variant_id_by_value = {
                variant.product_template_attribute_value_ids.product_attribute_value_id: variant.id
                for variant in new_template.with_context(
                    active_test=False
                ).product_variant_ids
            }
            capacities = old_template.with_context(
                active_test=False
            ).product_variant_ids.storage_category_capacity_ids
            for capacity, vals in zip(capacities, capacities.copy_data(), strict=True):
                attribute_value = capacity.product_id.product_template_attribute_value_ids.product_attribute_value_id
                new_variant_id = new_variant_id_by_value.get(attribute_value)
                if not new_variant_id or vals is None:
                    continue
                storage_category_capacity_vals.append(
                    {**vals, "product_id": new_variant_id},
                )
        Capacity.create(storage_category_capacity_vals)
        return new_products

    def _default_responsible_id(self):
        return False if self.env.user._is_superuser() else self.env.uid

    @api.model
    def _default_lot_sequence(self):
        return (
            self.env.ref("stock.sequence_production_lots", raise_if_not_found=False)
            or self.env["ir.sequence"]
        )

    @api.depends(
        "product_variant_ids.orderpoint_ids.product_min_qty",
        "product_variant_ids.orderpoint_ids.product_max_qty",
    )
    def _compute_count_reordering_rules(self):
        res = defaultdict(lambda: {"count": 0, "min": 0.0, "max": 0.0})
        for product, count, product_min_qty, product_max_qty in self.env[
            "stock.warehouse.orderpoint"
        ]._read_group(
            [("product_id.product_tmpl_id", "in", self.ids)],
            ["product_id"],
            ["__count", "product_min_qty:sum", "product_max_qty:sum"],
        ):
            agg = res[product.product_tmpl_id.id]
            agg["count"] += count
            agg["min"] += product_min_qty
            agg["max"] += product_max_qty
        for template in self:
            agg = res[template._origin.id]
            template.count_reordering_rules = agg["count"]
            template.reordering_qty_min = agg["min"]
            template.reordering_qty_max = agg["max"]

    @api.depends("type")
    def _compute_is_storable(self):
        self.filtered(lambda t: t.type != "consu" and t.is_storable).is_storable = False

    @api.depends("is_storable")
    def _compute_tracking(self):
        self.filtered(
            lambda t: not t.is_storable and t.tracking != "none",
        ).tracking = "none"

    @api.depends("lot_sequence_id.prefix")
    def _compute_serial_prefix_format(self):
        for template in self:
            template.serial_prefix_format = template.lot_sequence_id.prefix or ""

    @api.depends(
        "lot_sequence_id.prefix",
        "lot_sequence_id.number_next_actual",
        "lot_sequence_id.padding",
        "lot_sequence_id.suffix",
    )
    def _compute_next_serial(self):
        default_sequence = self._default_lot_sequence()
        for template in self:
            sequence = template.lot_sequence_id or default_sequence
            template.next_serial = sequence.preview_next() if sequence else ""

    @api.depends("is_storable", "product_variant_ids")
    def _compute_show_qty_status_button(self):
        for template in self:
            template.show_on_hand_qty_status_button = template.is_storable
            template.show_forecasted_qty_status_button = bool(
                template.is_storable and template.product_variant_id
            )

    def _compute_has_available_route_ids(self):
        self.has_available_route_ids = self._default_has_available_route_ids()

    @api.model
    def _default_has_available_route_ids(self):
        return bool(
            self.env["stock.route"].search_count(
                [("product_selectable", "=", True)],
                limit=1,
            )
        )

    @api.depends("product_variant_count", "tracking")
    def _compute_show_qty_update_button(self):
        for product in self:
            product.show_qty_update_button = (
                product._should_open_product_quants()
                or product.product_variant_count > 1
            )

    @api.depends(
        "product_variant_ids.qty_available",
        "product_variant_ids.qty_available_virtual",
        "product_variant_ids.qty_incoming",
        "product_variant_ids.qty_outgoing",
    )
    @api.depends_context(
        "lot_id",
        "owner_id",
        "owners",
        "package_id",
        "from_date",
        "to_date",
        "location",
        "warehouse_id",
        "search_location",
        "search_warehouse",
        "allowed_company_ids",
        "strict",
        "skip_in_progress",
        "with_expiration",
        "fresh_qty_forecast",
    )
    def _compute_quantities(self):
        res = self._aggregate_variant_quantities()
        for template in self.with_context(skip_qty_available_update=True):
            template.update(res[template.id])

    def _aggregate_variant_quantities(self):
        self.product_variant_ids._origin.fetch(TEMPLATE_QUANTITY_FIELDS)
        prod_available = {}
        for template in self:
            variants = template.product_variant_ids._origin
            prod_available[template.id] = {
                fname: sum(variants.mapped(fname)) for fname in TEMPLATE_QUANTITY_FIELDS
            }
        return prod_available

    @api.depends(
        "product_variant_ids.count_moves_in",
        "product_variant_ids.count_moves_out",
    )
    def _compute_count_moves(self):
        fnames = ("count_moves_in", "count_moves_out")
        self.product_variant_ids._origin.fetch(fnames)
        for template in self:
            variants = template.product_variant_ids._origin
            for fname in fnames:
                template[fname] = sum(variants.mapped(fname))

    def _inverse_serial_prefix_format(self):
        default_sequence = self._default_lot_sequence()
        valid_sequences = self.env["ir.sequence"].search(
            [
                ("code", "=", "stock.lot.serial"),
                ("prefix", "in", self.mapped("serial_prefix_format")),
                ("company_id", "in", [*self.company_id.ids, False]),
            ],
        )
        sequences_by_key = {
            (seq.prefix, seq.company_id.id): seq for seq in valid_sequences
        }
        for template in self:
            if not template.serial_prefix_format:
                template.lot_sequence_id = default_sequence
                continue
            key = (template.serial_prefix_format, template.company_id.id)
            sequence = sequences_by_key.get(key)
            if not sequence:
                sequence = self.env["ir.sequence"].create(
                    {
                        "name": f"{template.name} Serial Sequence",
                        "code": "stock.lot.serial",
                        "prefix": template.serial_prefix_format,
                        "padding": default_sequence.padding or 7,
                        "company_id": template.company_id.id,
                    },
                )
                sequences_by_key[key] = sequence
            template.lot_sequence_id = sequence

    def _inverse_qty_available(self):
        if self.env.context.get("skip_qty_available_update", False):
            return
        self._set_qty_available([template.qty_available for template in self])

    def _search_variant_quantity(self, field_name, operator, value):
        Product = self.env["product.product"]
        operation = PY_OPERATORS.get(operator)
        if operation is None:
            return self._filter_quantity_in_python(field_name, operator, value)

        location_domains = Product._get_domain_locations()
        candidates = Product._get_quantity_search_candidates(
            location_domains=location_domains
        )
        vals_by_variant = candidates.with_context(
            prefetch_fields=False
        )._prepare_quantities_vals(
            self.env.context.get("lot_id"),
            self.env.context.get("owner_id"),
            self.env.context.get("package_id"),
            self.env.context.get("from_date", False),
            self.env.context.get("to_date", False),
            location_domains=location_domains,
        )
        totals = defaultdict(float)
        for variant in candidates.filtered("active"):
            totals[variant.product_tmpl_id.id] += vals_by_variant[variant.id][
                field_name
            ]
        matched = [
            tmpl_id for tmpl_id, total in totals.items() if operation(total, value)
        ]
        if operation(0.0, value):
            return ["|", ("id", "in", matched), ("id", "not in", list(totals))]
        return [("id", "in", matched)]

    def _filter_quantity_in_python(self, field_name, operator, value):
        records = self.with_context(prefetch_fields=False).search_fetch(
            [], [field_name], order="id"
        )
        positive_operator = Domain.NEGATIVE_OPERATORS.get(operator, operator)
        predicate = self._fields[field_name].filter_function(
            records, field_name, positive_operator, value
        )
        if positive_operator != operator:
            matched_records = records.filtered(lambda rec: not predicate(rec))
        else:
            matched_records = records.filtered(predicate)
        return [("id", "in", matched_records.ids)]

    def _search_qty_available(self, operator, value):
        return self._search_variant_quantity("qty_available", operator, value)

    def _search_qty_available_virtual(self, operator, value):
        return self._search_variant_quantity("qty_available_virtual", operator, value)

    def _search_qty_incoming(self, operator, value):
        return self._search_variant_quantity("qty_incoming", operator, value)

    def _search_qty_outgoing(self, operator, value):
        return self._search_variant_quantity("qty_outgoing", operator, value)

    @api.onchange("tracking")
    def _onchange_tracking(self):
        return self.product_variant_ids._onchange_tracking()

    @api.onchange("type")
    def _onchange_type(self):
        res = super()._onchange_type()
        variant_ids = self.with_context(active_test=False).product_variant_ids.ids
        if (
            self.ids
            and variant_ids
            and self.env["stock.move.line"]
            .sudo()
            .search_count(
                [
                    ("product_id", "in", variant_ids),
                    ("state", "!=", "cancel"),
                ],
                limit=1,
            )
        ):
            res["warning"] = {
                "title": _("Warning!"),
                "message": _(
                    "This product has been used in at least one inventory movement. "
                    "It is not advised to change the Product Type since it can lead to inconsistencies. "
                    "A better solution could be to archive the product and create a new one instead."
                ),
            }
        return res

    def action_view_quants(self):
        variants = self.with_context(active_test=False).product_variant_ids
        return variants.filtered(
            lambda p: p.active or p.qty_available != 0,
        ).action_view_quants()

    def action_view_related_putaway_rules(self):
        self.ensure_one()
        domain = [
            "|",
            ("product_id.product_tmpl_id", "=", self.id),
            ("category_id", "=", self.categ_id.id),
        ]
        return self._get_action_view_related_putaway_rules(domain)

    def action_view_storage_category_capacity(self):
        self.ensure_one()
        return self.product_variant_ids.action_view_storage_category_capacity()

    def action_view_orderpoints(self):
        return self.product_variant_ids.action_view_orderpoints()

    def action_view_stock_move_lines(self):
        self.ensure_one()
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.stock_move_line_action",
        )
        action["domain"] = [("product_id.product_tmpl_id", "=", self.id)]
        return action

    def action_view_product_lot(self):
        self.ensure_one()
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.action_stock_lot_form_2",
        )
        action["domain"] = [
            ("product_id.product_tmpl_id", "=", self.id),
            *self.env["stock.lot"]._get_accessible_location_domain(),
        ]
        action["context"] = {
            "default_product_tmpl_id": self.id,
            "search_default_group_by_location": True,
        }
        if self.product_variant_count == 1:
            action["context"].update(
                {
                    "default_product_id": self.product_variant_id.id,
                },
            )
        return action

    def _resolve_diagram_products(self):
        Product = self.env["product.product"]
        if self.env.context.get("default_product_id"):
            products = Product.browse(self.env.context["default_product_id"])
            if products:
                return products
        if self.env.context.get("default_product_tmpl_id"):
            products = self.browse(
                self.env.context["default_product_tmpl_id"]
            ).product_variant_ids
            if products:
                return products
        templates = self or self.browse(self.env.context.get("active_id") or [])
        return templates.product_variant_ids

    def action_view_routes_diagram(self):
        products = self._resolve_diagram_products()
        if (
            not self.env.user.has_group("stock.group_stock_multi_warehouses")
            and len(products) == 1
        ):
            company = products.company_id or self.env.company
            warehouse = self.env["stock.warehouse"].search(
                [("company_id", "=", company.id)],
                limit=1,
            )
            if not warehouse:
                self.env["stock.warehouse"]._warehouse_redirect_warning()
            return self.env.ref("stock.action_report_stock_rule").report_action(
                None,
                data={
                    "product_id": products.id,
                    "warehouse_ids": warehouse.ids,
                },
                config=False,
            )
        action = self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.action_stock_rules_report",
        )
        action["context"] = {
            "default_product_id": products[:1].id,
            "default_product_tmpl_id": products[:1].product_tmpl_id.id,
        }
        return action

    def action_product_tmpl_forecast_report(self):
        self.ensure_one()
        if not self.env.user._get_default_warehouse_id():
            self.env["stock.warehouse"]._warehouse_redirect_warning()
        return self.env["ir.actions.actions"]._get_action_dict_by_xml_id(
            "stock.stock_forecasted_product_template_action",
        )

    def _reset_inventory(self):
        move_line_domain = Domain(
            [
                (
                    "product_id",
                    "in",
                    self.with_context(active_test=False).product_variant_ids.ids,
                ),
                ("state", "=", "done"),
                "|",
                ("location_usage", "in", ("internal", "transit")),
                ("location_dest_usage", "in", ("internal", "transit")),
            ],
        )
        move_lines_to_match = self.env["stock.move.line"].search_fetch(
            move_line_domain,
            [
                "product_id",
                "location_id",
                "location_dest_id",
                "quantity_product_uom",
            ],
        )
        inventory_ledger = defaultdict(float)
        for move_line in move_lines_to_match:
            if move_line.location_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_id] -= (
                    move_line.quantity_product_uom
                )
            if move_line.location_dest_usage in ("internal", "transit"):
                inventory_ledger[move_line.product_id, move_line.location_dest_id] += (
                    move_line.quantity_product_uom
                )
        quants_to_reset = self.env["stock.quant"].create(
            [
                {
                    "product_id": product.id,
                    "location_id": location.id,
                    "quantity": quantity,
                    "inventory_quantity": 0.0,
                }
                for (product, location), quantity in inventory_ledger.items()
                if not product.uom_id.is_zero(quantity)
            ],
        )
        quants_to_reset._apply_inventory()

    @api.model
    def _get_action_view_related_putaway_rules(self, domain):
        return {
            "name": _("Putaway Rules"),
            "type": "ir.actions.act_window",
            "res_model": "stock.putaway.rule",
            "view_mode": "list",
            "domain": domain,
        }

    @api.model
    def _has_advanced_stock_option(self):
        advanced_option_groups = [
            "stock.group_stock_multi_locations",
            "stock.group_tracking_owner",
            "stock.group_tracking_lot",
        ]
        return any(self.env.user.has_group(g) for g in advanced_option_groups)

    def _should_open_product_quants(self):
        self.ensure_one()
        return self._has_advanced_stock_option() or self.tracking != "none"
