{
    "name": "Documents",
    "summary": "Collect, organize and share documents.",
    "description": """
Store, organize and share files: a folder tree with per-document access rights,
share links, versioning, a trash and the Documents workspace.

`documents_enterprise` adds the sharing, operation and link-to-record wizards,
the onboarding tour, the digest KPIs and the Studio automation upsell.
    """,
    "category": "Productivity/Documents",
    "sequence": 80,
    "version": "1.6",
    "author": "Odoo S.A.",
    "website": "https://www.odoo.com/app/documents",
    "depends": [
        "mail",
        "portal",
        "attachment_indexation",
        "html_editor",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/mail_template_data.xml",
        "data/mail_activity_type_data.xml",
        "data/documents_tag_data.xml",
        "data/documents_document_data.xml",
        "data/mail_alias_data.xml",
        "data/ir_config_parameter_data.xml",
        "data/ir_cron_data.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/documents_access_views.xml",
        "views/documents_document_views.xml",
        "views/documents_folder_views.xml",
        "views/documents_tag_views.xml",
        "views/mail_activity_views.xml",
        "views/mail_activity_plan_views.xml",
        "views/mail_alias_views.xml",
        "views/documents_menu_views.xml",
        "views/documents_access_log_views.xml",
        "views/documents_templates_portal.xml",
        "views/documents_templates_share.xml",
        "views/documents_templates_thumbnails.xml",
        "views/ir_actions_views.xml",
        "views/mail_compose_message_views.xml",
        "views/mail_scheduled_message_views.xml",
        "wizard/documents_request_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "documents/static/src/scss/documents_views.scss",
            "documents/static/src/scss/documents_kanban_view.scss",
            "documents/static/src/attachments/**/*",
            "documents/static/src/core/**/*",
            "documents/static/src/js/**/*",
            "documents/static/src/mail/**/*",
            "documents/static/src/owl/**/*",
            "documents/static/src/utils.js",
            "documents/static/src/views/**/*",
            "documents/static/src/webclient/webclient.js",
            (
                "after",
                "web/static/src/components/errors/error_dialogs.xml",
                "documents/static/src/web/error_dialog/error_dialog_patch.xml",
            ),
            "documents/static/src/web/**/*",
            "documents/static/src/components/**/*",
            "documents/static/src/editor/**/*",
        ],
        "web._assets_primary_variables": [
            "documents/static/src/scss/documents.variables.scss",
        ],
        "web.assets_tests": [
            "documents/static/tests/tours/*",
        ],
        "web.assets_unit_tests": [
            "documents/static/tests/**/*",
        ],
        "documents.public_page_assets": [
            ("include", "web._assets_helpers"),
            ("include", "web._assets_backend_helpers"),
            "web/static/src/scss/pre_variables.scss",
            "web/static/lib/bootstrap/scss/_variables.scss",
            "web/static/lib/bootstrap/scss/_variables-dark.scss",
            "web/static/lib/bootstrap/scss/_maps.scss",
            ("include", "web._assets_bootstrap_backend"),
            "documents/static/src/scss/documents_public_pages.scss",
        ],
        "documents.webclient": [
            ("include", "web.assets_backend"),
            "documents/static/src/portal_webclient/**/*",
            "web/static/src/boot/start.js",
        ],
    },
    "esm": {
        "bundles": [
            "documents.public_page_assets",
            "documents.webclient",
        ],
        "secondary_import_map_includes": {
            "documents.webclient": ["web.assets_tests"],
        },
    },
    "demo": [
        "demo/documents_document_demo.xml",
    ],
    "application": True,
    "license": "LGPL-3",
}
