from . import test_purchase
from . import test_purchase_advanced
from . import test_purchase_downpayment
from . import test_purchase_flow
from . import test_purchase_order_line_compute
from . import test_purchase_order_product_catalog
from . import test_purchase_order_report
from . import test_purchase_invoice
from . import test_purchase_portal
from . import test_access_rights
from . import test_accrued_purchase_orders
from . import test_purchase_dashboard
from . import test_import_files
from . import test_purchase_product_catalog
from . import test_purchase_performance
from . import test_purchase_order_write_validation
from . import test_purchase_fixes
from . import test_invoiced_uom_guard
from . import test_product_purchase_stats
from . import test_partner_purchase_stats
from . import test_analytic_purchase_button
from . import test_partner_buyer
from . import test_tax_usage
from . import test_bill_line_match
from . import test_product_uom_guard
from . import test_account_move_create_purchase
from . import test_purchase_price_history
