from . import test_attendances
from . import test_calendar_sync
from . import test_hr_employee
from . import test_hr_employee_public
from . import test_channel
from . import test_self_user_access
from . import test_mail_activity_plan
from . import test_mail_features
from . import test_multi_company
from . import test_payroll_fields_access
from . import test_resource
from . import test_ui
from . import test_scenario
from . import test_hr_department
from . import test_hr_departure_reason
from . import test_hr_payroll_structure_type
from . import test_hr_work_location
from . import test_hr_version
from . import test_hr_contract_versions
from . import test_flexible_resource_calendar
from . import test_multiple_bank_accounts
from . import test_hr_audit_fixes
from . import test_hr_audit_round3
