from . import res_company
from . import res_users
from . import resource_calendar
from . import resource_calendar_attendance
from . import resource_calendar_leaves
from . import resource_mixin
from . import resource_resource
from . import resource_scheduling_tools
from . import resource_scheduling_mixin
from . import resource_reservation
from . import utils
