import logging
import re
from ast import literal_eval
from typing import Any, Self

from odoo import _, api, models
from odoo.api import ValuesType
from odoo.exceptions import AccessError, RedirectWarning, UserError

_logger = logging.getLogger(__name__)

# ``env.cr.cache`` key ({model_name: classified}) where ``execute()`` stashes the
# ``_get_classified_fields()`` result for ``set_values()`` to reuse. It can't be
# passed as an argument because ``set_values()`` is overridden as ``def
# set_values(self)`` across the codebase. ``cr.cache`` is transaction-local and
# ``execute()`` pops the entry in a ``finally``, so it can't leak across saves.
SETTINGS_CLASSIFIED_CACHE_KEY = "res_config_settings_classified_fields"


class ResConfig(models.TransientModel):
    """Base class for new-style configuration items.

    Subclass, implement ``execute`` (and optionally ``cancel``), and inherit the
    view from ``res_config_view_base``.
    """

    _name = "res.config"
    _description = "Config"

    def start(self) -> dict[str, str]:
        return self._next_todo_action()

    def _next_todo_action(self) -> dict[str, str]:
        """Reload the settings page."""
        return {
            "type": "ir.actions.client",
            "tag": "reload",
        }

    def execute(self) -> dict[str, Any] | None:
        """Handle the ``Next`` button. Must be overloaded (unless ``action_next``
        is). A returned action dictionary is executed instead of advancing to the
        next configuration item.
        """
        msg = "Configuration items need to implement execute"
        raise NotImplementedError(msg)

    def cancel(self) -> dict[str, Any] | None:
        """Handle the ``Skip`` button (overload this, not ``action_skip``). Like
        ``execute``, a returned action dictionary is executed instead of advancing
        to the next configuration item. Default is a no-op. Also called by the
        default ``action_cancel``.
        """
        pass

    def action_next(self) -> dict[str, Any] | None:
        """Call ``execute``; return its action or ``_next_todo_action``."""
        return self.execute() or self._next_todo_action()

    def action_skip(self) -> dict[str, Any] | None:
        """Call ``cancel``; return its action or ``_next_todo_action``."""
        return self.cancel() or self._next_todo_action()

    def action_cancel(self) -> dict[str, Any] | None:
        """Call ``cancel``; return its action or ``_next_todo_action``. The
        ``cancel`` event isn't generated by ``res.config.view.base``; an inheriting
        view must overload a button (or add one) to trigger it.
        """
        return self.cancel() or self._next_todo_action()


class ResConfigSettings(models.TransientModel):
    """Base configuration wizard for application settings.

    Subclass ``res.config.settings`` and name fields by prefix; ``execute``
    dispatches on the prefix, ``default_get`` reflects the current status back:

    *   ``default_XXX`` (needs ``default_model``): sets/reads the global default of
        field ``XXX`` on ``default_model``.
    *   ``group_XXX`` (boolean or '0'/'1' selection; needs ``implied_group``,
        optional ``group``): adds/removes ``implied_group`` on ``group`` (default:
        Employee). ``group`` is comma-separated xml ids.
    *   ``module_XXX`` (boolean only): installs module ``XXX`` when True. Selection
        is unsupported — the historical support was broken and never used.
    *   any field with ``config_parameter``: stores/reads an ir.config.parameter.
    *   other fields: handled by ``set_values`` / ``get_values`` (override these).
    """

    _name = "res.config.settings"
    _description = "Config Settings"

    def _valid_field_parameter(self, field: Any, name: str) -> bool:
        return (
            name in ("default_model", "config_parameter")
            or (
                field.type in ("boolean", "selection")
                and name in ("group", "implied_group")
            )
            or super()._valid_field_parameter(field, name)
        )

    def copy(self, default: ValuesType | None = None) -> Self:
        raise UserError(_("Cannot duplicate configuration!"))

    @api.model
    def _install_modules(self, modules: Any) -> Any:
        """Install the requested modules.

        :param modules: a recordset of ir.module.module records
        :return: the next action to execute
        """
        result = None

        to_install_modules = modules.filtered(
            lambda module: module.state == "uninstalled"
        )
        if to_install_modules:
            result = to_install_modules.button_immediate_install()

        return result

    @api.model
    def _get_classified_fields(self, fnames: Any = None) -> dict[str, Any]:
        """Return the settings fields classified by category:

        .. code-block:: python

            {
                "default": [("default_foo", "model", "foo"), ...],
                "group": [("group_bar", [browse_group], browse_implied_group), ...],
                "module": browse_modules,  # recordset of ir.module.module
                "config": [("config_qux", "my.parameter"), ...],
                "other": ["other_field", ...],
            }
        """
        IrModule = self.env["ir.module.module"]
        IrModelData = self.env["ir.model.data"]
        Groups = self.env["res.groups"]

        def ref(xml_id):
            res_model, res_id = IrModelData._xmlid_to_res_model_res_id(
                xml_id, raise_if_not_found=True
            )
            return self.env[res_model].browse(res_id)

        if fnames is None:
            fnames = self._fields.keys()

        defaults, groups, configs, others = [], [], [], []
        module_recs = []
        for name in fnames:
            field = self._fields[name]
            if name.startswith("default_"):
                if not hasattr(field, "default_model"):
                    raise TypeError(f"Field {field} without attribute 'default_model'")
                defaults.append(
                    (name, field.default_model, name.removeprefix("default_"))
                )
            elif name.startswith("group_"):
                if field.type not in ("boolean", "selection"):
                    raise TypeError(
                        f"Field {field} must have type 'boolean' or 'selection'"
                    )
                if not hasattr(field, "implied_group"):
                    raise TypeError(f"Field {field} without attribute 'implied_group'")
                field_group_xmlids = getattr(field, "group", "base.group_user").split(
                    ","
                )
                field_groups = Groups.concat(*(ref(it) for it in field_group_xmlids))
                groups.append((name, field_groups, ref(field.implied_group)))
            elif name.startswith("module_"):
                # module_ must be boolean: the selection variant was broken
                # everywhere it was read ('0' is truthy in execute()) and unused.
                if field.type != "boolean":
                    raise TypeError(f"Field {field} must have type 'boolean'")
                module_recs.append(IrModule._get(name.removeprefix("module_")))
            elif hasattr(field, "config_parameter") and field.config_parameter:
                if field.type not in (
                    "boolean",
                    "integer",
                    "float",
                    "char",
                    "selection",
                    "many2one",
                    "datetime",
                ):
                    raise TypeError(
                        "Field %s must have type 'boolean', 'integer', 'float', 'char', 'selection', 'many2one' or 'datetime'"
                        % field
                    )
                configs.append((name, field.config_parameter))
            else:
                others.append(name)

        modules = IrModule.concat(*module_recs) if module_recs else IrModule
        return {
            "default": defaults,
            "group": groups,
            "module": modules,
            "config": configs,
            "other": others,
        }

    @api.model
    def get_values(self) -> dict[str, Any]:
        """Return values for the fields other than `default`, `group` and `module`."""
        return {}

    @api.model
    def default_get(self, fields: list[str]) -> dict[str, Any]:
        res = super().default_get(fields)
        if not fields:
            return res

        IrDefault = self.env["ir.default"]
        IrConfigParameter = self.env["ir.config_parameter"].sudo()
        classified = self._get_classified_fields(fields)

        # defaults: take the corresponding default value they set
        for name, model, field in classified["default"]:
            value = IrDefault._get(model, field)
            if value is not None:
                res[name] = value

        # groups: which groups are implied by the group Employee
        for name, groups, implied_group in classified["group"]:
            res[name] = all(implied_group in group.all_implied_ids for group in groups)
            if self._fields[name].type == "selection":
                res[name] = str(int(res[name]))  # True, False -> '1', '0'

        # modules: which modules are installed/to install
        for module in classified["module"]:
            res[f"module_{module.name}"] = module.state in (
                "installed",
                "to install",
                "to upgrade",
            )

        # config: get & convert stored ir.config_parameter (or default)
        WARNING_MESSAGE = (
            "Error when converting value %r of field %s for ir.config.parameter %r"
        )
        for name, icp in classified["config"]:
            field = self._fields[name]
            default_value = (
                field.default(self) if callable(field.default) else field.default
            )
            value = IrConfigParameter.get_param(icp, default_value or False)
            if value is not False:
                match field.type:
                    case "many2one":
                        try:
                            # tolerate ids of deleted records so the settings
                            # screen still opens
                            value = (
                                self.env[field.comodel_name]
                                .browse(int(value))
                                .exists()
                                .id
                            )
                        except ValueError, TypeError:
                            _logger.warning(WARNING_MESSAGE, value, field, icp)
                            value = False
                    case "integer":
                        try:
                            value = int(value)
                        except ValueError, TypeError:
                            _logger.warning(WARNING_MESSAGE, value, field, icp)
                            value = 0
                    case "float":
                        try:
                            value = float(value)
                        except ValueError, TypeError:
                            _logger.warning(WARNING_MESSAGE, value, field, icp)
                            value = 0.0
                    case "boolean":
                        # RCFG-B1: an unstored param yields the field default (a
                        # real bool, not "True"/"False"); str() handles both.
                        value = str(value) == "True"
            res[name] = value

        res.update(self.get_values())

        return res

    def set_values(self, classified: dict[str, Any] | None = None) -> None:
        """Set values for the fields other than `default`, `group` and `module`.

        :param classified: optional precomputed :meth:`_get_classified_fields`
            result. When None (e.g. overrides calling ``super().set_values()``),
            the classification stashed by :meth:`execute` is reused, or computed
            lazily for standalone calls.
        """
        # RCFG-L1: defense-in-depth admin gate. set_values does sudo'd,
        # ACL-bypassing writes (ir.default, res.groups.implied_ids,
        # ir.config_parameter) and otherwise relies solely on the model ACL.
        if not self.env.is_admin():
            raise AccessError(
                self.env._("Only administrators can change system settings.")
            )

        self = self.with_context(active_test=False)
        if classified is None:
            stash = self.env.cr.cache.get(SETTINGS_CLASSIFIED_CACHE_KEY)
            classified = (stash or {}).get(self._name) or self._get_classified_fields()
        # restrict the diff basis to the names compared below (default_ and
        # group_ fields) so default_get classifies only those
        compared_names = [name for name, _model, _field in classified["default"]]
        compared_names += [name for name, _groups, _implied in classified["group"]]
        current_settings = self.default_get(compared_names)

        # default values fields
        IrDefault = self.env["ir.default"].sudo()
        for name, model, field in classified["default"]:
            if isinstance(self[name], models.BaseModel):
                if self._fields[name].type == "many2one":
                    value = self[name].id
                else:
                    value = self[name].ids
            else:
                value = self[name]
            if name not in current_settings or value != current_settings[name]:
                IrDefault.set(model, field, value)

        # group fields: process removals (falsy) before additions. RCFG-S1:
        # normalize the sort key to bool since group_ fields may mix boolean and
        # '0'/'1' selection, and sorted() can't compare bool with str.
        for name, groups, implied_group in sorted(
            classified["group"], key=lambda k: bool(int(self[k[0]] or 0))
        ):
            # sudo: writing res.groups.implied_ids needs group_erp_manager, which
            # the env user may lack when settings apply from module install/tests.
            groups = groups.sudo()
            implied_group = implied_group.sudo()
            if self[name] == current_settings[name]:
                continue
            if self[name] and int(self[name]):
                groups._apply_group(implied_group)
            else:
                groups._remove_group(implied_group)

        # config fields: store ir.config_parameters
        IrConfigParameter = self.env["ir.config_parameter"].sudo()
        for name, icp in classified["config"]:
            field = self._fields[name]
            value = self[name]
            current_value = IrConfigParameter.get_param(icp)

            if field.type == "char":
                # strip surrounding spaces: stored developer keys break subtly
                # when users leave whitespace around them
                value = (value or "").strip() or False
            elif field.type in ("integer", "float"):
                value = repr(value) if value is not None else False
            elif field.type == "many2one":
                # value is a (possibly empty) recordset
                value = value.id
            elif field.type == "boolean":
                # RCFG-B1: store False as "False" to bypass set_param()'s
                # delete-on-falsy path; deleting would make False look "not set"
                # and let a default=True field silently revert
                value = str(bool(value))

            if current_value == str(value) or current_value == value:
                continue
            IrConfigParameter.set_param(icp, value)

    def execute(self) -> dict[str, Any]:
        """Apply saved settings: call `set_values`, install/uninstall `module_`
        fields, then reload the web client.

        .. warning::

            Override `set_values`, not this method. Module install/uninstall
            **MUST** stay at the end of the transaction or the registry and
            database can desynchronise.
        """
        self.ensure_one()
        if not self.env.is_admin():
            raise AccessError(_("Only administrators can change the settings"))

        self = self.with_context(active_test=False)
        # classify once per save; set_values() and its default_get() reuse it
        classified = self._get_classified_fields()

        stash = self.env.cr.cache.setdefault(SETTINGS_CLASSIFIED_CACHE_KEY, {})
        stash[self._name] = classified
        try:
            self.set_values()
        finally:
            stash.pop(self._name, None)

        # module fields: install/uninstall the selected modules
        to_install = classified["module"].filtered(
            lambda m: self[f"module_{m.name}"] and m.state != "installed"
        )
        to_uninstall = classified["module"].filtered(
            lambda m: (
                not self[f"module_{m.name}"] and m.state in ("installed", "to upgrade")
            )
        )

        if to_install or to_uninstall:
            self.env.flush_all()

        if to_uninstall:
            return {
                "type": "ir.actions.act_window",
                "target": "new",
                "name": _("Uninstall modules"),
                "view_mode": "form",
                "res_model": "base.module.uninstall",
                "context": {
                    "default_module_ids": to_uninstall.ids,
                },
            }

        installation_status = self._install_modules(to_install)

        if installation_status:
            # the install invalidated the registry and environments
            self.env.transaction.reset()

        # force client-side reload (update user menu and current view)
        return self.env["res.config"]._next_todo_action()

    def cancel(self) -> dict[str, Any]:
        # ignore the current record, and send the action to reopen the view
        actions = self.env["ir.actions.act_window"].search(
            [("res_model", "=", self._name)], limit=1
        )
        if actions:
            return actions.read()[0]
        return {}

    def _compute_display_name(self) -> None:
        """Return the configuration wizard's action name, not the generated one."""
        action = self.env["ir.actions.act_window"].search(
            [("res_model", "=", self._name)], limit=1
        )
        self.display_name = action.name or self._name

    @api.model
    def get_option_path(self, menu_xml_id: str) -> tuple[str, int]:
        """Return the path to a configuration view and the action id to access it.

        :param str menu_xml_id: xml id of the menuitem, as
            module_name.menuitem_xml_id (e.g. "sales_team.menu_sale_config")
        :return: (full menuitem path e.g. "Settings/Configuration/Sales",
            menuitem action id)
        """
        ir_ui_menu = self.env.ref(menu_xml_id)
        return (ir_ui_menu.complete_name, ir_ui_menu.action.id)

    @api.model
    def get_option_name(self, full_field_name: str) -> str:
        """Return the human readable name of a configuration option.

        :param str full_field_name: full field name as model_name.field_name
            (e.g. "sale.config.settings.fetchmail_lead")
        :return: human readable field name (e.g. "Create leads from incoming mails")
        :rtype: str
        """
        model_name, field_name = full_field_name.rsplit(".", 1)
        return self.env[model_name].fields_get([field_name])[field_name]["string"]

    @api.model
    def get_config_warning(self, msg: str) -> RedirectWarning | UserError:
        """Return a Warning exception with ``%(field:model.field)s`` /
        ``%(menu:module.menuitem)s`` placeholders in ``msg`` replaced by the
        human readable field name / menuitem full path.

        .. code-block:: python

            raise self.get_config_warning(
                _(
                    "Error: this action is prohibited. You should check the "
                    "field %(field:sale.config.settings.fetchmail_lead)s in "
                    "%(menu:sales_team.menu_sale_config)s."
                )
            )

        If ``msg`` already contains an unrelated ``%s`` substitution, escape the
        placeholder's percent as ``%%(menu:...)s`` to leave the rest untouched.
        """
        self = self.sudo()

        # collect the menu/field references
        regex_path = r"%\(((?:menu|field):[a-z_\.]*)\)s"
        references = re.findall(regex_path, msg, flags=re.IGNORECASE)

        # resolve each reference to its replacement value (and action_id)
        values = {}
        action_id = None
        for item in references:
            ref_type, ref = item.split(":")
            if ref_type == "menu":
                values[item], action_id = self.get_option_path(ref)
            elif ref_type == "field":
                values[item] = self.get_option_name(ref)

        # substitute and return
        if action_id:
            return RedirectWarning(
                msg % values, action_id, _("Go to the configuration panel")
            )
        return UserError(msg % values)

    @api.model_create_multi
    def create(self, vals_list: list[ValuesType]) -> Self:
        # Optimisation: saving unchanged related values would write them all and
        # cascade recomputations. Drop values that did not actually change.
        for vals in vals_list:
            for field in self._fields.values():
                if not (field.name in vals and field.related and not field.readonly):
                    continue
                # writable related field, e.g.
                # qr_code = fields.Boolean(related='company_id.qr_code', readonly=False)
                fname0, *fnames = field.related.split(".")
                if fname0 not in vals:
                    continue

                # determine the current value
                field0 = self._fields[fname0]
                old_value = field0.convert_to_record(
                    field0.convert_to_cache(vals[fname0], self), self
                )
                for fname in fnames:
                    old_value = next(iter(old_value), old_value)[fname]

                # determine the new value
                new_value = field.convert_to_record(
                    field.convert_to_cache(vals[field.name], self), self
                )

                # drop if the value is the same
                if old_value == new_value:
                    vals.pop(field.name)

        return super().create(vals_list)

    def action_open_template_user(self) -> dict[str, Any]:
        action = self.env["ir.actions.actions"]._for_xml_id("base.action_res_users")
        try:
            template_user_id = literal_eval(
                self.env["ir.config_parameter"]
                .sudo()
                .get_param("base.template_portal_user_id", "False")
            )
        except ValueError, SyntaxError:
            template_user_id = False
        template_user = self.env["res.users"].browse(template_user_id)
        if not template_user.exists():
            raise UserError(_("Invalid template user. It seems it has been deleted."))
        action["res_id"] = template_user_id
        action["views"] = [[self.env.ref("base.view_users_form").id, "form"]]
        return action
