from odoo import _, api, fields, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    mrp_production_count = fields.Count(
        "mrp_production_ids",
        "Count of MO generated",
        groups="mrp.group_mrp_user",
    )
    mrp_production_ids = fields.Many2many(
        "mrp.production",
        compute="_compute_mrp_production_ids",
        string="Manufacturing Orders",
        groups="mrp.group_mrp_user",
    )

    @api.depends(
        "stock_reference_ids.production_ids",
        "stock_reference_ids.production_ids.state",
        "stock_reference_ids.production_ids.production_group_id.parent_ids",
    )
    def _compute_mrp_production_ids(self):
        for sale in self:
            mos = sale.stock_reference_ids.production_ids
            sale.mrp_production_ids = mos.filtered(
                lambda mo: (
                    not mo.production_group_id.parent_ids and mo.state != "cancel"
                )
            )

    def action_view_mrp_production(self):
        self.check_singleton()
        action = {
            "res_model": "mrp.production",
            "type": "ir.actions.act_window",
        }
        if len(self.mrp_production_ids) == 1:
            action.update(
                {
                    "view_mode": "form",
                    "res_id": self.mrp_production_ids.id,
                }
            )
        else:
            action.update(
                {
                    "name": _("Manufacturing Orders Generated by %s", self.name),
                    "domain": [("id", "in", self.mrp_production_ids.ids)],
                    "view_mode": "list,form",
                }
            )
        return action
