from . import test_order_amount
from . import test_order_line_amount
from . import test_order_merge
from . import test_order_edi_report
from . import test_order_portal
from . import test_order_report
from . import test_order_shared_features
from . import test_order_partner_domain
from . import test_order_document_match_guard
from . import test_order_invoice_refund_chain
