from . import test_catalog
from . import test_confirm_validation
from . import test_document_match
from . import test_duplicates
from . import test_header_misc
from . import test_invoice
from . import test_invoice_state
from . import test_line_amounts
from . import test_line_fields
from . import test_line_match
from . import test_line_pricing
from . import test_line_write_guards
from . import test_mail
from . import test_merge
from . import test_order_activity
from . import test_order_amounts
from . import test_order_type_declarations
from . import test_partner_count
from . import test_price_history
from . import test_smoke
from . import test_write_validation
from . import test_order_amount
from . import test_order_document_match_guard
from . import test_order_edi_report
from . import test_order_invoice_refund_chain
from . import test_order_line_amount
from . import test_order_merge
from . import test_order_partner_domain
from . import test_order_portal
from . import test_order_report
from . import test_order_shared_features
