from . import test_dunderinit
from . import test_translated_unique
from . import test_checkers
from . import test_python_lint
from . import test_bundle_token_defs
from . import test_color_scheme_reads
from . import test_dark_sibling_scope
from . import test_grey_ramp_token
from . import test_scheme_duplication
from . import test_pofile
from . import test_docstring
from . import test_index
from . import test_jstranslate
from . import test_l10n
from . import test_manifests
from . import test_xml_records
from . import test_pretty_xml
from . import test_fixers
from . import test_markers
from . import test_naming
from . import test_onchange_triggers
from . import test_recipient_data
from . import test_override_signatures
from . import test_pep649
from . import test_routes
from . import test_i18n
from . import test_test_holes
from . import test_esm_specifiers
from . import test_esm_bundles
from . import test_asset_paths_exist
from . import test_bundles_assemble
from . import test_copy_translations
from . import test_menu_parents
