from . import project_pm_mixin
from . import account_analytic_account
from . import mail_message
from . import project_phase
from . import project_task_recurrence

# project_task_triage must be loaded before project_project and project_milestone
from . import project_task_triage
from . import project_milestone
from . import project_project
from . import project_role
from . import project_task
from . import project_workflow_step
from . import project_triage
from . import project_baseline
from . import project_benefit
from . import project_gate
from . import project_history
from . import project_retrospective
from . import project_risk
from . import project_sprint
from . import project_task_dependency
from . import project_tags
from . import project_collaborator
from . import project_update
from . import res_partner
from . import res_users_settings
from . import res_users
from . import digest_digest
from . import ir_ui_menu
