"""A gate's own docstring, kept honest about the numbers it quotes.

Every gate in this directory explains itself in prose, and the good ones quote
the measurement to make the explanation concrete — "293 accesses in 33 files",
"52 of the 59 undeclared reaches come from its own three helpers". That is worth
keeping: a budget without a magnitude is not an argument.

The numbers then rot, silently and in the one place a reader trusts most. Three
instances were live in this tree at once:

* ``js_private_access.py`` opened with 293 accesses in 33 files while measuring
  251 in 29.
* ``record_contract.js`` said twenty undeclared reaches remained. Four did.
* ``.github/workflows/typecheck.yml`` had already been burnt by this and says so
  in its header — "this header once read 2002 while the baseline said 2274 and
  reality was 2155" — and drew the rule *do not restate a floor's value in this
  comment*.

That rule works, and it costs the explanation its magnitudes. This is the other
way to get there: keep the numbers, and make them un-writable by hand.

A participating module carries a block in its docstring::

    MEASURED (regenerated by --update-doc; do not hand-edit)
        total=247 declared=196 module_internal=51 undeclared=0 files=29

``check()`` recomputes and compares; ``update()`` rewrites. Wire ``check()``
into a ``test_*.py`` beside the gate and CI's ``pytest tooling/architecture/``
run turns a stale docstring into a failure, in the same lane as the gate itself.

Prose above the block may then refer to it ("the MEASURED block below") instead
of copying a figure out of it, which is the habit this is trying to buy.
"""

from __future__ import annotations

import re
from pathlib import Path

MARKER = "MEASURED (regenerated by --update-doc; do not hand-edit)"

# The marker line, then exactly one values line indented further than it. Bounded
# at one line on purpose: a block that may span an arbitrary number of lines has
# an ambiguous end, and the first thing to go wrong would be a rewrite eating the
# paragraph after it.
_BLOCK = re.compile(
    r"^(?P<indent>[ \t]*)"
    + re.escape(MARKER)
    + r"[ \t]*\n"
    + r"(?P<vindent>[ \t]+)(?P<values>\S.*)$",
    re.MULTILINE,
)

_PAIR = re.compile(r"([A-Za-z_][\w]*)=(-?\d+)")


class DocMeasuredError(Exception):
    """The module does not carry a well-formed MEASURED block."""


def render(metrics: dict[str, int]) -> str:
    """The values line for ``metrics``, without indentation."""
    return " ".join(f"{k}={v}" for k, v in metrics.items())


def extract(text: str) -> dict[str, int]:
    """The metrics a module's MEASURED block currently claims.

    Raises if the block is missing or holds no ``key=value`` pair, rather than
    returning ``{}``. An absent block and a block claiming nothing would
    otherwise both compare equal to a gate that happens to measure nothing, and
    the check would pass by having found no facts — the same failure the
    empty-tree refusal tests in this directory exist to prevent.
    """
    match = _BLOCK.search(text)
    if not match:
        raise DocMeasuredError(f"no MEASURED block found (marker: {MARKER!r})")
    pairs = _PAIR.findall(match.group("values"))
    if not pairs:
        raise DocMeasuredError(
            f"MEASURED block holds no key=value pair: {match.group('values')!r}"
        )
    return {k: int(v) for k, v in pairs}


def check(path: Path, metrics: dict[str, int]) -> list[str]:
    """Human-readable differences between the block and ``metrics``; [] if fresh.

    Reports missing and extra keys as well as changed values: a metric dropped
    from the docstring is drift too, and the whole point is that the block
    cannot quietly describe less than the gate measures.
    """
    claimed = extract(path.read_text(encoding="utf-8"))
    problems = []
    for key in sorted(set(claimed) | set(metrics)):
        if key not in claimed:
            problems.append(
                f"{key}: missing from the docstring, measured {metrics[key]}"
            )
        elif key not in metrics:
            problems.append(
                f"{key}: in the docstring ({claimed[key]}), no longer measured"
            )
        elif claimed[key] != metrics[key]:
            problems.append(
                f"{key}: docstring says {claimed[key]}, measured {metrics[key]}"
            )
    return problems


def update(path: Path, metrics: dict[str, int]) -> bool:
    """Rewrite the block in place. True if the file changed."""
    text = path.read_text(encoding="utf-8")
    match = _BLOCK.search(text)
    if not match:
        raise DocMeasuredError(f"no MEASURED block found (marker: {MARKER!r})")
    line = f"{match.group('vindent')}{render(metrics)}"
    if line == match.group("vindent") + match.group("values"):
        return False
    start, end = match.span("vindent"), match.span("values")
    new = text[: start[0]] + line + text[end[1] :]
    path.write_text(new, encoding="utf-8")
    return True


def main_flags(parser) -> None:
    """Add the standard pair of flags to a gate's argument parser."""
    parser.add_argument(
        "--check-doc",
        action="store_true",
        help="fail if the module docstring's MEASURED block is stale",
    )
    parser.add_argument(
        "--update-doc",
        action="store_true",
        help="rewrite the module docstring's MEASURED block",
    )
