"""Inheritance-surface ratchet for the ``web`` addon's JavaScript.

``js_public_surface.py`` pins which ``@web/*`` **modules** other addons import.
That is a strictly weaker statement than it looks: it guarantees
``@web/views/form`` keeps existing, not that ``FormController`` keeps having a
``beforeExecuteActionButton``. The method-level contract — what a downstream
addon may override, by ``extends`` or by ``patch()``, and expect the base to
call — is pinned by nothing.

Measured, that contract is large: addons outside ``web`` reach hundreds of
distinct ``Owner.method`` points on classes inside it. Those points are web's
real API. They are declared nowhere.

MEASURED (regenerated by --update-doc; do not hand-edit)
    points=361 sites=1368 single_use=221 owners=98 subclasses=750 patch_sites=29

Every figure quoted below comes from that block, and ``--check-doc`` fails when
they disagree — wired into ``test_js_extension_surface.py``. See
``doc_measured.py``; this file's first draft hardcoded five counts and three of
them were stale within the hour.

**That block is measured over this repository alone** (``REPO_ROOTS``), while the
gate itself scans every checkout present. The two scopes are not
interchangeable: ``_named_roots`` drops an absent checkout silently, and CI
checks this repo out by itself, so a figure taken over the full workspace is one
the build verifying it can never reproduce — green on every developer's machine
and red only in CI, which is where this block had drifted to (492 points pinned
from a workspace against the 361 CI sees). ``--update`` has the opposite
requirement, and states it below: the *pin file* is per-scope and a partial
checkout would erase the absent scopes' provenance.

This was tested rather than argued. Two worktrees at commit ``891d617a711``,
identically configured, differing only by renaming ``beforeExecuteActionButton``
inside ``web`` and leaving all 19 downstream overriders untouched, produce
identical results (a one-time experiment, not a live measurement)::

    pristine   3 failed, 909 passed, 1 skipped, 178 subtests
    renamed    3 failed, 909 passed, 1 skipped, 178 subtests
    tsc        2100 errors == the committed ratchet floor

Nothing moved. Three independent reasons, each sufficient on its own:

* no gate in this directory models class inheritance — ``js_private_access.py``
  comes closest and cannot, because its ``ACCESS`` regex excludes ``super.``
  explicitly and it scans only ``addons/web/static/src``;
* the consuming side is not typechecked — 756 of 763 files in ``addons/web``
  carry ``@ts-check``, against 40 in the other 4956 ``odoo/addons`` JS files and
  10 in ``enterprise``;
* 18 of those 19 overriding classes have no test that names them, and
  ``enterprise`` is never checked out by this repo's CI, so half the breakage is
  outside what that CI can observe at all.

This gate does the thing that has to come first: **pin what the surface is, so
it can only shrink.** Renaming a method downstream overrides becomes a visible
edit to a list rather than a silent break in three repositories.

Contract: per consumer scope, the pinned set and the measured set must be equal.

  * a point overridden but **not pinned for that scope** is new surface — fail;
  * a point pinned for a scope that no longer overrides it is surface given up —
    fail until the list is shrunk, so the win is recorded rather than quietly
    re-spendable.

Entries are unclassified beyond provenance, for the reason
``js_public_surface.py`` gives at length: deciding which points are contract and
which are accident is a design judgement, and a tool that inferred it would be
guessing. The ``single_use`` figure above counts the points reached by exactly
one subclass; that is the worklist for that conversation — not a verdict this
gate is entitled to reach.

Module resolution is derived from the **addon layout**, not from
``tsconfig.json``: every Odoo addon ``X`` publishes ``@X/*`` as
``<root>/addons/X/static/src/*``. ``tsconfig.json``'s ``paths`` map covers a
minority of the aliases actually imported fork-wide, so a resolver trusting it
silently loses every chain through the rest — including
``FsmProjectTaskFormController``, whose base reaches ``FormController`` through
``@project/*``. No count is restated here; ``addon_aliases()`` measures it, and
a figure copied into this paragraph would rot the way this file's first draft
already demonstrated twice.

Limits
------
* **Three ``extends`` forms are understood**: ``extends Base``,
  ``extends descriptor.Property`` (``formView.Controller``) and
  ``extends Mixin(Base)``. A form outside these three terminates the walk, and
  the class is not counted. A direct-subclass-only implementation undercounts
  the surface by roughly a quarter, which is why the walk is transitive;
  ``test_js_extension_surface.py`` pins that it is.
* **A patch target that is not a statically known class is skipped.** Measured
  over the tree: of the patch calls outside ``web``, most target a class in
  another addon (``mail``, ``point_of_sale``) and are correctly none of web's
  business; the rest split into objects rather than classes — ``router``,
  ``browser``, ``cookie``, ``download``, and the service singletons, which have
  no ancestry to attribute a member to — and **patch factories**, where the
  target is a function parameter (``export function patchGraphModel(Model) {
  patch(Model.prototype, …) }``, six of them). Those last are genuinely
  invisible: which class is patched is decided by the caller. They are the one
  shape here that hides a real dependency.
* **Method detection is textual**, keyed to four-space indentation inside a
  class body — the formatter guarantees it for real sources, but a hand-written
  file at another indent is invisible. Comments and regex literals are stripped
  first via the shared parser.
* **Dynamic shapes are invisible**: a class assembled by ``Object.assign`` on a
  prototype, or produced by a factory that is not a simple ``Mixin(Base)`` call,
  creates a real dependency this cannot see.
* **``patch()`` is in scope, merged into the same keys.** ``patch(Target, {…})``
  and ``patch(Target.prototype, {…})`` reach a base's members by a different
  syntax, but depend on exactly the same contract: rename the member in ``web``
  and the patch silently stops applying — with no error, because a patch that
  matches nothing is indistinguishable from one that has not run yet. Both
  mechanisms therefore land on one ``(owner, method)`` key; the pin answers "is
  this member depended on from outside", not "by which syntax". Folding it in
  found 53 points that ``extends`` alone never saw, among them
  ``FormController.onWillLoadRoot``, ``NavBar.systrayItems`` and
  ``WebClient.setup``. ``js_patch_blind_facade.py`` owns a different question
  about ``patch`` (whether a patch reaches through a facade), not this one.
  Patch *targets that are not classes* — a service object, a plain export — are
  skipped: they carry no ancestry to attribute a member to.
* The measurement is therefore a **floor**. Every limit above loses points; none
  invents one.

Usage::

    python tooling/architecture/js_extension_surface.py            # report
    python tooling/architecture/js_extension_surface.py --check    # CI, exit 1
    python tooling/architecture/js_extension_surface.py --update   # rewrite pin
    python tooling/architecture/js_extension_surface.py --json

``--update`` refuses to run unless every consumer checkout is present, for the
same reason ``js_public_surface.py`` does: an update from a partial checkout can
only erase the absent scopes' provenance.
"""

import argparse
import json
import re
import sys
from pathlib import Path

from js_imports import strip_comments  # sys.path set by conftest.py

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import doc_measured
from _repo_root import find_odoo_root

ROOT = find_odoo_root(Path(__file__).resolve(), tool="js_extension_surface")
WEB = ROOT / "addons" / "web"
PINNED = Path(__file__).resolve().parent / "extension_surface_web.txt"

CONSUMER_ROOTS = (
    ("odoo", ROOT),
    ("enterprise", ROOT.parent / "enterprise"),
    ("agromarin", ROOT.parent / "agromarin"),
    ("design-themes", ROOT.parent / "design-themes"),
)

# The scope the MEASURED block is allowed to pin. `_named_roots` drops an absent
# checkout silently, and CI checks this repo out alone, so a figure measured over
# CONSUMER_ROOTS is one the build that verifies it cannot reproduce: it passes on
# every developer's full workspace and fails only in CI. `--update` already
# refuses to run without every checkout present, for the same reason from the
# other side; the docstring needs the opposite guarantee, not the same one.
REPO_ROOTS = CONSUMER_ROOTS[:1]

# Members every OWL component declares; overriding one says nothing about the
# base's behavioural contract.
NOT_CONTRACT = frozenset(
    {"template", "props", "components", "defaultProps", "constructor"}
)

_IMPORT = re.compile(r'import\s*\{([^}]*)\}\s*from\s*["\']([^"\']+)["\']', re.DOTALL)
_REEXPORT = re.compile(r'export\s*\{([^}]*)\}\s*from\s*["\']([^"\']+)["\']', re.DOTALL)
_STAR = re.compile(r'export\s*\*\s*from\s*["\']([^"\']+)["\']')
# `extends Mixin(Base)` | `extends Base.Prop` | `extends Base`
_EXTENDS = (
    r"(?:([A-Za-z_$][\w$]*)\s*\(\s*([A-Za-z_$][\w$]*)"
    r"|([A-Za-z_$][\w$]*)(?:\.([A-Za-z_$][\w$]*))?)"
)
_CLASS = re.compile(
    r"^(?:export\s+)?(?:default\s+)?class\s+([A-Za-z_$][\w$]*)\s*(?:extends\s+"
    + _EXTENDS
    + r")?",
    re.MULTILINE,
)
_METHOD = re.compile(
    r"^\s{4}(?:static\s+)?(?:async\s+)?(?:\*\s*)?(?:get\s+|set\s+)?"
    r"([a-zA-Z_$][\w$]*)\s*[(=]",
    re.MULTILINE,
)
# `export const formView = { Controller: FormController, ... }`
_DESCRIPTOR = re.compile(
    r"(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*=\s*\{(.*?)\n\}", re.DOTALL
)
# `patch(Target, {...})` / `patch(Target.prototype, {...})` — the OTHER way a
# consumer reaches a base's members. Same contract, different mechanism.
_PATCH = re.compile(r"\bpatch\(\s*([A-Za-z_$][\w$]*)(\.prototype)?\s*,")
_PATCH_MEMBER = re.compile(
    r"(?:async\s+)?(?:\*\s*)?(?:get\s+|set\s+)?([A-Za-z_$][\w$]*)"
)
_DESC_PROP = re.compile(
    r"^\s*([A-Za-z_$][\w$]*)\s*:\s*([A-Za-z_$][\w$]*)\s*,?\s*$", re.MULTILINE
)


def _skip(path: Path) -> bool:
    """Vendored trees only.

    Deliberately NOT a blanket ``/lib/`` match: ``static/src/core/lib/`` and
    ``static/src/libs/`` are first-party modules that merely wrap a vendored
    dependency, and ``@web/libs/bootstrap`` is imported by four addons today.
    Nothing under them declares a class yet, so a looser match cost nothing —
    which is exactly how it would have gone unnoticed once one did. Minified
    payloads are dropped by line-length in ``Index``, not by path.
    """
    text = path.as_posix()
    return "/static/lib/" in text or "/node_modules/" in text


def addon_aliases(consumer_roots=CONSUMER_ROOTS) -> dict[str, Path]:
    """``{"web": <addons/web/static/src>, ...}`` over every checkout present.

    Derived from the tree rather than from ``tsconfig.json``, which names 38 of
    the 164 aliases in use — see the module docstring.
    """
    aliases: dict[str, Path] = {}
    for _name, root in _named_roots(consumer_roots):
        for addons in (root / "addons", root):
            if not addons.is_dir():
                continue
            for entry in addons.iterdir():
                src = entry / "static" / "src"
                if src.is_dir():
                    aliases.setdefault(entry.name, src)
    return aliases


def _named_roots(consumer_roots) -> list[tuple[str, Path]]:
    """Normalise to ``(scope, root)`` for the roots present; see the twin in
    ``js_public_surface.py``. Bare paths take their directory name as scope, so
    tests can pass synthetic trees."""
    named = []
    for item in consumer_roots:
        if isinstance(item, tuple):
            name, root = item[0], Path(item[1])
        else:
            root = Path(item)
            name = root.name
        if root.is_dir():
            named.append((name, root))
    return named


def _class_body(src: str, start: int) -> str:
    opening = src.find("{", start)
    if opening < 0:
        return ""
    depth = 0
    for index in range(opening, len(src)):
        if src[index] == "{":
            depth += 1
        elif src[index] == "}":
            depth -= 1
            if depth == 0:
                return src[opening:index]
    return ""


def object_literal_members(src: str, after: int) -> set[str]:
    """Top-level keys of the object literal starting at or after *after*.

    Used for ``patch(Target, { ... })``. Brace-depth tracked from the literal's
    own ``{`` so only depth-1 keys count — a regex on indentation cannot do
    this, because an object literal nested inside a patched method has exactly
    the same shape as the patch body itself.
    """
    opening = src.find("{", after)
    if opening < 0:
        return set()
    members: set[str] = set()
    depth = 0
    buf: list[str] = []
    for index in range(opening, len(src)):
        char = src[index]
        if char == "{":
            depth += 1
            buf = []
            continue
        if char == "}":
            depth -= 1
            buf = []
            if depth == 0:
                break
            continue
        if depth != 1:
            continue
        if char in "\n,;":
            buf = []
        elif char in "(:":
            candidate = "".join(buf).strip().lstrip(",").strip()
            match = _PATCH_MEMBER.fullmatch(candidate)
            if match:
                members.add(match.group(1))
            buf = []
        else:
            buf.append(char)
    return members


def scan_file(source: str) -> dict:
    """Parse one module into the facts the walk needs.

    ``{"imports": {name: spec}, "reexports": {name: (spec, orig)},
       "stars": [spec], "descriptors": {name: {prop: cls}},
       "classes": {name: {"base", "prop", "form", "methods"}},
       "patches": [(target, members)]}``
    """
    src = strip_comments(source)
    record = {
        "imports": {},
        "reexports": {},
        "stars": _STAR.findall(src),
        "descriptors": {},
        "classes": {},
        "patches": [],
    }
    for names, spec in _IMPORT.findall(src):
        for raw in names.split(","):
            name = raw.strip()
            if not name:
                continue
            # `import { A as B }` binds B locally, but the target module
            # exports A. Keying only on B and then looking B up over there
            # resolves nothing — which is how `patch(WebFileViewer.prototype,…)`
            # in enterprise/sign went uncounted: the face exports `FileViewer`.
            parts = [part.strip() for part in name.split(" as ")]
            record["imports"][parts[-1]] = (spec, parts[0])
    for names, spec in _REEXPORT.findall(src):
        for raw in names.split(","):
            name = raw.strip()
            if not name:
                continue
            parts = [part.strip() for part in name.split(" as ")]
            record["reexports"][parts[-1]] = (spec, parts[0])
    for match in _DESCRIPTOR.finditer(src):
        record["descriptors"][match.group(1)] = dict(_DESC_PROP.findall(match.group(2)))
    for match in _CLASS.finditer(src):
        mixin_arg, plain, prop = match.group(3), match.group(4), match.group(5)
        if mixin_arg:
            base, prop, form = mixin_arg, None, "mixin"
        elif plain:
            base, form = plain, "prop" if prop else "plain"
        else:
            base, prop, form = None, None, None
        record["classes"][match.group(1)] = {
            "base": base,
            "prop": prop,
            "form": form,
            "methods": frozenset(_METHOD.findall(_class_body(src, match.end()))),
        }
    for match in _PATCH.finditer(src):
        members = object_literal_members(src, match.end())
        if members:
            record["patches"].append((match.group(1), frozenset(members)))
    return record


class Index:
    """Every parsed module, plus the resolution the inheritance walk needs."""

    def __init__(self, consumer_roots=CONSUMER_ROOTS, web_src=None):
        self.web_src = Path(web_src or WEB / "static" / "src").resolve()
        self.roots = _named_roots(consumer_roots)
        self.aliases = addon_aliases(consumer_roots)
        self.files: dict[Path, dict] = {}
        self.scope_of: dict[Path, str] = {}
        for name, root in self.roots:
            for path in root.rglob("*.js"):
                if _skip(path):
                    continue
                try:
                    source = path.read_text(encoding="utf8")
                except UnicodeDecodeError, OSError:
                    continue
                # Minified vendored payloads carry no readable class structure
                # and cost more to parse than the whole rest of the tree.
                if len(source) / (source.count("\n") + 1) > 300:
                    continue
                resolved = path.resolve()
                self.files[resolved] = scan_file(source)
                self.scope_of.setdefault(resolved, name)
        self._defs: dict[tuple[Path, str], tuple[Path, str] | None] = {}

    def in_web(self, path: Path) -> bool:
        """Whether ``path`` is a ``web`` **source** module — one that can own a
        contract. Scoped to ``static/src``: a base class lives there."""
        return path.is_relative_to(self.web_src)

    def is_web_addon(self, path: Path) -> bool:
        """Whether ``path`` belongs to the ``web`` addon **at all**.

        Wider than :meth:`in_web`, and the difference is load-bearing. A class in
        ``web/static/tests/`` that subclasses ``FormController`` is web testing
        itself, not a downstream consumer — but it is outside ``static/src``, so
        the narrower predicate counted it as surface and let web's own suite
        write entries into the pin. Worse, those entries move whenever anyone
        edits a web test, so the pin drifts on changes that cross no boundary.
        ``js_public_surface.py`` draws the same line at the addon, not the source
        directory, for the same reason.
        """
        return path.is_relative_to(self.web_src.parent.parent)

    def resolve_spec(self, spec: str, origin: Path) -> Path | None:
        if spec.startswith("."):
            base = (origin.parent / spec).resolve()
        else:
            head, _, tail = spec.partition("/")
            alias = self.aliases.get(head.lstrip("@"))
            if alias is None or not tail:
                return None
            base = (alias / tail).resolve()
        for candidate in (base, Path(f"{base}.js"), base / "index.js"):
            if candidate.is_file():
                return candidate.resolve()
        return None

    def find_class(self, path: Path, name: str, depth: int = 0):
        """Resolve ``(module, exported name)`` to the module defining it."""
        if depth > 12:
            return None
        key = (path, name)
        if key in self._defs:
            return self._defs[key]
        self._defs[key] = None  # cycle guard
        record = self.files.get(path)
        if record is None:
            return None
        found = None
        if name in record["classes"]:
            found = (path, name)
        elif name in record["reexports"]:
            spec, original = record["reexports"][name]
            target = self.resolve_spec(spec, path)
            if target:
                found = self.find_class(target, original, depth + 1)
        elif name in record["imports"]:
            spec, original = record["imports"][name]
            target = self.resolve_spec(spec, path)
            if target:
                found = self.find_class(target, original, depth + 1)
        else:
            for spec in record["stars"]:
                target = self.resolve_spec(spec, path)
                if target and (found := self.find_class(target, name, depth + 1)):
                    break
        self._defs[key] = found
        return found

    def find_descriptor(self, path: Path, name: str, depth: int = 0):
        """Resolve a view descriptor (``formView``) to ``(module, {prop: cls})``."""
        if depth > 10:
            return None
        record = self.files.get(path)
        if record is None:
            return None
        if name in record["descriptors"]:
            return (path, record["descriptors"][name])
        spec = original = None
        if name in record["reexports"]:
            spec, original = record["reexports"][name]
        elif name in record["imports"]:
            spec, original = record["imports"][name]
        if spec:
            target = self.resolve_spec(spec, path)
            if target:
                return self.find_descriptor(target, original, depth + 1)
        for star in record["stars"]:
            target = self.resolve_spec(star, path)
            if target and (found := self.find_descriptor(target, name, depth + 1)):
                return found
        return None

    def parent_of(self, path: Path, name: str):
        info = self.files[path]["classes"].get(name)
        if not info or not info["base"]:
            return None
        if info["form"] == "prop":
            descriptor = self.find_descriptor(path, info["base"])
            if not descriptor:
                return None
            home, properties = descriptor
            target = properties.get(info["prop"])
            return self.find_class(home, target) if target else None
        return self.find_class(path, info["base"])

    def chain(self, path: Path, name: str) -> list[tuple[Path, str]]:
        """``[(module, class), ...]`` from this class up to its root."""
        seen: set[tuple[Path, str]] = set()
        walk: list[tuple[Path, str]] = []
        current = (path, name)
        while current and current not in seen:
            seen.add(current)
            walk.append(current)
            if current[1] not in self.files.get(current[0], {}).get("classes", {}):
                break
            current = self.parent_of(*current)
        return walk


def measure_detailed(
    consumer_roots=CONSUMER_ROOTS, web_src=None
) -> dict[str, dict[str, list[int]]]:
    """``{"Owner.method": {scope: [production, test]}}``.

    The one walk everything derives from. A point is attributed to the
    **nearest ``web`` ancestor that defines the method** — the class whose
    contract the override is actually against.
    """
    index = Index(consumer_roots, web_src)
    found: dict[str, dict[str, list[int]]] = {}
    for path, record in index.files.items():
        if index.is_web_addon(path):
            continue
        scope = index.scope_of[path]
        slot = 1 if "/static/tests/" in path.as_posix() else 0
        for name, info in record["classes"].items():
            if not info["base"]:
                continue
            ancestry = [
                (module, cls)
                for module, cls in index.chain(path, name)[1:]
                if index.in_web(module)
            ]
            if not ancestry:
                continue
            for method in info["methods"] - NOT_CONTRACT:
                for module, cls in ancestry:
                    if method in index.files[module]["classes"][cls]["methods"]:
                        found.setdefault(f"{cls}.{method}", {}).setdefault(
                            scope, [0, 0]
                        )[slot] += 1
                        break
        # `patch(Target, {...})` reaches the same members by a different
        # mechanism, and the contract it depends on is identical: rename the
        # member in `web` and the patch silently stops applying. Merged into the
        # same `(owner, method)` key deliberately — the pin answers "is this
        # member depended on from outside", not "by which syntax".
        for target, members in record["patches"]:
            defined = index.find_class(path, target)
            if not defined or not index.in_web(defined[0]):
                continue
            ancestry = [
                (module, cls)
                for module, cls in index.chain(*defined)
                if index.in_web(module)
            ]
            for method in members - NOT_CONTRACT:
                for module, cls in ancestry:
                    if method in index.files[module]["classes"][cls]["methods"]:
                        found.setdefault(f"{cls}.{method}", {}).setdefault(
                            scope, [0, 0]
                        )[slot] += 1
                        break
    return found


def overriders(point: str, consumer_roots=CONSUMER_ROOTS, web_src=None) -> list[tuple]:
    """``[(scope, path, subclass), ...]`` for one ``Owner.method`` point.

    The pin says *how many* scopes reach a point; narrowing one needs *which
    files*, and grepping the method name does not answer that — a bare
    ``_reset(`` matches ``signature_pad`` and ``socket_io``, neither of which is
    a ``SearchModel``. Only the resolved walk knows, and it already ran to build
    the pin. Without this the single-use entries are a number rather than a
    worklist, which is most of what the pin is *for*.
    """
    owner, _, method = point.rpartition(".")
    index = Index(consumer_roots, web_src)
    found = []
    for path, record in index.files.items():
        if index.is_web_addon(path):
            continue
        for name, info in record["classes"].items():
            if not info["base"] or method not in info["methods"]:
                continue
            for module, cls in index.chain(path, name)[1:]:
                if not index.in_web(module):
                    continue
                if method in index.files[module]["classes"][cls]["methods"]:
                    if cls == owner:
                        found.append((index.scope_of[path], path, name))
                    break
    return sorted(found, key=lambda row: (row[0], str(row[1])))


def provenance(detailed) -> dict[str, frozenset[str]]:
    return {point: frozenset(scopes) for point, scopes in detailed.items()}


def load_pinned() -> dict[str, frozenset[str]]:
    """``{point: pinned scopes}``. A tagless line pins every scope."""
    pinned: dict[str, frozenset[str]] = {}
    if not PINNED.is_file():
        return pinned
    for line in PINNED.read_text(encoding="utf8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        point, *tags = line.split()
        pinned[point] = frozenset(tags)
    return pinned


def _scope_order(scope: str) -> tuple[int, str]:
    names = [name for name, _ in CONSUMER_ROOTS]
    return (names.index(scope) if scope in names else len(names), scope)


def write_pinned(measured_provenance: dict[str, frozenset[str]]) -> None:
    header = (
        "# The `Owner.method` points that addons outside `web` reach — by `extends`\n"
        "# or by `patch()`, which depend on the same contract and are merged here:\n"
        "# web's extension surface, as it is rather than as anyone designed it.\n"
        "# Each entry names the consumer checkout(s) reaching it — its provenance —\n"
        "# and the gate judges only the scopes present in the environment.\n"
        "#\n"
        "# Shrink-only, per scope. A point pinned for a scope that no longer\n"
        "# overrides it fails until the entry is shrunk, so giving up surface is\n"
        "# recorded; one overridden from a scope it is not pinned for fails as\n"
        "# new exposure there.\n"
        "#\n"
        "# `js_public_surface.py` pins the MODULES other addons import. This pins\n"
        "# the METHODS they override — a contract the first cannot express, and\n"
        "# which no other gate in this directory models.\n"
        "#\n"
        "# Entries are deliberately unclassified beyond provenance. Many are\n"
        "# reached by exactly one consumer — the worklist for narrowing the\n"
        "# surface, not a judgement this tool may make. No count is restated\n"
        "# here; run the gate, or read its MEASURED block.\n"
        "# Generated by tooling/architecture/js_extension_surface.py --update.\n"
    )
    lines = [
        f"{point}  {' '.join(sorted(scopes, key=_scope_order))}"
        for point, scopes in sorted(measured_provenance.items())
    ]
    PINNED.write_text(header + "\n".join(lines) + "\n", encoding="utf8")


def drift(measured_provenance, pinned, present_scopes):
    """``(new, gone)`` as ``{scope: [point, ...]}``, judged only for the scopes
    present. Mirrors ``js_public_surface.drift``."""
    new: dict[str, list[str]] = {}
    gone: dict[str, list[str]] = {}
    for scope in present_scopes:
        measured_scope = {
            p for p, scopes in measured_provenance.items() if scope in scopes
        }
        pinned_scope = {p for p, tags in pinned.items() if not tags or scope in tags}
        if grown := sorted(measured_scope - pinned_scope):
            new[scope] = grown
        if shrunk := sorted(pinned_scope - measured_scope):
            gone[scope] = shrunk
    return new, gone


def unresolved(points, web_src=None) -> list[str]:
    """Pinned points whose owning class no longer declares the method.

    A rename inside ``web`` orphans its pin; without this the entry would sit
    in the list forever describing a contract that no longer exists. Judged
    against the tree, exactly as ``js_public_surface.unresolved`` is.
    """
    declared: dict[str, set[str]] = {}
    src = Path(web_src or WEB / "static" / "src").resolve()
    for path in src.rglob("*.js"):
        if _skip(path):
            continue
        try:
            source = path.read_text(encoding="utf8")
        except UnicodeDecodeError, OSError:
            continue
        for name, info in scan_file(source)["classes"].items():
            declared.setdefault(name, set()).update(info["methods"])
    missing = []
    for point in points:
        owner, _, method = point.rpartition(".")
        if owner not in declared or method not in declared[owner]:
            missing.append(point)
    return sorted(missing)


def metrics(
    detailed=None, consumer_roots=CONSUMER_ROOTS, web_src=None
) -> dict[str, int]:
    """The figures the docstring's MEASURED block carries.

    ``subclasses`` counts overriding classes, not override sites: one subclass
    overriding four methods is one subclass and four sites.
    """
    if detailed is None:
        detailed = measure_detailed(consumer_roots, web_src)
    totals = {
        point: sum(sum(counts) for counts in scopes.values())
        for point, scopes in detailed.items()
    }
    return {
        "points": len(detailed),
        "sites": sum(totals.values()),
        "single_use": sum(1 for n in totals.values() if n == 1),
        "owners": len({point.rpartition(".")[0] for point in detailed}),
        "subclasses": count_subclasses(consumer_roots, web_src),
        "patch_sites": count_patch_sites(consumer_roots, web_src),
    }


def repo_metrics() -> dict[str, int]:
    """``metrics()`` over this repository alone — what the MEASURED block pins.

    The single entry point for the docstring figures, so the gate and the test
    that checks it cannot disagree about scope.
    """
    return metrics(consumer_roots=REPO_ROOTS)


def count_patch_sites(consumer_roots=CONSUMER_ROOTS, web_src=None) -> int:
    """`patch()` calls outside `web` whose target resolves to a `web` class."""
    index = Index(consumer_roots, web_src)
    total = 0
    for path, record in index.files.items():
        if index.is_web_addon(path):
            continue
        for target, _members in record["patches"]:
            defined = index.find_class(path, target)
            if defined and index.in_web(defined[0]):
                total += 1
    return total


def count_subclasses(consumer_roots=CONSUMER_ROOTS, web_src=None) -> int:
    """Classes outside ``web`` whose ancestry reaches a ``web`` class."""
    index = Index(consumer_roots, web_src)
    total = 0
    for path, record in index.files.items():
        if index.in_web(path):
            continue
        for name, info in record["classes"].items():
            if info["base"] and any(
                index.in_web(module) for module, _ in index.chain(path, name)[1:]
            ):
                total += 1
    return total


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 on drift")
    parser.add_argument("--update", action="store_true", help="rewrite the pin")
    parser.add_argument("--json", action="store_true")
    parser.add_argument(
        "--explain",
        metavar="Owner.method",
        help="list the files overriding one point — the narrowing worklist",
    )
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    if not (WEB / "static" / "src").is_dir():
        parser.error(f"no web addon at {WEB}")

    if args.explain:
        rows = overriders(args.explain)
        if not rows:
            print(f"no subclass overrides {args.explain}")
            return 1
        print(f"{args.explain} — {len(rows)} overrider(s)")
        for scope, path, subclass in rows:
            try:
                shown = path.relative_to(ROOT.parent)
            except ValueError:
                shown = path
            print(f"  [{scope}] {subclass}  {shown}")
        return 0

    present = [name for name, _ in _named_roots(CONSUMER_ROOTS)]
    absent = [name for name, _ in CONSUMER_ROOTS if name not in present]
    if args.update and absent:
        parser.error(
            "--update needs every consumer checkout present; missing: "
            + ", ".join(absent)
        )

    detailed = measure_detailed(CONSUMER_ROOTS)
    if not detailed:
        # A gate that scanned nothing must say so rather than report success.
        parser.error("measured an empty surface — the scan reached nothing")
    measured_provenance = provenance(detailed)

    here = Path(__file__).resolve()
    if args.update_doc:
        changed = doc_measured.update(here, repo_metrics())
        print(f"{'rewrote' if changed else 'already fresh:'} MEASURED block")
        return 0
    if args.check_doc:
        problems = doc_measured.check(here, repo_metrics())
        for problem in problems:
            print(f"[FAIL] {problem}")
        if problems:
            print(
                "\n  python tooling/architecture/js_extension_surface.py --update-doc"
            )
        return 1 if problems else 0

    if args.update:
        write_pinned(measured_provenance)
        print(f"wrote {PINNED.name}: {len(measured_provenance)} point(s)")
        return 0

    pinned = load_pinned()
    new, gone = drift(measured_provenance, pinned, present)
    orphaned = unresolved(pinned)

    totals = {
        point: sum(sum(counts) for counts in scopes.values())
        for point, scopes in detailed.items()
    }
    single_use = sorted(p for p, n in totals.items() if n == 1)

    if args.json:
        print(
            json.dumps(
                {
                    "scopes_present": present,
                    "scopes_absent": absent,
                    "measured": len(detailed),
                    "subclass_sites": sum(totals.values()),
                    "single_use": single_use,
                    "new": new,
                    "gone": gone,
                    "orphaned": orphaned,
                },
                indent=2,
            )
        )
        return 1 if ((new or gone or orphaned) and args.check) else 0

    print("JS extension-surface ratchet (shrink-only, per consumer scope)")
    print("=" * 64)
    print(f"consumer scopes present: {', '.join(present)}")
    if absent:
        print(f"  absent, validated in their own CI: {', '.join(absent)}")
    print(
        f"measured {len(detailed)} override point(s) over {sum(totals.values())} site(s)"
    )
    print(f"  {len(single_use)} reached by exactly one subclass")
    for scope, points in new.items():
        print(f"\n[FAIL] scope '{scope}': {len(points)} NEW override point(s):")
        for point in points[:20]:
            print(f"    {point}  ({totals[point]} subclass(es))")
        if len(points) > 20:
            print(f"    … and {len(points) - 20} more")
    for scope, points in gone.items():
        print(
            f"\n[FAIL] scope '{scope}': {len(points)} pinned point(s) no longer "
            f"overridden from it — shrink the list:"
        )
        for point in points[:20]:
            print(f"    {point}")
        if len(points) > 20:
            print(f"    … and {len(points) - 20} more")
    if orphaned:
        print(
            f"\n[FAIL] {len(orphaned)} pinned point(s) name a method the owning "
            f"class no longer declares:"
        )
        for point in orphaned:
            print(f"    {point}")
        print("    A rename inside web orphaned these. Update the pin with the rename.")
    print("-" * 64)
    if not new and not gone and not orphaned:
        print(f"\nExtension surface unchanged across {len(present)} scope(s). ✓")

    return 1 if ((new or gone or orphaned) and args.check) else 0


if __name__ == "__main__":
    sys.exit(main())
