#!/usr/bin/env python3
"""Gate on what field widgets reach through ``props.record``.

``standardFieldProps`` has four keys and one of them is
``record: { type: Object }`` — a live ``RelationalRecord``, whose own members
before anything inherited are ``own_members`` in the block below. Every field
widget in the fork gets all of them, so the real interface of every field widget
in every checkout was "the record", and no gate could see a change to it:

* ``js_public_surface`` pins imported module specifiers. The record arrives as a
  prop, not an import.
* ``js_extension_surface`` pins ``(class, member)`` points reached by ``extends``
  or ``patch()``. A prop read is neither.
* ``js_private_access`` counts ``_``-prefixed reaches across modules. Every
  member here is public; that is the problem, not the exemption.

WHAT IS CHECKED
---------------

1. **Every member reached is declared** in ``FIELD_RECORD_SURFACE``
   (``@web/fields/field_record_contract``). Hard zero. Widening the interface of
   every field widget in the fork becomes an edit to a list someone reviews.

2. **The measured split stays honest.** The block below records how many
   widgets reach only the narrow own-value surface versus how many name a
   sibling field or reach ``record.model``. That split is the worklist for a
   narrower ``FieldHandle`` prop, and the number that says whether it is worth
   doing.

SCOPE
-----

The scan covers every checkout beside this one, because an ``enterprise`` widget
reaching an undeclared member is as real a finding as a ``web`` one. **The
MEASURED block pins this repository alone**, because ``_named_roots`` drops an
absent checkout silently and CI checks this repo out by itself: a figure taken
over "whatever happened to be on disk" is one the build cannot reproduce, so it
fails there and nowhere else. This block did exactly that — 155 widgets pinned
from a full workspace against the far smaller ``widgets`` below, which is what
CI measures. The report prints both, labelled.

Prose here names block keys and does not restate their values, which is
``doc_measured``'s own rule and was broken twice in this docstring: 83 own
members against a class declaring 81, and 111 against a ``widgets`` of 110. A
figure copied out of the block is a second copy of a number the block exists to
own, and drifts the first time either moves.

MEASURED (regenerated by --update-doc; do not hand-edit)
    own_members=85 widgets=110 narrow=60 detached=42 needs_record=30 undecidable=2 own_value_reads=61 sibling_names=36 prop_named_siblings=6 dynamic_reads=24 unresolved=42

WHY AN AST PASS
---------------

The first measurement of this surface was a grep, and it was wrong in two
directions at once: it swept identifiers named ``record`` that are not
``props.record`` (x2many row variables, kanban card records, callback
parameters), inflating ``record.data`` by about a quarter, and it swept test
fixtures, so ``record.foo``, ``record.int_field`` and ``record.bar`` were
reported as members of ``RelationalRecord``.

``js_field_record.mjs`` resolves the binding instead, and reports what it cannot
attribute as ``unresolved`` rather than guessing. That count is pinned too: a
read the analysis cannot tie to a prop is not evidence of anything, but a *rise*
in how much it cannot tie means the pass is losing its grip on the tree.

USAGE
-----

  python js_field_record_surface.py             # report
  python js_field_record_surface.py --check     # gate
  python js_field_record_surface.py --json
  python js_field_record_surface.py --update-doc
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import _consumer_scopes
import doc_measured
from _repo_root import find_odoo_root

ADR = "0022"

ROOT = find_odoo_root(Path(__file__).resolve(), tool="js_field_record_surface")
WEB_SRC = ROOT / "addons" / "web" / "static" / "src"
CONTRACT = WEB_SRC / "fields" / "field_record_contract.js"
ANALYZER = Path(__file__).resolve().parent / "js_field_record.mjs"

RECORD_CLASS = "RelationalRecord"
RECORD_SOURCE = WEB_SRC / "model" / "relational_model" / "record.js"

CONSUMER_ROOTS = _consumer_scopes.CONSUMER_ROOTS

_ARRAY = r"export const {name} = \[(.*?)\];"


def declared_surface() -> tuple[set[str], set[str]]:
    source = CONTRACT.read_text(encoding="utf8")

    def names(const: str) -> set[str]:
        match = re.search(_ARRAY.format(name=const), source, re.DOTALL)
        if not match:
            raise SystemExit(f"js_field_record_surface: {const} not in {CONTRACT}")
        return set(re.findall(r'"([^"]+)"', match.group(1)))

    return names("FIELD_RECORD_SURFACE"), names("FIELD_OWN_VALUE_SURFACE")


def _named_roots(consumer_roots=CONSUMER_ROOTS) -> list[tuple[str, Path]]:
    return [(n, Path(r)) for n, r in consumer_roots if Path(r).exists()]


def widget_files() -> list[Path]:
    found: list[Path] = []
    for _scope, root in _named_roots():
        for path in root.rglob("*.js"):
            parts = path.parts
            if "node_modules" in parts or "lib" in parts or "tests" in parts:
                continue
            try:
                if "standardFieldProps" in path.read_text(encoding="utf8"):
                    found.append(path)
            except UnicodeDecodeError, OSError:
                continue
    return sorted(found)


def analyse(paths: list[Path]) -> list[dict]:
    if not paths:
        return []
    done = subprocess.run(
        ["node", str(ANALYZER), *[str(p) for p in paths]],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    if done.returncode != 0:
        raise RuntimeError(f"field-record analyzer failed: {done.stderr.strip()}")
    return [json.loads(line) for line in done.stdout.splitlines() if line.strip()]


def _classify(rows: list[dict], narrow: set[str]) -> dict:

    def reaches_another_field(row):
        return row["siblings"] or row.get("propSiblings")

    needs_record = [
        row for row in rows if reaches_another_field(row) or "model" in row["members"]
    ]
    undecidable = [
        row
        for row in rows
        if row not in needs_record and row["dynamic"] and set(row["members"]) <= narrow
    ]
    narrow_only = [
        row
        for row in rows
        if not reaches_another_field(row)
        and not row["dynamic"]
        and set(row["members"]) <= narrow
    ]
    detached = [row for row in rows if not row["members"]]
    return {
        "widgets": len(rows),
        "narrow": len(narrow_only),
        "detached": len(detached),
        "needs_record": len(needs_record),
        "undecidable": len(undecidable),
        "own_value_reads": sum(r["ownValue"] for r in rows),
        "sibling_names": len({s for r in rows for s in r["siblings"]}),
        "prop_named_siblings": len(
            {s for r in rows for s in r.get("propSiblings", [])}
        ),
        "dynamic_reads": sum(r["dynamic"] for r in rows),
        "unresolved": sum(r["unresolved"] for r in rows),
        "needs_record_files": sorted(
            str(Path(r["file"]).relative_to(ROOT.parent)) for r in needs_record
        ),
    }


def _in_this_repo(row: dict) -> bool:
    return Path(row["file"]).resolve().is_relative_to(ROOT)


def record_own_members() -> int:
    (row,) = analyse([RECORD_SOURCE])
    try:
        return len(row["classes"][RECORD_CLASS])
    except KeyError:
        raise LookupError(
            f"{RECORD_CLASS} is no longer declared in "
            f"{RECORD_SOURCE.relative_to(ROOT)} — `props.record`'s type moved, "
            f"and this gate's opening figure is measuring nothing"
        ) from None


def measure() -> dict:
    rows = [r for r in analyse(widget_files()) if r["isWidget"]]
    _full, narrow = declared_surface()
    members = Counter()
    for row in rows:
        members.update(row["members"])

    scanned = _classify(rows, narrow)
    repo = _classify([r for r in rows if _in_this_repo(r)], narrow)
    return {
        "rows": rows,
        "members": members,
        "scanned_metrics": scanned,
        "metrics": {
            "own_members": record_own_members(),
            **{k: v for k, v in repo.items() if k != "needs_record_files"},
        },
        "needs_record_files": scanned["needs_record_files"],
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--update-doc", dest="update_doc", action="store_true")
    args = parser.parse_args(argv)

    full, _narrow = declared_surface()
    state = measure()
    metrics = state["metrics"]
    scanned = state["scanned_metrics"]
    scopes = [name for name, _root in _named_roots()]

    if not scanned["widgets"]:
        print(
            "js_field_record_surface: found no field widget — the tree ships "
            "dozens, so this scan reached nothing",
            file=sys.stderr,
        )
        return 2

    if args.update_doc:
        changed = doc_measured.update(Path(__file__), metrics)
        print(
            f"{'updated' if changed else 'already fresh'}: {doc_measured.render(metrics)}"
        )
        return 0

    undeclared = sorted(set(state["members"]) - full)

    if args.json:
        print(
            json.dumps(
                {
                    "metrics": metrics,
                    "members": dict(state["members"].most_common()),
                    "undeclared": undeclared,
                    "needs_record_files": state["needs_record_files"],
                },
                indent=2,
            )
        )
        return 1 if undeclared and args.check else 0

    print("record members reached by field widgets (widgets reaching each):")
    for name, count in state["members"].most_common():
        mark = "" if name in full else "   UNDECLARED"
        print(f"  {count:>4}  {name}{mark}")
    print(
        f"\nscanned: {', '.join(scopes)} — pinned figures below are odoo alone, "
        f"the only scope CI reproduces"
    )
    print(
        f"{scanned['widgets']} widgets ({metrics['widgets']} in odoo): "
        f"{scanned['narrow']} reach only the narrow own-value surface, "
        f"{scanned['needs_record']} name a sibling field or reach record.model, "
        f"{scanned['undecidable']} read a key this pass cannot decide"
    )
    print(
        f"{scanned['detached']} reach no record member at all — converted to "
        f"fieldHandle, or never needed the record"
    )
    print(
        f"record.data reads: {scanned['own_value_reads']} own-field, "
        f"{scanned['sibling_names']} distinct sibling names, "
        f"{scanned['prop_named_siblings']} named by an option, "
        f"{scanned['dynamic_reads']} dynamic keys "
        f"({scanned['unresolved']} unattributable reads on a bare `record`)"
    )

    for name in undeclared:
        print(f"\nUNDECLARED record member `{name}`")
        print("  -> add it to FIELD_RECORD_SURFACE in fields/field_record_contract.js,")
        print("     or stop reaching it: this widens the interface of every widget")

    problems = doc_measured.check(Path(__file__), metrics)
    for problem in problems:
        print(f"\nMEASURED block stale: {problem}")

    return 1 if (undeclared or problems) and args.check else 0


if __name__ == "__main__":
    sys.exit(main())
