"""Drift-zero gate on the JS mixin compositions in ``web``.

``mixin_coupling_check.py`` makes an argument about Python that is true, word for
word, about this tree's JavaScript::

    ``BaseModel`` is composed from 23 ``__slots__ = ()`` mixins by multiple
    inheritance; they collaborate through ``self``, and a ``self._fields`` or
    ``self._search(...)`` produces **no import edge at all**. So the most
    intricate coupling surface in the framework is invisible to the checker that
    guards everything around it: a mixin can grow a dependency on any other
    mixin, and no gate moves.

``SearchModel`` is composed from five mixin factories by a chain of calls::

    export class SearchModel extends SearchQueryMixin(
        SearchSplitDomainMixin(
            SearchFavoritesMixin(SearchPropertiesMixin(SearchPanelMixin(EventBus))),
        ),
    ) {

and they collaborate through ``this``. The same blindness follows, and it was
measurable: ``js_private_access`` reports its accesses across the whole addon and
**zero** of them in ``search/``, because a mixin merges into its host class and
leaves no cross-module member access to detect. The equivalent decomposition in
``model/relational_model/`` is measured, contract-declared and
conformance-tested. This one was not measured at all.

MEASURED (regenerated by --update-doc; do not hand-edit)
    units=6 edges=12 max_scc=6 cyclic_edges=12 foreign=150 shared_privates=4 dynamic=0

**This gate does not ask for the chain to be dismantled.** ``js_service_shape``
already records the chain as one of four legitimate extension seams in this tree
-- "inherit it / SearchModel mixins / 5-deep chain, patchable with ``super``" --
and downstream addons use it. Dismantling it would delete that seam to improve a
number, which is the trade ``record_contract.js`` refuses by name. What a
composition may not do is get *more* tangled without anyone seeing, which is
what the Python gate ratchets and what this one ratchets too.

WHAT IS MEASURED
----------------

A **unit** is one participating module: a mixin factory, or the module composing
them. For each, the analyzer (``js_mixin_coupling.mjs``, espree -- see its header
for why not a regex) collects

* **defines** -- names bound in the body of a class it declares;
* **uses** -- every ``this.X`` inside such a class, excluding a nested
  non-arrow ``function``, whose ``this`` is a different object.

An edge ``A -> B`` exists when A uses a name B defines. From that graph:

* ``max_scc`` -- the largest strongly-connected component. Cycles are what make
  a decomposition cosmetic; this must never grow.

  It equals ``units``, and ``cyclic_edges`` equals ``edges``. **The composition
  is a single strongly-connected component: every unit reaches every other, and
  not one of the twelve edges is acyclic.** That is the measurement worth having
  and the reason this gate exists -- the Python side reports ``max_scc`` **1**
  for ``BaseModel``'s 23 mixins, having done the splitting that got it there, so
  the two ends of the same technique in the same fork are as far apart as the
  metric goes.

* ``cyclic_edges`` -- edges whose endpoints share a cycle. The volume of
  tangling, as opposed to ``max_scc``'s worst single knot. Distinct from
  ``max_scc`` in general: breaking one back-edge of a 6-cycle leaves ``max_scc``
  at 6 but shows up here immediately, which is what makes incremental progress
  visible before the component finally splits.
* ``foreign`` -- uses a unit does not itself define. The size of the undeclared
  interface: the number that would be a contract file if this were
  ``model/relational_model/``. 88 of the 150 are in the five mixins; the rest are
  ``search_model.js`` reaching into what the mixins define, which is the same
  coupling in the other direction and is counted for that reason.
* ``shared_privates`` -- underscore-prefixed names used by two or more units and
  defined by another. These are the ones that would be counted, and would need
  declaring, if they crossed a module boundary in any other form. ``_notify`` is
  reached by five units.
* ``dynamic`` -- ``this[expr]`` accesses, reported and never counted, matching
  how ``js_private_access`` treats members no module declares.

**The gaming move, and the guard.** Every metric here falls to zero by folding
the mixins back into one class, which changes no coupling whatsoever. So
``units`` is reported alongside them: a merge that "fixes" the graph shrinks it
in the same commit, where a reviewer sees both. As with ``public_members`` in
``js_private_access``, neither number means anything alone.

Exact-mode against ``BASELINE``, like ``mixin_coupling_check.py``: an improvement
that does not lower the baseline fails too, so a cleanup is locked in rather than
re-spent.

    python tooling/architecture/js_mixin_coupling.py            # report
    python tooling/architecture/js_mixin_coupling.py --check    # gate
    python tooling/architecture/js_mixin_coupling.py --json
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import doc_measured
from _repo_root import find_odoo_root

ROOT = find_odoo_root(Path(__file__).resolve(), tool="js_mixin_coupling")
WEB_SRC = ROOT / "addons" / "web" / "static" / "src"
ANALYZER = Path(__file__).with_suffix(".mjs")

#: Compositions this gate knows about, as ``{composing module: [mixin modules]}``.
#:
#: Enumerated rather than discovered. A discovered set would silently change
#: meaning when a mixin is added -- the baseline would move for a reason nobody
#: chose -- and the whole value of an exact ratchet is that every movement was a
#: decision. Adding a composition here is that decision.
COMPOSITIONS = {
    "search/search_model.js": [
        "search/search_query_mixin.js",
        "search/search_split_domain_mixin.js",
        "search/search_favorites_mixin.js",
        "search/search_properties_mixin.js",
        "search/search_panel/search_panel_mixin.js",
    ],
}

BASELINE = {
    "max_scc": 6,
    "cyclic_edges": 12,
    "foreign": 150,
    "shared_privates": 4,
}


@dataclass
class Unit:
    module: str
    defines: set[str] = field(default_factory=set)
    uses: set[str] = field(default_factory=set)
    dynamic: int = 0

    @property
    def foreign(self) -> set[str]:
        return self.uses - self.defines


def modules() -> list[str]:
    out = []
    for base, mixins in COMPOSITIONS.items():
        out.append(base)
        out.extend(mixins)
    return sorted(set(out))


def analyse(mods: list[str]) -> dict[str, Unit]:
    """Run the espree analyzer over ``mods`` and return one Unit each."""
    paths = [WEB_SRC / m for m in mods]
    missing = [p for p in paths if not p.is_file()]
    if missing:
        raise SystemExit(
            "js_mixin_coupling: declared module(s) not on disk -- update "
            "COMPOSITIONS:\n  " + "\n  ".join(str(p) for p in missing)
        )
    proc = subprocess.run(
        ["node", str(ANALYZER), *[str(p) for p in paths]],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,  # returncode inspected below, with the stderr
    )
    if proc.returncode != 0:
        raise RuntimeError(f"mixin analyzer failed: {proc.stderr.strip()}")
    units = {}
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        raw = json.loads(line)
        rel = Path(raw["file"]).resolve().relative_to(WEB_SRC.resolve()).as_posix()
        units[rel] = Unit(
            module=rel,
            defines=set(raw["defines"]),
            uses=set(raw["uses"]),
            dynamic=raw["dynamic"],
        )
    return units


def build_edges(units: dict[str, Unit]) -> set[tuple[str, str]]:
    """``A -> B`` when A uses a name B defines. Self-edges are not edges."""
    edges = set()
    for a in units.values():
        for b in units.values():
            if a.module == b.module:
                continue
            if a.foreign & b.defines:
                edges.add((a.module, b.module))
    return edges


def strongly_connected(
    nodes: list[str], edges: set[tuple[str, str]]
) -> list[list[str]]:
    """Tarjan's SCC, iterative so a deep graph cannot blow the stack."""
    succ: dict[str, list[str]] = {n: [] for n in nodes}
    for a, b in edges:
        succ[a].append(b)
    index: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    result: list[list[str]] = []
    counter = 0

    for root in nodes:
        if root in index:
            continue
        work = [(root, iter(sorted(succ[root])))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on_stack.add(root)
        while work:
            node, children = work[-1]
            advanced = False
            for child in children:
                if child not in index:
                    index[child] = low[child] = counter
                    counter += 1
                    stack.append(child)
                    on_stack.add(child)
                    work.append((child, iter(sorted(succ[child]))))
                    advanced = True
                    break
                if child in on_stack:
                    low[node] = min(low[node], index[child])
            if advanced:
                continue
            work.pop()
            if work:
                parent = work[-1][0]
                low[parent] = min(low[parent], low[node])
            if low[node] == index[node]:
                component = []
                while True:
                    member = stack.pop()
                    on_stack.discard(member)
                    component.append(member)
                    if member == node:
                        break
                result.append(sorted(component))
    return result


def cyclic_edges(
    edges: set[tuple[str, str]], components: list[list[str]]
) -> set[tuple[str, str]]:
    """Edges whose endpoints sit in the same strongly-connected component."""
    owner = {n: i for i, c in enumerate(components) for n in c}
    sizes = {i: len(c) for i, c in enumerate(components)}
    return {
        (a, b)
        for a, b in edges
        if owner.get(a) == owner.get(b) and sizes.get(owner.get(a), 0) > 1
    }


def shared_privates(units: dict[str, Unit]) -> dict[str, list[str]]:
    """Underscored names used by >=2 units and defined by some other unit."""
    defined_by = {
        name: mod
        for mod, u in units.items()
        for name in u.defines
        if name.startswith("_")
    }
    users: dict[str, list[str]] = {}
    for mod, unit in units.items():
        for name in unit.foreign:
            if name in defined_by and defined_by[name] != mod:
                users.setdefault(name, []).append(mod)
    return {n: sorted(m) for n, m in sorted(users.items()) if len(m) >= 2}


def measure() -> dict:
    units = analyse(modules())
    nodes = sorted(units)
    edges = build_edges(units)
    components = strongly_connected(nodes, edges)
    cyc = cyclic_edges(edges, components)
    shared = shared_privates(units)
    return {
        "units": units,
        "nodes": nodes,
        "edges": edges,
        "components": components,
        "cyclic": cyc,
        "shared": shared,
        "metrics": {
            "max_scc": max((len(c) for c in components), default=0),
            "cyclic_edges": len(cyc),
            "foreign": sum(len(u.foreign) for u in units.values()),
            "shared_privates": len(shared),
        },
    }


def doc_metrics(state: dict) -> dict[str, int]:
    m = state["metrics"]
    return {
        "units": len(state["nodes"]),
        "edges": len(state["edges"]),
        "max_scc": m["max_scc"],
        "cyclic_edges": m["cyclic_edges"],
        "foreign": m["foreign"],
        "shared_privates": m["shared_privates"],
        "dynamic": sum(u.dynamic for u in state["units"].values()),
    }


def report(state: dict) -> str:
    units, metrics = state["units"], state["metrics"]
    out = ["JS mixin-coupling graph (drift-zero)", "=" * 72, ""]
    out.append(f"{'unit':<46}{'defines':>9}{'uses':>7}{'foreign':>9}")
    for mod in state["nodes"]:
        u = units[mod]
        out.append(f"  {mod:<44}{len(u.defines):>9}{len(u.uses):>7}{len(u.foreign):>9}")
    out.append("")
    for name, users in state["shared"].items():
        out.append(f"  this.{name} — reached by {len(users)} unit(s)")
    out.append("")
    for key, value in sorted(metrics.items()):
        floor = BASELINE[key]
        mark = "ok" if value == floor else ("DOWN" if value < floor else "UP")
        out.append(f"  [{mark:>4}] {key:<16} {value:>4}   baseline {floor}")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="gate against BASELINE")
    parser.add_argument("--json", action="store_true")
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    if not modules():
        parser.error("COMPOSITIONS is empty — the gate would scan nothing")

    state = measure()

    if args.update_doc or args.check_doc:
        metrics = doc_metrics(state)
        path = Path(__file__)
        if args.update_doc:
            changed = doc_measured.update(path, metrics)
            print(
                f"{'updated' if changed else 'already fresh'}: {doc_measured.render(metrics)}"
            )
            return 0
        problems = doc_measured.check(path, metrics)
        if problems:
            print("module docstring's MEASURED block is stale:")
            for problem in problems:
                print(f"  {problem}")
            return 1
        print(f"[ ok] MEASURED block is fresh: {doc_measured.render(metrics)}")
        return 0

    if args.json:
        print(
            json.dumps(
                {
                    "metrics": state["metrics"],
                    "baseline": BASELINE,
                    "units": {
                        m: {
                            "defines": sorted(u.defines),
                            "uses": sorted(u.uses),
                            "foreign": sorted(u.foreign),
                            "dynamic": u.dynamic,
                        }
                        for m, u in state["units"].items()
                    },
                    "edges": sorted(state["edges"]),
                    "components": state["components"],
                    "shared_privates": state["shared"],
                },
                indent=2,
            )
        )
        return 0

    print(report(state))

    if not args.check:
        return 0

    drift = {
        k: (v, BASELINE[k]) for k, v in state["metrics"].items() if v != BASELINE[k]
    }
    if not drift:
        print("\nNo mixin-coupling drift. ✓")
        return 0
    print("\nMixin-coupling drift:")
    for key, (value, floor) in sorted(drift.items()):
        direction = "grew" if value > floor else "improved"
        print(f"  {key}: {floor} -> {value} ({direction})")
    print(
        "\n  An improvement must be locked in: update BASELINE in this file and\n"
        "  regenerate the MEASURED block (--update-doc) in the same commit."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
