"""Drift-zero gate on the JS mixin compositions in ``web``.

``mixin_coupling_check.py`` makes an argument about Python that is true, almost
word for word, about this tree's JavaScript (the count is dropped from the quote
below on purpose: it was copied as 23, the source has since said 26, and a
restated number is a second copy that drifts)::

    ``BaseModel`` is composed from many ``__slots__ = ()`` mixins by multiple
    inheritance; they collaborate through ``self``, and a ``self._fields`` or
    ``self._search(...)`` produces **no import edge at all**. So the most
    intricate coupling surface in the framework is invisible to the checker that
    guards everything around it: a mixin can grow a dependency on any other
    mixin, and no gate moves.

``SearchModel`` is composed from five mixin factories by a chain of calls::

    export class SearchModel extends SearchQueryMixin(
        SearchSplitDomainMixin(
            SearchFavoritesMixin(SearchPropertiesMixin(SearchPanelMixin(EventBus))),
        ),
    ) {

and they collaborate through ``this``. The same blindness follows, and it was
measurable: ``js_private_access`` reports its accesses across the whole addon and
**zero** of them in ``search/``, because a mixin merges into its host class and
leaves no cross-module member access to detect. The equivalent decomposition in
``model/relational_model/`` is measured, contract-declared and
conformance-tested. This one was not measured at all.

MEASURED (regenerated by --update-doc; do not hand-edit)
    units=10 edges=17 max_scc=4 cyclic_edges=12 foreign=206 shared_privates=4 dynamic=0 covered=6 undeclared=0 unpublished=0 stale=0

**This gate does not ask for the chain to be dismantled.** ``js_service_shape``
already records the chain as one of four legitimate extension seams in this tree
-- "inherit it / SearchModel mixins / 5-deep chain, patchable with ``super``" --
and downstream addons use it. Dismantling it would delete that seam to improve a
number, which is the trade ``record_contract.js`` refuses by name. What a
composition may not do is get *more* tangled without anyone seeing, which is
what the Python gate ratchets and what this one ratchets too.

WHAT IS MEASURED
----------------

A **unit** is one participating module: a mixin factory, or the module composing
them. For each, the analyzer (``js_mixin_coupling.mjs``, espree -- see its header
for why not a regex) collects

* **defines** -- names bound in the body of a class it declares, or in an
  object-literal mixin (``export const fooMixin = {...}``) it exports;
* **uses** -- every ``this.X`` inside such a body, excluding a nested
  non-arrow ``function``, whose ``this`` is a different object. In an object
  literal only ``function``-valued properties are entered: an **arrow**
  property's ``this`` is the module scope, not the prototype it is merged onto.

Both mixin mechanisms in this tree are therefore covered. Object literals were
not, and that was a trap rather than a gap: the three ``list_renderer`` mixins
reported ``classes: [], defines: [], uses: []``, so enumerating them in
``COMPOSITIONS`` would have pinned a vacuous zero over 62 real ``this``
references. Edges and shared privates are computed **per composition** for the
same reason -- two compositions that never meet still both define ``fields``,
``props`` and ``state``, and a flat pass over every pair invents edges between
them out of a shared member name.

An edge ``A -> B`` exists when A uses a name B defines. From that graph:

* ``max_scc`` -- the largest strongly-connected component. Cycles are what make
  a decomposition cosmetic; this must never grow.

  When this gate was written ``cyclic_edges`` equalled ``edges`` -- not one
  edge in either composition was acyclic, and ``SearchModel``'s six units were
  a single strongly-connected component in which every unit reached every
  other, and ``ListRenderer``'s four were a second. Neither is now, and both
  split the same way -- by moving one method to the unit whose state its body
  reaches:

    spawnCustomFilterDialog  query      -> split_domain   max_scc 6 -> 4
    toggleGroup              group_rend -> renderer       list SCC 4 -> 3

  ``cyclic_edges`` went 19 -> 14 -> 12 across the two, and ``split_domain`` and
  ``properties`` left the search component together -- the second for free,
  because only ``split_domain`` reached it.

  That is the measurement worth having and the reason this gate exists: the
  Python side reports ``max_scc`` **1** for ``BaseModel``'s mixins, having done
  the splitting that got it there. One edge was worth two units of ``max_scc``
  here because a single unit was the composition's only way in to two others --
  which a graph says and reading the five files does not.

  The list composition earned its place in that sentence rather than inheriting
  it, and still earns most of it. Its three mixins are merged onto the prototype
  by ``Object.assign``, and the graph shows the merge is not a decomposition:
  ``list_styling`` reaches ``list_sorting``'s ``isNumericColumn`` and
  ``isSortable``, and the renderer reaches back into ``list_styling`` and
  ``list_sorting``. It no longer reaches into ``list_group_rendering``:
  ``toggleGroup`` was a one-line delegation to ``groupOps``, which the renderer
  owns, and ``KanbanRenderer`` had always kept the identical method on the
  renderer itself -- the mixin copy was the list view's own divergence and the
  only name the renderer reached it for. Every helper also
  reads ``this.props`` and ``this.fields``, and ``list_styling`` reads
  ``this._readonlyCache`` -- a private the renderer never declares, created by
  assignment, which is why it does not appear in ``shared_privates``.

* ``cyclic_edges`` -- edges whose endpoints share a cycle. The volume of
  tangling, as opposed to ``max_scc``'s worst single knot. Distinct from
  ``max_scc`` in general: breaking one back-edge of a 6-cycle leaves ``max_scc``
  at 6 but shows up here immediately, which is what makes incremental progress
  visible before the component finally splits.
* ``foreign`` -- uses a unit does not itself define. The size of the undeclared
  interface: the number that would be a contract file if this were
  ``model/relational_model/``. Roughly half sit in the mixins themselves; the
  rest are the composing module reaching into what its mixins define, which is
  the same coupling in the other direction and is counted for that reason. No
  split is restated here -- ``--json`` reports it per unit, and a hand-copied
  share is exactly what the MEASURED block exists to replace.
* ``shared_privates`` -- underscore-prefixed names used by two or more units and
  defined by another. These are the ones that would be counted, and would need
  declaring, if they crossed a module boundary in any other form. ``_notify`` is
  reached by five units.
* ``dynamic`` -- ``this[expr]`` accesses, reported and never counted, matching
  how ``js_private_access`` treats members no module declares.

**The gaming move, and the guard.** Every metric here falls to zero by folding
the mixins back into one class, which changes no coupling whatsoever. So
``units`` is reported alongside them: a merge that "fixes" the graph shrinks it
in the same commit, where a reviewer sees both. As with ``public_members`` in
``js_private_access``, neither number means anything alone.

Exact-mode against ``BASELINE``, like ``mixin_coupling_check.py``: an improvement
that does not lower the baseline fails too, so a cleanup is locked in rather than
re-spent.

    python tooling/architecture/js_mixin_coupling.py            # report
    python tooling/architecture/js_mixin_coupling.py --check    # gate
    python tooling/architecture/js_mixin_coupling.py --json
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import doc_measured
from _repo_root import find_odoo_root

ADR = "0024"

ROOT = find_odoo_root(Path(__file__).resolve(), tool="js_mixin_coupling")
WEB_SRC = ROOT / "addons" / "web" / "static" / "src"
ANALYZER = Path(__file__).with_suffix(".mjs")

COMPOSITIONS = {
    "search/search_model.js": [
        "search/search_query_mixin.js",
        "search/search_split_domain_mixin.js",
        "search/search_favorites_mixin.js",
        "search/search_properties_mixin.js",
        "search/search_panel/search_panel_mixin.js",
    ],
    "views/list/list_renderer.js": [
        "views/list/list_styling.js",
        "views/list/list_group_rendering.js",
        "views/list/list_sorting.js",
    ],
}

BASELINE = {
    "max_scc": 4,
    "cyclic_edges": 12,
    "foreign": 206,
    "shared_privates": 4,
    "undeclared": 0,
    "unpublished": 0,
    "stale": 0,
}

# The composition contract, and the units it covers.
#
# ``model/relational_model/`` declares its cross-module reaches in
# ``*_contract.js`` files and ``js_private_access`` counts what is left over.
# A mixin composition has the same interface and no way to state it, because the
# reach leaves no import edge and no cross-module member access -- so the
# declaration has to be checked against the analyzer instead. That is what these
# three metrics do.
#
# A composition with no entry here is measured but not contract-checked: the
# ``list_renderer`` mixins have no contract file, and failing them for every
# reach would say nothing anyone can act on. Adding a contract is what opts a
# composition in, which is the same shape as ``jsfunclen``'s ``--addon``.
CONTRACT_FILES = {
    "search/search_composition_contract.js": {
        "search/search_model.js": "SEARCH_MODEL",
        "search/search_query_mixin.js": "SEARCH_QUERY",
        "search/search_split_domain_mixin.js": "SEARCH_SPLIT_DOMAIN",
        "search/search_favorites_mixin.js": "SEARCH_FAVORITES",
        "search/search_properties_mixin.js": "SEARCH_PROPERTIES",
        "search/search_panel/search_panel_mixin.js": "SEARCH_PANEL",
    },
}

DECLARATION = "export const {prefix}_{kind} = ["


def _array_literal(source: str, head: str) -> str | None:
    """The text between the brackets of ``head``'s array literal, or None.

    Scans for the matching ``]`` rather than a ``\\n];`` terminator. Prettier
    collapses a one-element declaration onto a single line, so a terminator that
    assumes a multi-line array reads a single-line one as unterminated and
    swallows everything up to the *next* array's close -- silently merging two
    declarations into one and inflating whatever the caller does with them.
    That is a false pass, not a crash, which is why this is a scan.
    """
    start = source.find(head)
    if start < 0:
        return None
    depth, i = 0, start + len(head) - 1
    while i < len(source):
        if source[i] == "[":
            depth += 1
        elif source[i] == "]":
            depth -= 1
            if depth == 0:
                return source[start:i]
        i += 1
    return None


@dataclass
class Unit:
    module: str
    defines: set[str] = field(default_factory=set)
    uses: set[str] = field(default_factory=set)
    dynamic: int = 0

    @property
    def foreign(self) -> set[str]:
        return self.uses - self.defines


def modules() -> list[str]:
    out = []
    for base, mixins in COMPOSITIONS.items():
        out.append(base)
        out.extend(mixins)
    return sorted(set(out))


def analyse(mods: list[str]) -> dict[str, Unit]:
    paths = [WEB_SRC / m for m in mods]
    missing = [p for p in paths if not p.is_file()]
    if missing:
        raise SystemExit(
            "js_mixin_coupling: declared module(s) not on disk -- update "
            "COMPOSITIONS:\n  " + "\n  ".join(str(p) for p in missing)
        )
    proc = subprocess.run(
        ["node", str(ANALYZER), *[str(p) for p in paths]],
        capture_output=True,
        text=True,
        cwd=ROOT,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"mixin analyzer failed: {proc.stderr.strip()}")
    units = {}
    for line in proc.stdout.splitlines():
        if not line.strip():
            continue
        raw = json.loads(line)
        rel = Path(raw["file"]).resolve().relative_to(WEB_SRC.resolve()).as_posix()
        units[rel] = Unit(
            module=rel,
            defines=set(raw["defines"]),
            uses=set(raw["uses"]),
            dynamic=raw["dynamic"],
        )
    return units


def _groups(units: dict[str, Unit], compositions=None) -> list[list[Unit]]:

    compositions = COMPOSITIONS if compositions is None else compositions
    groups, grouped = [], set()
    for base, mixins in compositions.items():
        members = [units[m] for m in (base, *mixins) if m in units]
        if members:
            groups.append(members)
            grouped.update(u.module for u in members)
    if ungrouped := [u for m, u in units.items() if m not in grouped]:
        groups.append(ungrouped)
    return groups


def build_edges(units: dict[str, Unit], compositions=None) -> set[tuple[str, str]]:

    edges = set()
    for group in _groups(units, compositions):
        for a in group:
            for b in group:
                if a.module == b.module:
                    continue
                if a.foreign & b.defines:
                    edges.add((a.module, b.module))
    return edges


def strongly_connected(
    nodes: list[str], edges: set[tuple[str, str]]
) -> list[list[str]]:
    succ: dict[str, list[str]] = {n: [] for n in nodes}
    for a, b in edges:
        succ[a].append(b)
    index: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    result: list[list[str]] = []
    counter = 0

    for root in nodes:
        if root in index:
            continue
        work = [(root, iter(sorted(succ[root])))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on_stack.add(root)
        while work:
            node, children = work[-1]
            advanced = False
            for child in children:
                if child not in index:
                    index[child] = low[child] = counter
                    counter += 1
                    stack.append(child)
                    on_stack.add(child)
                    work.append((child, iter(sorted(succ[child]))))
                    advanced = True
                    break
                if child in on_stack:
                    low[node] = min(low[node], index[child])
            if advanced:
                continue
            work.pop()
            if work:
                parent = work[-1][0]
                low[parent] = min(low[parent], low[node])
            if low[node] == index[node]:
                component = []
                while True:
                    member = stack.pop()
                    on_stack.discard(member)
                    component.append(member)
                    if member == node:
                        break
                result.append(sorted(component))
    return result


def cyclic_edges(
    edges: set[tuple[str, str]], components: list[list[str]]
) -> set[tuple[str, str]]:
    owner = {n: i for i, c in enumerate(components) for n in c}
    sizes = {i: len(c) for i, c in enumerate(components)}
    return {
        (a, b)
        for a, b in edges
        if owner.get(a) == owner.get(b) and sizes.get(owner.get(a), 0) > 1
    }


def shared_privates(units: dict[str, Unit], compositions=None) -> dict[str, list[str]]:

    users: dict[str, list[str]] = {}
    for group in _groups(units, compositions):
        defined_by = {
            name: u.module for u in group for name in u.defines if name.startswith("_")
        }
        in_group: dict[str, list[str]] = {}
        for unit in group:
            for name in unit.foreign:
                if name in defined_by and defined_by[name] != unit.module:
                    in_group.setdefault(name, []).append(unit.module)
        for name, mods in in_group.items():
            if len(mods) >= 2:
                users.setdefault(name, []).extend(mods)
    return {n: sorted(m) for n, m in sorted(users.items())}


def declared_contracts() -> dict[str, dict[str, set[str]]]:
    """Parse the contract files into ``{module: {kind: names}}``.

    Regex rather than a JS parse, for the same reason
    ``js_private_access.declared_contracts`` does it: the declarations are flat
    string arrays on purpose, so that the file stays readable as a document and
    parseable without a toolchain.
    """
    declared: dict[str, dict[str, set[str]]] = {}
    for contract, prefixes in CONTRACT_FILES.items():
        path = WEB_SRC / contract
        if not path.is_file():
            raise SystemExit(f"js_mixin_coupling: contract file not on disk -- {path}")
        source = path.read_text(encoding="utf8")
        for module, prefix in prefixes.items():
            kinds: dict[str, set[str]] = {}
            for kind in ("PUBLISHED", "REQUIRES", "SHARED_STATE"):
                head = DECLARATION.format(prefix=prefix, kind=kind)
                block = _array_literal(source, head)
                if block is None:
                    raise SystemExit(
                        f"js_mixin_coupling: {contract} declares no "
                        f"{prefix}_{kind} -- the contract and CONTRACT_FILES "
                        "disagree"
                    )
                kinds[kind] = set(re.findall(r'"([^"]+)"', block))
            declared[module] = kinds
    return declared


def base_surface() -> set[str]:
    """Names the composition inherits from the class the chain is applied to.

    Allowed for every unit and declared by none: ``EventBus.trigger`` resolves
    on all six without any class body binding it, so counting it as an
    undeclared reach would report a coupling that has an owner and is not ours.
    """
    names: set[str] = set()
    for contract in CONTRACT_FILES:
        source = (WEB_SRC / contract).read_text(encoding="utf8")
        block = _array_literal(
            source, "export const SEARCH_COMPOSITION_BASE_SURFACE = ["
        )
        if block is None:
            continue
        names |= set(re.findall(r'"([^"]+)"', block))
    return names


def contract_audit(units: dict[str, Unit], compositions=None) -> dict[str, dict]:
    """Compare each covered unit's measured reaches against its declaration.

    Three ways a contract and a composition can disagree, kept apart because
    they are different mistakes:

    * ``undeclared`` -- the unit reaches something it never declared. A new
      coupling nobody wrote down; this is the one that must fail the build.
    * ``unpublished`` -- the unit declares it requires an operation that no
      sibling declares it publishes. Either the contract is wrong or the reach
      is into something private by accident.
    * ``stale`` -- the unit declares a reach it no longer makes. Harmless at
      runtime and corrosive on paper: an unpruned contract is how the next
      reader learns to stop trusting it.
    """
    declared = declared_contracts()
    inherited = base_surface()
    published_by: dict[str, set[str]] = {}
    for module, kinds in declared.items():
        published_by[module] = kinds["PUBLISHED"]

    audit: dict[str, dict] = {}
    for group in _groups(units, compositions):
        members = [u for u in group if u.module in declared]
        if not members:
            continue
        offered = set().union(*(published_by[u.module] for u in members))
        for unit in members:
            kinds = declared[unit.module]
            allowed = kinds["REQUIRES"] | kinds["SHARED_STATE"] | inherited
            sibling_defined = set().union(
                *(o.defines for o in group if o.module != unit.module)
            )
            audit[unit.module] = {
                "undeclared": sorted(unit.foreign - allowed),
                "unpublished": sorted(
                    name
                    for name in kinds["REQUIRES"]
                    if name not in offered and name in sibling_defined
                ),
                "stale": sorted(
                    (kinds["REQUIRES"] | kinds["SHARED_STATE"]) - unit.foreign
                ),
            }
    return audit


def measure() -> dict:
    units = analyse(modules())
    nodes = sorted(units)
    edges = build_edges(units)
    components = strongly_connected(nodes, edges)
    cyc = cyclic_edges(edges, components)
    shared = shared_privates(units)
    audit = contract_audit(units)
    return {
        "units": units,
        "nodes": nodes,
        "edges": edges,
        "components": components,
        "cyclic": cyc,
        "shared": shared,
        "audit": audit,
        "metrics": {
            "max_scc": max((len(c) for c in components), default=0),
            "cyclic_edges": len(cyc),
            "foreign": sum(len(u.foreign) for u in units.values()),
            "shared_privates": len(shared),
            "undeclared": sum(len(a["undeclared"]) for a in audit.values()),
            "unpublished": sum(len(a["unpublished"]) for a in audit.values()),
            "stale": sum(len(a["stale"]) for a in audit.values()),
        },
    }


def doc_metrics(state: dict) -> dict[str, int]:
    m = state["metrics"]
    return {
        "units": len(state["nodes"]),
        "edges": len(state["edges"]),
        "max_scc": m["max_scc"],
        "cyclic_edges": m["cyclic_edges"],
        "foreign": m["foreign"],
        "shared_privates": m["shared_privates"],
        "dynamic": sum(u.dynamic for u in state["units"].values()),
        "covered": len(state["audit"]),
        "undeclared": m["undeclared"],
        "unpublished": m["unpublished"],
        "stale": m["stale"],
    }


def report(state: dict) -> str:
    units, metrics = state["units"], state["metrics"]
    out = ["JS mixin-coupling graph (drift-zero)", "=" * 72, ""]
    out.append(f"{'unit':<46}{'defines':>9}{'uses':>7}{'foreign':>9}")
    for mod in state["nodes"]:
        u = units[mod]
        out.append(f"  {mod:<44}{len(u.defines):>9}{len(u.uses):>7}{len(u.foreign):>9}")
    out.append("")
    covered = state["audit"]
    if covered:
        out.append(
            f"  contract: {len(covered)} of {len(state['nodes'])} unit(s) covered"
        )
        out.extend(
            f"    [{kind}] {mod}: {', '.join(entry[kind])}"
            for mod, entry in sorted(covered.items())
            for kind in ("undeclared", "unpublished", "stale")
            if entry[kind]
        )
    out.append("")
    for name, users in state["shared"].items():
        out.append(f"  this.{name} — reached by {len(users)} unit(s)")
    out.append("")
    for key, value in sorted(metrics.items()):
        floor = BASELINE[key]
        mark = "ok" if value == floor else ("DOWN" if value < floor else "UP")
        out.append(f"  [{mark:>4}] {key:<16} {value:>4}   baseline {floor}")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="gate against BASELINE")
    parser.add_argument("--json", action="store_true")
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    if not modules():
        parser.error("COMPOSITIONS is empty — the gate would scan nothing")

    state = measure()

    if args.update_doc or args.check_doc:
        metrics = doc_metrics(state)
        path = Path(__file__)
        if args.update_doc:
            changed = doc_measured.update(path, metrics)
            print(
                f"{'updated' if changed else 'already fresh'}: {doc_measured.render(metrics)}"
            )
            return 0
        problems = doc_measured.check(path, metrics)
        if problems:
            print("module docstring's MEASURED block is stale:")
            for problem in problems:
                print(f"  {problem}")
            return 1
        print(f"[ ok] MEASURED block is fresh: {doc_measured.render(metrics)}")
        return 0

    if args.json:
        print(
            json.dumps(
                {
                    "metrics": state["metrics"],
                    "baseline": BASELINE,
                    "units": {
                        m: {
                            "defines": sorted(u.defines),
                            "uses": sorted(u.uses),
                            "foreign": sorted(u.foreign),
                            "dynamic": u.dynamic,
                        }
                        for m, u in state["units"].items()
                    },
                    "edges": sorted(state["edges"]),
                    "components": state["components"],
                    "shared_privates": state["shared"],
                    "contract_audit": state["audit"],
                },
                indent=2,
            )
        )
        return 0

    print(report(state))

    if not args.check:
        return 0

    drift = {
        k: (v, BASELINE[k]) for k, v in state["metrics"].items() if v != BASELINE[k]
    }
    if not drift:
        print("\nNo mixin-coupling drift. ✓")
        return 0
    print("\nMixin-coupling drift:")
    for key, (value, floor) in sorted(drift.items()):
        direction = "grew" if value > floor else "improved"
        print(f"  {key}: {floor} -> {value} ({direction})")
    print(
        "\n  An improvement must be locked in: update BASELINE in this file and\n"
        "  regenerate the MEASURED block (--update-doc) in the same commit."
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
