"""Gate *which members* the framework calls on addon-owned models.

``env_model_surface_check.py`` ratchets **which models** the core reaches by
string key -- 31 of them, exact-mode. It is deliberately one flat set of model
names, and its own docstring names the next step: "the argument for eventually
promoting their *interfaces* into core (Protocols in ``odoo/``, implementations
in ``base``)". This gate is the measurement that step needs, and the thing that
keeps a promoted interface honest afterwards.

**The gap it closes.** A model name is not a contract; the members called on it
are. The model gate is green for every one of the pairs below, because none of
them adds a *model*. Adding ``env["res.users"]._invent_a_hook()`` to ``orm/``
today passes ``env_model_surface_check``, ``layer_check``, ``env_surface_check``
and ``pool_surface_check``: four gates, all green, on a call to a method that
need not exist.

MEASURED (regenerated by --update-doc; do not hand-edit)
    pairs=69 models=22 with_protocol=1

Every figure quoted below comes from that block, and ``--check-doc`` fails when
they disagree -- wired into ``test_model_member_surface_check.py``. See
``doc_measured.py``.

**What is counted, and what is not.** Members ``BaseModel`` itself provides are
subtracted (:func:`base_model_members`): ``browse``, ``search``, ``sudo``,
``create``, ``with_context`` on ``env["res.users"]`` ask ``base`` for nothing it
did not inherit from the framework. Counting them put 46 further pairs in the
surface and buried the ones that are the real contract -- ``ir.model.data
._load_xmlid``, ``ir.attachment._filestore``, ``res.users._compute_session_token``
-- among them. What remains is the surface an addon must actually implement:
**69 pairs across 22 models**, of which **1 model has a declared interface.**

**And that one Protocol was already behind.** ``http/_protocols.py`` declares
``HttpExtension`` for ``ir.http``, the widest of the 22. Its only enforcement,
``addons/test_http/tests/test_ir_http_contract.py``, checks Protocol ->
implementation: everything *declared* must exist on ``ir.http``, with a
compatible signature. Nothing checked the other direction, so
``http/_serve.py``'s ``registry["ir.http"]._apply_max_upload_size()`` -- called
on every dispatched request -- was reached by core, absent from the Protocol,
and therefore unchecked in both existence and signature. This gate found it on
its first run and it was declared the same day. That is the second rule below:
**every member the core reaches on a model that has a Protocol must be declared
by it.**

Two rules, then:

* the ``(model, member)`` surface is ratcheted exact, like the model set: a new
  pair fails (coupling is acknowledged, not accreted), and a pair that
  disappears fails too (a genuine decoupling is committed rather than quietly
  reintroducible);
* a model listed in :data:`PROTOCOLS` must have **every** reached member
  declared by its Protocol class.

What it does not do is *require* a Protocol. Eight models are reached for three
or more members and have none (the report's ``no Protocol`` column); mandating
one here would be a gate voting on work it cannot do. It makes the width visible
instead, and holds the line wherever the work has been done.

Usage::

  python tooling/architecture/model_member_surface_check.py            # report
  python tooling/architecture/model_member_surface_check.py --check    # CI
  python tooling/architecture/model_member_surface_check.py --json
  python tooling/architecture/model_member_surface_check.py --print-baseline
  python tooling/architecture/model_member_surface_check.py --update-doc
"""

import argparse
import ast
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import doc_measured
from _repo_root import find_odoo_root
from env_model_surface_check import (
    _MODEL_RE,
    ENV_MODEL_ACCESSORS,
    _is_env_expression,
    _is_model_container,
    iter_scope_files,
)

REPO_ROOT = find_odoo_root(Path(__file__).resolve(), tool="model_member_surface_check")

#: ``Environment`` accessors that return a **recordset**, so a member read off
#: one is a member of that model.
#:
#: A strict subset of ``env_model_surface_check.ENV_MODEL_ACCESSORS``, and the
#: difference is load-bearing: that map answers "does this reach a model?", for
#: which ``env.lang`` counts -- it consults ``res.lang``. This one answers "is
#: the next attribute a member of that model?", for which it does not:
#: ``env.lang`` and ``env._lang`` return ``str | None``, so ``env._lang
#: .startswith("_")`` would otherwise be recorded as ``res.lang.startswith``.
#: Derived by subtraction rather than retyped, so a new accessor there is a
#: decision here rather than an omission.
_VALUE_ACCESSORS = frozenset({"lang", "_lang"})
RECORDSET_ACCESSORS: dict[str, str] = {
    name: model
    for name, model in ENV_MODEL_ACCESSORS.items()
    if name not in _VALUE_ACCESSORS
}

#: Where ``BaseModel``'s own members are declared. Everything the composition
#: defines is framework-owned and carries no addon contract, so it is subtracted
#: from the surface below -- see :func:`base_model_members`.
_BASE_MODEL_TREE = "odoo/orm/models"

#: ``BaseModel`` members that no ``def`` in that tree declares: the instance
#: slots, and the class attributes the metaclass and registry assembly install.
#: Without these, ``env["res.users"]._fields`` and ``env["base"].env`` read as
#: addon contract when they are the recordset protocol itself.
_BASE_MODEL_EXTRA_MEMBERS = frozenset(
    {
        "env",
        "pool",
        "_ids",
        "_prefetch_ids",
        "_fields",
        "_name",
        "_table",
        "_inherit",
        "_inherits",
        "_description",
        "_order",
        "_rec_name",
        "_auto",
        "_abstract",
        "_transient",
        "_module",
        "_log_access",
        "_active_name",
        "_parent_name",
        "_parent_store",
        "_custom",
        "_original_module",
        "_inherit_children",
        "_inherits_children",
        "_field_definitions",
        "_table_objects",
        "_table_object_definitions",
        "_sql_constraints",
        "_check_company_auto",
        "_allow_sudo_commands",
        "_depends",
        "_rec_names_search",
        "display_name",
        "id",
    }
)

#: ``model name -> (module path relative to the repo root, Protocol class)``.
#:
#: One entry today, which is the finding rather than the configuration:
#: ``ir.http`` is the only addon-owned model whose interface the framework
#: states. The other 21 are reached by duck typing alone.
PROTOCOLS: dict[str, tuple[str, str]] = {
    "ir.http": ("odoo/http/_protocols.py", "HttpExtension"),
}

#: The acknowledged ``model -> members`` surface, ratcheted exact.
#:
#: Regenerate with ``--print-baseline`` after an intentional change, and say in
#: the commit message which member moved and why -- the same standard the ratchet
#: baselines keep. A new entry here is a new promise the framework makes about a
#: model it does not own.
KNOWN_MEMBER_SURFACE: dict[str, frozenset[str]] = {
    "decimal.precision": frozenset({"precision_get"}),
    "ir.attachment": frozenset({"_content_checksum", "_filestore", "_unsized"}),
    "ir.config_parameter": frozenset({"get_param"}),
    "ir.default": frozenset(
        {
            "_evaluate_condition_with_fallback",
            "_get_field_column_fallbacks",
            "_get_model_defaults",
        }
    ),
    "ir.fields.converter": frozenset({"for_model"}),
    "ir.http": frozenset(
        {
            "_apply_max_upload_size",
            "_auth_method_public",
            "_authenticate",
            "_dispatch",
            "_handle_error",
            "_is_allowed_cookie",
            "_match",
            "_post_dispatch",
            "_post_logout",
            "_pre_dispatch",
            "_redirect",
            "_sanitize_cookies",
            "_serve_fallback",
        }
    ),
    "ir.model": frozenset({"_get", "_instantiate_attrs", "_reflect_models"}),
    "ir.model.access": frozenset({"_make_access_error", "check"}),
    "ir.model.constraint": frozenset({"_reflect_constraint", "_reflect_constraints"}),
    "ir.model.data": frozenset(
        {"_load_xmlid", "_process_end", "_update_xmlids", "_xmlid_to_res_model_res_id"}
    ),
    "ir.model.fields": frozenset(
        {
            "_get",
            "_get_ids",
            "_get_manual_field_data",
            "_instantiate_attrs",
            "_reflect_fields",
            "get_field_help",
            "get_field_selection",
            "get_field_string",
        }
    ),
    "ir.model.fields.selection": frozenset({"_reflect_selections"}),
    "ir.model.inherit": frozenset({"_reflect_inherits"}),
    "ir.model.relation": frozenset({"_reflect_relations"}),
    "ir.module.module": frozenset(
        {"_extract_resource_attachment_translations", "_import_zipfile", "update_list"}
    ),
    "ir.qweb": frozenset({"_pregenerate_assets_bundles"}),
    "ir.rule": frozenset({"_compute_domain", "_make_access_error"}),
    "ir.ui.view": frozenset(
        {"_render_template", "_validate_custom_views", "_validate_module_views"}
    ),
    "res.company": frozenset({"root_id"}),
    "res.device.log": frozenset({"_update_device"}),
    "res.lang": frozenset({"_get_data", "_lang_get", "get_installed"}),
    "res.users": frozenset(
        {
            "_compute_session_token",
            "_has_group",
            "_is_public",
            "authenticate",
            "company_id",
            "company_ids",
            "context_get",
            "has_group",
            "has_groups",
            "lang",
            "tz",
        }
    ),
}


def base_model_members() -> frozenset[str]:
    """Every member ``BaseModel`` itself provides.

    Read from ``orm/models/`` rather than imported, so this gate stays
    stdlib-only like its neighbours -- and measured rather than listed, so a
    method moving between mixins changes nothing here.

    This subtraction is what makes the gate mean something. ``browse``,
    ``search``, ``sudo``, ``create``, ``with_context``, ``invalidate_model`` are
    all ``BaseModel``: calling them on ``env["res.users"]`` asks ``base`` for
    nothing it did not inherit from the framework. Counting them put 46 pairs in
    the surface that no addon implements, and buried the ones that are the real
    contract -- ``res.users._check_uid_passwd``, ``ir.model.data._load_xmlid``,
    ``ir.attachment._filestore`` -- among them.
    """
    root = REPO_ROOT / _BASE_MODEL_TREE
    if not root.is_dir():
        raise SystemExit(
            f"model_member_surface_check: {_BASE_MODEL_TREE} is missing, so "
            f"BaseModel's own members cannot be measured."
        )
    members: set[str] = set()
    for path in sorted(root.rglob("*.py")):
        if "tests" in path.parts or path.name.startswith("test_"):
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for child in node.body:
                    if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
                        members.add(child.name)
                    elif isinstance(child, ast.AnnAssign) and isinstance(
                        target := child.target, ast.Name
                    ):
                        members.add(target.id)
                    elif isinstance(child, ast.Assign):
                        members.update(
                            t.id for t in child.targets if isinstance(t, ast.Name)
                        )
    if not members:
        raise SystemExit(
            f"model_member_surface_check: {_BASE_MODEL_TREE} declared no "
            f"members, so every reach would read as addon contract."
        )
    return frozenset(members) | _BASE_MODEL_EXTRA_MEMBERS


@dataclass(frozen=True)
class MemberReach:
    """One ``env[model].member`` access site."""

    model: str
    member: str
    path: str  # repo-relative
    lineno: int


@dataclass
class Report:
    reaches: list[MemberReach] = field(default_factory=list)
    files_scanned: int = 0
    #: ``(model, member)`` pairs reached now but absent from the baseline.
    added: set[tuple[str, str]] = field(default_factory=set)
    #: pairs in the baseline no longer reached (a decoupling to commit).
    removed: set[tuple[str, str]] = field(default_factory=set)
    #: reached members a declared Protocol does not carry.
    undeclared: set[tuple[str, str]] = field(default_factory=set)

    @property
    def surface(self) -> dict[str, frozenset[str]]:
        by_model: dict[str, set[str]] = {}
        for r in self.reaches:
            by_model.setdefault(r.model, set()).add(r.member)
        return {model: frozenset(members) for model, members in by_model.items()}

    @property
    def pairs(self) -> set[tuple[str, str]]:
        return {(r.model, r.member) for r in self.reaches}

    @property
    def ok(self) -> bool:
        return not self.added and not self.removed and not self.undeclared


class _MemberCollector(ast.NodeVisitor):
    """Collect ``(model, member)`` pairs, by the syntaxes the framework uses.

    Four channels, all of them an attribute access whose *value* resolves to a
    recordset of a known model:

    * ``env["res.users"].browse`` / ``self.env["res.users"].browse`` --
      the subscript spelling, and ``registry[...]``/``pool[...]`` with it, since
      ``Registry.__getitem__`` hands back the model class;
    * ``env.user.browse`` -- through the ``Environment`` accessors that resolve
      to a model without naming it (:data:`ENV_MODEL_ACCESSORS`), the same
      channel ``env_model_surface_check`` had to learn to see;
    * ``env["res.users"].sudo().browse`` -- one call deep, because ``sudo()`` /
      ``with_user()`` / ``with_context()`` return the same model and appear
      between the lookup and the member at a third of the sites;
    * ``Access = env["ir.model.access"]`` ... ``Access.check(...)`` -- a
      **single-assignment module-level binding**, resolved by
      :meth:`_single_assignment_bindings`.

    That fourth channel was added after the first version of this gate was
    audited against its own blind spot: 15 sites in the core bind an
    ``env[...]`` lookup to a local, and one model -- ``ir.model.access``, which
    ``env_model_surface_check`` does list -- was reached **only** that way, so it
    was absent from this gate's surface entirely while looking like a model the
    framework calls nothing on.

    Single-assignment is the soundness condition and it is deliberate: a name
    bound once in a module cannot be something else at the use site, so no
    dataflow analysis is needed. A name assigned twice is skipped rather than
    guessed at.

    Still NOT followed: a binding reassigned in the module, a binding through a
    function parameter, and a model name that arrives as a variable rather than
    a literal. The baseline is therefore a lower bound on the member surface,
    stated here so nobody reads it as a closed set.
    """

    #: Recordset-returning methods that preserve the model, so the member after
    #: them is still a member of that model.
    _TRANSPARENT = frozenset(
        {
            "sudo",
            "with_user",
            "with_company",
            "with_context",
            "with_env",
            "with_prefetch",
        }
    )

    def __init__(self, framework_members: frozenset[str]) -> None:
        self.hits: list[tuple[str, str, int]] = []
        self._framework_members = framework_members
        self._bindings: dict[str, str] = {}

    def bind(self, tree: ast.Module) -> None:
        """Resolve the module's single-assignment recordset locals before visiting."""
        self._bindings = self._single_assignment_bindings(tree)

    @classmethod
    def _single_assignment_bindings(cls, tree: ast.Module) -> dict[str, str]:
        """``{local name: model}`` for names bound **exactly once** in the module.

        Assigned twice anywhere -- including in another function, including from
        something that is not a model lookup -- and the name is dropped rather
        than guessed at. That is what makes this sound without dataflow: a name
        with one binding site cannot be anything else where it is used.
        """
        assigned: dict[str, list[str | None]] = {}
        for node in ast.walk(tree):
            targets: list[ast.expr] = []
            value: ast.expr | None = None
            if isinstance(node, ast.Assign):
                targets, value = list(node.targets), node.value
            elif isinstance(node, ast.AnnAssign) and node.value is not None:
                targets, value = [node.target], node.value
            elif isinstance(node, (ast.For, ast.comprehension)):
                targets = [node.target]
            for target in targets:
                if isinstance(target, ast.Name):
                    model = cls._model_of(value) if value is not None else None
                    assigned.setdefault(target.id, []).append(model)
        return {
            name: models[0]
            for name, models in assigned.items()
            if len(models) == 1 and models[0] is not None
        }

    @staticmethod
    def _model_of(node: ast.expr) -> str | None:
        """The model ``node`` evaluates to, or ``None``."""
        if isinstance(node, ast.Subscript) and _is_model_container(node.value):
            key = node.slice
            if (
                isinstance(key, ast.Constant)
                and isinstance(key.value, str)
                and _MODEL_RE.match(key.value)
            ):
                return key.value
            return None
        if isinstance(node, ast.Attribute) and _is_env_expression(node.value):
            return RECORDSET_ACCESSORS.get(node.attr)
        return None

    def _receiver_model(self, node: ast.expr) -> str | None:
        model = self._model_of(node)
        if model is not None:
            return model
        # env["x"].sudo().member -- step over one model-preserving call.
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr in self._TRANSPARENT
        ):
            return self._model_of(node.func.value)
        if isinstance(node, ast.Name):
            return self._bindings.get(node.id)
        return None

    def visit_Attribute(self, node: ast.Attribute) -> None:
        self.generic_visit(node)
        if node.attr in self._framework_members:
            return
        model = self._receiver_model(node.value)
        if model is not None:
            self.hits.append((model, node.attr, node.lineno))


def declared_members(module_rel: str, class_name: str) -> frozenset[str]:
    """The member names a Protocol class declares, read from its source.

    Parsed rather than imported: this gate is stdlib-only and must run without
    the framework (and without a database), exactly like its neighbours.
    """
    path = REPO_ROOT / module_rel
    if not path.is_file():
        raise SystemExit(
            f"model_member_surface_check: {module_rel} does not exist, so the "
            f"{class_name!r} Protocol cannot be read. Update PROTOCOLS."
        )
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            members = {
                child.name
                for child in node.body
                if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef)
            }
            members |= {
                target.id
                for child in node.body
                if isinstance(child, ast.AnnAssign)
                and isinstance(target := child.target, ast.Name)
            }
            return frozenset(members)
    raise SystemExit(
        f"model_member_surface_check: {module_rel} declares no class "
        f"{class_name!r}. Update PROTOCOLS."
    )


def check(files: list[Path] | None = None) -> Report:
    report = Report()
    framework_members = base_model_members()
    for path in files if files is not None else iter_scope_files():
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (SyntaxError, UnicodeDecodeError) as exc:  # pragma: no cover
            print(f"warning: could not parse {path}: {exc}", file=sys.stderr)
            continue
        report.files_scanned += 1
        collector = _MemberCollector(framework_members)
        collector.bind(tree)
        collector.visit(tree)
        rel = path.relative_to(REPO_ROOT).as_posix()
        for model, member, lineno in collector.hits:
            report.reaches.append(MemberReach(model, member, rel, lineno))

    baseline = {
        (model, member)
        for model, members in KNOWN_MEMBER_SURFACE.items()
        for member in members
    }
    report.added = report.pairs - baseline
    report.removed = baseline - report.pairs

    surface = report.surface
    for model, (module_rel, class_name) in PROTOCOLS.items():
        reached = surface.get(model, frozenset())
        missing = reached - declared_members(module_rel, class_name)
        report.undeclared |= {(model, member) for member in missing}
    return report


def _render(report: Report) -> str:
    surface = report.surface
    total = sum(len(members) for members in surface.values())
    lines = [
        "Framework → addon-model MEMBER surface (what the core calls, not just where)",
        "=" * 76,
        f"files scanned: {report.files_scanned}",
        f"models reached: {len(surface)}    distinct (model, member) pairs: {total}",
        "",
    ]
    for model in sorted(surface, key=lambda m: (-len(surface[m]), m)):
        members = surface[model]
        tag = "" if model in PROTOCOLS else "   ← no Protocol"
        lines.append(f"  {model:28s} {len(members):3d}{tag}")
        lines.append(f"      {', '.join(sorted(members))}")
    if report.added:
        lines += ["", "NEW members reached (not in the acknowledged surface):"]
        for model, member in sorted(report.added):
            site = next(
                (
                    f"{r.path}:{r.lineno}"
                    for r in report.reaches
                    if (r.model, r.member) == (model, member)
                ),
                "?",
            )
            lines.append(f"  + {model}.{member}   {site}")
    if report.removed:
        lines += ["", "Members no longer reached (commit the removal):"]
        lines += [f"  - {model}.{member}" for model, member in sorted(report.removed)]
    if report.undeclared:
        header = (
            "Reached but NOT declared by the model's Protocol "
            "(the contract is behind the code):"
        )
        lines += ["", header]
        for model, member in sorted(report.undeclared):
            module_rel, class_name = PROTOCOLS[model]
            lines.append(
                f"  ! {model}.{member} — add it to {class_name} in {module_rel}"
            )
    lines.append("-" * 76)
    if report.ok:
        lines.append("Framework model-member surface matches the acknowledged set. ✓")
    else:
        lines.append(
            "FAILED: framework model-member surface drifted from the baseline."
        )
    return "\n".join(lines)


def doc_metrics(report: Report) -> dict[str, int]:
    """The figures this module's docstring quotes, derived from one live run.

    Deliberately NOT ``files_scanned``. It was in this block for one run, and
    every session that added a source file to a scanned package -- for any
    reason, touching no model -- made the block stale and this gate's own test
    fail in their working tree. A MEASURED figure has to be about the thing
    measured; the size of the scan is not, and churns on work that cannot
    change the answer.
    """
    surface = report.surface
    return {
        "pairs": sum(len(members) for members in surface.values()),
        "models": len(surface),
        "with_protocol": sum(1 for model in surface if model in PROTOCOLS),
    }


def _print_baseline(report: Report) -> None:
    for model in sorted(report.surface):
        members = sorted(report.surface[model])
        rendered = ", ".join(f'"{m}"' for m in members)
        print(f'    "{model}": frozenset({{{rendered}}}),')


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Gate which members the framework calls on addon-owned models."
    )
    parser.add_argument("--check", action="store_true", help="CI mode: exit 1 on drift")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument(
        "--print-baseline",
        action="store_true",
        help="print the current surface as a Python literal (to update the baseline)",
    )
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    report = check()

    # A gate that finds no inputs must refuse, not report success: an emptied or
    # mis-globbed tree yields zero reaches, which is indistinguishable from a
    # framework that reaches no addon model at all -- and the second has never
    # been true. Pinned by test_every_gate_refuses_an_empty_tree.
    if not report.reaches:
        print(
            "model_member_surface_check: no model-member reaches found at all. "
            "The scan resolved no framework sources (an empty or mis-rooted "
            "tree), because the framework does reach addon models.",
            file=sys.stderr,
        )
        return 1

    if args.check_doc or args.update_doc:
        metrics = doc_metrics(report)
        path = Path(__file__)
        if args.update_doc:
            changed = doc_measured.update(path, metrics)
            print(
                f"{'updated' if changed else 'already fresh'}: "
                f"{doc_measured.render(metrics)}"
            )
            return 0
        problems = doc_measured.check(path, metrics)
        if problems:
            print("module docstring's MEASURED block is stale:")
            for problem in problems:
                print(f"  {problem}")
            print(
                "\n  python tooling/architecture/"
                "model_member_surface_check.py --update-doc"
            )
            return 1
        print(f"[ ok] MEASURED block is fresh: {doc_measured.render(metrics)}")
        return 0

    if args.print_baseline:
        _print_baseline(report)
        return 0
    if args.json:
        print(
            json.dumps(
                {
                    "surface": {
                        model: sorted(members)
                        for model, members in sorted(report.surface.items())
                    },
                    "added": sorted(report.added),
                    "removed": sorted(report.removed),
                    "undeclared": sorted(report.undeclared),
                    "sites": len(report.reaches),
                    "ok": report.ok,
                },
                indent=2,
            )
        )
    else:
        print(_render(report))

    if args.check and not report.ok:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
