"""Gate *which members* the framework calls on addon-owned models.

``env_model_surface_check.py`` ratchets **which models** the core reaches by
string key -- 31 of them, exact-mode. It is deliberately one flat set of model
names, and its own docstring names the next step: "the argument for eventually
promoting their *interfaces* into core (Protocols in ``odoo/``, implementations
in ``base``)". This gate is the measurement that step needs, and the thing that
keeps a promoted interface honest afterwards.

**The gap it closes.** A model name is not a contract; the members called on it
are. The model gate is green for every one of the pairs below, because none of
them adds a *model*. Adding ``env["res.users"]._invent_a_hook()`` to ``orm/``
today passes ``env_model_surface_check``, ``layer_check``, ``env_surface_check``
and ``pool_surface_check``: four gates, all green, on a call to a method that
need not exist.

MEASURED (regenerated by --update-doc; do not hand-edit)
    pairs=69 models=22 with_protocol=13

Every figure quoted below comes from that block, and ``--check-doc`` fails when
they disagree -- wired into ``test_model_member_surface_check.py``. See
``doc_measured.py``.

**What is counted, and what is not.** Members ``BaseModel`` itself provides are
subtracted (:func:`base_model_members`): ``browse``, ``search``, ``sudo``,
``create``, ``with_context`` on ``env["res.users"]`` ask ``base`` for nothing it
did not inherit from the framework. Counting them put 46 further pairs in the
surface and buried the ones that are the real contract -- ``ir.model.data
._load_xmlid``, ``ir.attachment._get_filestore``, ``res.users._compute_session_token``
-- among them. What remains is the surface an addon must actually implement:
**69 pairs across 22 models**, of which **13 models have a declared interface** covering 60 of the pairs.

**The first Protocol was already behind when this gate found it.**
``http/_protocols.py`` declares ``HttpExtension`` for ``ir.http``, the widest of
the 22. Its only enforcement,
``addons/test_http/tests/test_ir_http_contract.py``, checks Protocol ->
implementation: everything *declared* must exist on ``ir.http``, with a
compatible signature. Nothing checked the other direction, so
``http/_serve.py``'s ``registry["ir.http"]._apply_max_upload_size()`` -- called
on every dispatched request -- was reached by core, absent from the Protocol,
and therefore unchecked in both existence and signature. This gate found it on
its first run and it was declared the same day. That is the second rule below:
**every member the core reaches on a model that has a Protocol must be declared
by it.**

Two rules, then:

* the ``(model, member)`` surface is ratcheted exact, like the model set: a new
  pair fails (coupling is acknowledged, not accreted), and a pair that
  disappears fails too (a genuine decoupling is committed rather than quietly
  reintroducible);
* a model listed in :data:`PROTOCOLS` must have **every** reached member
  declared by its Protocol class.

What it does not do is *require* a Protocol. Nine models are reached for a
single member each and have none (the report's ``no Protocol`` column): a
one-method contract is a call site with extra steps, and the surface ratchet
above already pins those names exactly. Mandating one would be a gate voting on
work it cannot do. It makes the width visible instead, and holds the line
wherever the work has been done.

Usage::

  python tooling/architecture/model_member_surface_check.py            # report
  python tooling/architecture/model_member_surface_check.py --check    # CI
  python tooling/architecture/model_member_surface_check.py --json
  python tooling/architecture/model_member_surface_check.py --print-baseline
  python tooling/architecture/model_member_surface_check.py --update-doc
"""

import argparse
import ast
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import doc_measured
from _repo_root import find_odoo_root
from env_model_surface_check import (
    _MODEL_RE,
    ENV_MODEL_ACCESSORS,
    _is_env_expression,
    _is_model_container,
    iter_scope_files,
)

ADR = "0029"

REPO_ROOT = find_odoo_root(Path(__file__).resolve(), tool="model_member_surface_check")

_VALUE_ACCESSORS = frozenset({"lang", "_lang"})
RECORDSET_ACCESSORS: dict[str, str] = {
    name: model
    for name, model in ENV_MODEL_ACCESSORS.items()
    if name not in _VALUE_ACCESSORS
}

_BASE_MODEL_TREE = "odoo/orm/models"

_BASE_MODEL_EXTRA_MEMBERS = frozenset(
    {
        "env",
        "pool",
        "_ids",
        "_prefetch_ids",
        "_fields",
        "_name",
        "_table",
        "_inherit",
        "_inherits",
        "_description",
        "_order",
        "_rec_name",
        "_auto",
        "_abstract",
        "_transient",
        "_module",
        "_log_access",
        "_active_name",
        "_parent_name",
        "_parent_store",
        "_custom",
        "_original_module",
        "_inherit_children",
        "_inherits_children",
        "_field_definitions",
        "_table_objects",
        "_table_object_definitions",
        "_sql_constraints",
        "_check_company_auto",
        "_allow_sudo_commands",
        "_depends",
        "_rec_names_search",
        "display_name",
        "id",
    }
)

PROTOCOLS: dict[str, tuple[str, str]] = {
    "ir.http": ("odoo/http/_protocols.py", "HttpExtension"),
    "ir.attachment": ("odoo/orm/_protocols.py", "IrAttachmentProtocol"),
    "ir.default": ("odoo/orm/_protocols.py", "IrDefaultProtocol"),
    "ir.model": ("odoo/orm/_protocols.py", "IrModelProtocol"),
    "ir.model.access": ("odoo/orm/_protocols.py", "IrModelAccessProtocol"),
    "ir.model.constraint": ("odoo/orm/_protocols.py", "IrModelConstraintProtocol"),
    "ir.model.data": ("odoo/orm/_protocols.py", "IrModelDataProtocol"),
    "ir.model.fields": ("odoo/orm/_protocols.py", "IrModelFieldsProtocol"),
    "ir.module.module": ("odoo/orm/_protocols.py", "IrModuleModuleProtocol"),
    "ir.rule": ("odoo/orm/_protocols.py", "IrRuleProtocol"),
    "ir.ui.view": ("odoo/orm/_protocols.py", "IrUiViewProtocol"),
    "res.lang": ("odoo/orm/_protocols.py", "ResLangProtocol"),
    "res.users": ("odoo/orm/_protocols.py", "ResUsersProtocol"),
}

KNOWN_MEMBER_SURFACE: dict[str, frozenset[str]] = {
    "decimal.precision": frozenset({"get_precision"}),
    "ir.attachment": frozenset(
        {"_get_content_checksum", "_get_filestore", "_without_bin_size"}
    ),
    "ir.config_parameter": frozenset({"get_param"}),
    "ir.default": frozenset(
        {
            "_evaluate_condition_with_fallback",
            "_get_field_column_fallbacks",
            "_get_model_defaults",
        }
    ),
    "ir.fields.converter": frozenset({"_get_converter_record"}),
    "ir.http": frozenset(
        {
            "_apply_max_upload_size",
            "_auth_method_public",
            "_authenticate",
            "_dispatch",
            "_handle_error",
            "_is_allowed_cookie",
            "_match",
            "_post_dispatch",
            "_post_logout",
            "_pre_dispatch",
            "_redirect",
            "_sanitize_cookies",
            "_serve_fallback",
        }
    ),
    "ir.model": frozenset({"_get", "_prepare_class_attrs", "_reflect_models"}),
    "ir.model.access": frozenset({"_prepare_access_error", "check"}),
    "ir.model.constraint": frozenset({"_reflect_constraint", "_reflect_constraints"}),
    "ir.model.data": frozenset(
        {"_load_xmlid", "_process_end", "_update_xmlids", "_xmlid_to_res_model_res_id"}
    ),
    "ir.model.fields": frozenset(
        {
            "_get",
            "_get_ids",
            "_get_manual_field_data",
            "_prepare_field_attrs",
            "_reflect_fields",
            "get_field_help",
            "get_field_selection",
            "get_field_string",
        }
    ),
    "ir.model.fields.selection": frozenset({"_reflect_selections"}),
    "ir.model.inherit": frozenset({"_reflect_inherits"}),
    "ir.model.relation": frozenset({"_reflect_relations"}),
    "ir.module.module": frozenset(
        {"_extract_resource_attachment_translations", "_import_zipfile", "update_list"}
    ),
    "ir.qweb": frozenset({"_pregenerate_assets_bundles"}),
    "ir.rule": frozenset({"_compute_domain", "_prepare_access_error"}),
    "ir.ui.view": frozenset(
        {"_render_template", "_check_custom_views", "_check_module_views"}
    ),
    "res.company": frozenset({"root_id"}),
    "res.device.log": frozenset({"_update_device"}),
    "res.lang": frozenset({"_get_data", "_lang_get", "get_installed"}),
    "res.users": frozenset(
        {
            "_compute_session_token",
            "_has_group",
            "_is_public",
            "authenticate",
            "company_id",
            "company_ids",
            "context_get",
            "has_group",
            "has_groups",
            "lang",
            "tz",
        }
    ),
}


def base_model_members() -> frozenset[str]:

    root = REPO_ROOT / _BASE_MODEL_TREE
    if not root.is_dir():
        raise SystemExit(
            f"model_member_surface_check: {_BASE_MODEL_TREE} is missing, so "
            f"BaseModel's own members cannot be measured."
        )
    members: set[str] = set()
    for path in sorted(root.rglob("*.py")):
        if "tests" in path.parts or path.name.startswith("test_"):
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for child in node.body:
                    if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef):
                        members.add(child.name)
                    elif isinstance(child, ast.AnnAssign) and isinstance(
                        target := child.target, ast.Name
                    ):
                        members.add(target.id)
                    elif isinstance(child, ast.Assign):
                        members.update(
                            t.id for t in child.targets if isinstance(t, ast.Name)
                        )
    if not members:
        raise SystemExit(
            f"model_member_surface_check: {_BASE_MODEL_TREE} declared no "
            f"members, so every reach would read as addon contract."
        )
    return frozenset(members) | _BASE_MODEL_EXTRA_MEMBERS


@dataclass(frozen=True)
class MemberReach:
    model: str
    member: str
    path: str
    lineno: int


@dataclass
class Report:
    reaches: list[MemberReach] = field(default_factory=list)
    files_scanned: int = 0
    added: set[tuple[str, str]] = field(default_factory=set)
    removed: set[tuple[str, str]] = field(default_factory=set)
    undeclared: set[tuple[str, str]] = field(default_factory=set)

    @property
    def surface(self) -> dict[str, frozenset[str]]:
        by_model: dict[str, set[str]] = {}
        for r in self.reaches:
            by_model.setdefault(r.model, set()).add(r.member)
        return {model: frozenset(members) for model, members in by_model.items()}

    @property
    def pairs(self) -> set[tuple[str, str]]:
        return {(r.model, r.member) for r in self.reaches}

    @property
    def ok(self) -> bool:
        return not self.added and not self.removed and not self.undeclared


class _MemberCollector(ast.NodeVisitor):
    _TRANSPARENT = frozenset(
        {
            "sudo",
            "with_user",
            "with_company",
            "with_context",
            "with_env",
            "with_prefetch",
        }
    )

    def __init__(self, framework_members: frozenset[str]) -> None:
        self.hits: list[tuple[str, str, int]] = []
        self._framework_members = framework_members
        self._bindings: dict[str, str] = {}

    def bind(self, tree: ast.Module) -> None:
        self._bindings = self._single_assignment_bindings(tree)

    @classmethod
    def _single_assignment_bindings(cls, tree: ast.Module) -> dict[str, str]:

        assigned: dict[str, list[str | None]] = {}
        for node in ast.walk(tree):
            targets: list[ast.expr] = []
            value: ast.expr | None = None
            if isinstance(node, ast.Assign):
                targets, value = list(node.targets), node.value
            elif isinstance(node, ast.AnnAssign) and node.value is not None:
                targets, value = [node.target], node.value
            elif isinstance(node, (ast.For, ast.comprehension)):
                targets = [node.target]
            for target in targets:
                if isinstance(target, ast.Name):
                    model = cls._model_of(value) if value is not None else None
                    assigned.setdefault(target.id, []).append(model)
        return {
            name: models[0]
            for name, models in assigned.items()
            if len(models) == 1 and models[0] is not None
        }

    @staticmethod
    def _model_of(node: ast.expr) -> str | None:
        if isinstance(node, ast.Subscript) and _is_model_container(node.value):
            key = node.slice
            if (
                isinstance(key, ast.Constant)
                and isinstance(key.value, str)
                and _MODEL_RE.match(key.value)
            ):
                return key.value
            return None
        if isinstance(node, ast.Attribute) and _is_env_expression(node.value):
            return RECORDSET_ACCESSORS.get(node.attr)
        return None

    def _receiver_model(self, node: ast.expr) -> str | None:
        model = self._model_of(node)
        if model is not None:
            return model
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr in self._TRANSPARENT
        ):
            return self._model_of(node.func.value)
        if isinstance(node, ast.Name):
            return self._bindings.get(node.id)
        return None

    def visit_Attribute(self, node: ast.Attribute) -> None:
        self.generic_visit(node)
        if node.attr in self._framework_members:
            return
        model = self._receiver_model(node.value)
        if model is not None:
            self.hits.append((model, node.attr, node.lineno))


def declared_members(module_rel: str, class_name: str) -> frozenset[str]:

    path = REPO_ROOT / module_rel
    if not path.is_file():
        raise SystemExit(
            f"model_member_surface_check: {module_rel} does not exist, so the "
            f"{class_name!r} Protocol cannot be read. Update PROTOCOLS."
        )
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            members = {
                child.name
                for child in node.body
                if isinstance(child, ast.FunctionDef | ast.AsyncFunctionDef)
            }
            members |= {
                target.id
                for child in node.body
                if isinstance(child, ast.AnnAssign)
                and isinstance(target := child.target, ast.Name)
            }
            return frozenset(members)
    raise SystemExit(
        f"model_member_surface_check: {module_rel} declares no class "
        f"{class_name!r}. Update PROTOCOLS."
    )


def check(files: list[Path] | None = None) -> Report:
    report = Report()
    framework_members = base_model_members()
    for path in files if files is not None else iter_scope_files():
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (SyntaxError, UnicodeDecodeError) as exc:  # pragma: no cover
            print(f"warning: could not parse {path}: {exc}", file=sys.stderr)
            continue
        report.files_scanned += 1
        collector = _MemberCollector(framework_members)
        collector.bind(tree)
        collector.visit(tree)
        rel = path.relative_to(REPO_ROOT).as_posix()
        for model, member, lineno in collector.hits:
            report.reaches.append(MemberReach(model, member, rel, lineno))

    baseline = {
        (model, member)
        for model, members in KNOWN_MEMBER_SURFACE.items()
        for member in members
    }
    report.added = report.pairs - baseline
    report.removed = baseline - report.pairs

    surface = report.surface
    for model, (module_rel, class_name) in PROTOCOLS.items():
        reached = surface.get(model, frozenset())
        missing = reached - declared_members(module_rel, class_name)
        report.undeclared |= {(model, member) for member in missing}
    return report


def _render(report: Report) -> str:
    surface = report.surface
    total = sum(len(members) for members in surface.values())
    lines = [
        "Framework → addon-model MEMBER surface (what the core calls, not just where)",
        "=" * 76,
        f"files scanned: {report.files_scanned}",
        f"models reached: {len(surface)}    distinct (model, member) pairs: {total}",
        "",
    ]
    for model in sorted(surface, key=lambda m: (-len(surface[m]), m)):
        members = surface[model]
        tag = "" if model in PROTOCOLS else "   ← no Protocol"
        lines.append(f"  {model:28s} {len(members):3d}{tag}")
        lines.append(f"      {', '.join(sorted(members))}")
    if report.added:
        lines += ["", "NEW members reached (not in the acknowledged surface):"]
        for model, member in sorted(report.added):
            site = next(
                (
                    f"{r.path}:{r.lineno}"
                    for r in report.reaches
                    if (r.model, r.member) == (model, member)
                ),
                "?",
            )
            lines.append(f"  + {model}.{member}   {site}")
    if report.removed:
        lines += ["", "Members no longer reached (commit the removal):"]
        lines += [f"  - {model}.{member}" for model, member in sorted(report.removed)]
    if report.undeclared:
        header = (
            "Reached but NOT declared by the model's Protocol "
            "(the contract is behind the code):"
        )
        lines += ["", header]
        for model, member in sorted(report.undeclared):
            module_rel, class_name = PROTOCOLS[model]
            lines.append(
                f"  ! {model}.{member} — add it to {class_name} in {module_rel}"
            )
    lines.append("-" * 76)
    if report.ok:
        lines.append("Framework model-member surface matches the acknowledged set. ✓")
    else:
        lines.append(
            "FAILED: framework model-member surface drifted from the baseline."
        )
    return "\n".join(lines)


def doc_metrics(report: Report) -> dict[str, int]:

    surface = report.surface
    return {
        "pairs": sum(len(members) for members in surface.values()),
        "models": len(surface),
        "with_protocol": sum(1 for model in surface if model in PROTOCOLS),
    }


def _print_baseline(report: Report) -> None:
    for model in sorted(report.surface):
        members = sorted(report.surface[model])
        rendered = ", ".join(f'"{m}"' for m in members)
        print(f'    "{model}": frozenset({{{rendered}}}),')


def main(argv: list[str] | None = None) -> int:
    # `__doc__`, not a paraphrase of it: the module already explains the rule at
    # length, and a hand-written line meant `--help` showed a summary while the
    # reasoning sat unread three lines above it.
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="CI mode: exit 1 on drift")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    parser.add_argument(
        "--print-baseline",
        action="store_true",
        help="print the current surface as a Python literal (to update the baseline)",
    )
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    report = check()

    if not report.reaches:
        print(
            "model_member_surface_check: no model-member reaches found at all. "
            "The scan resolved no framework sources (an empty or mis-rooted "
            "tree), because the framework does reach addon models.",
            file=sys.stderr,
        )
        return 1

    if args.check_doc or args.update_doc:
        metrics = doc_metrics(report)
        path = Path(__file__)
        if args.update_doc:
            changed = doc_measured.update(path, metrics)
            print(
                f"{'updated' if changed else 'already fresh'}: "
                f"{doc_measured.render(metrics)}"
            )
            return 0
        problems = doc_measured.check(path, metrics)
        if problems:
            print("module docstring's MEASURED block is stale:")
            for problem in problems:
                print(f"  {problem}")
            print(
                "\n  python tooling/architecture/"
                "model_member_surface_check.py --update-doc"
            )
            return 1
        print(f"[ ok] MEASURED block is fresh: {doc_measured.render(metrics)}")
        return 0

    if args.print_baseline:
        _print_baseline(report)
        return 0
    if args.json:
        print(
            json.dumps(
                {
                    "surface": {
                        model: sorted(members)
                        for model, members in sorted(report.surface.items())
                    },
                    "added": sorted(report.added),
                    "removed": sorted(report.removed),
                    "undeclared": sorted(report.undeclared),
                    "sites": len(report.reaches),
                    "ok": report.ok,
                },
                indent=2,
            )
        )
    else:
        print(_render(report))

    if args.check and not report.ok:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
