"""A view controller's template is an extension surface, and this pins who inherits it.

Converting `calendar` onto `ViewLayout` was tried and reverted (e075e8cfdf0):
eleven templates across two repositories `t-inherit` a controller template of
`web` -- `web.ListView`, `web.KanbanView`, `web.CalendarController` -- and
xpath `//Layout` inside it, which the chassis renames. Nothing had counted
that. `js_extension_surface` pins the methods subclasses override,
`js_public_surface` the specifiers they import, `js_private_access` the
members they reach; all three read JavaScript, and this surface is QWeb.

So: every `t-inherit` whose target is a template declared under
`addons/web/static/src/views/` is a row of the pin, keyed by the inheriting
file, and the pin is shrink-only. A new inheritor is a decision written down
in the pin with the scope it came from, not a line that lands in silence and
blocks a conversion months later.

Templates under `views/` only: the search panel, fields and widgets have
their own faces and their own inheritors, and a pin of everything is a pin of
nothing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from js_layer_check import ROOT

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _repo_root import SIBLING_REPOS

WEB_VIEWS = ROOT / "addons" / "web" / "static" / "src" / "views"
SCAN_ROOTS = (
    ("odoo", ROOT / "addons"),
    ("odoo", ROOT / "odoo" / "addons"),
    *((name, ROOT.parent / name) for name in SIBLING_REPOS),
)
PINNED = Path(__file__).resolve().parent / "qweb_inherit_surface_web.txt"

T_NAME = re.compile(r"""\bt-name\s*=\s*["']([^"']+)["']""")
T_INHERIT = re.compile(r"""\bt-inherit\s*=\s*["']([^"']+)["']""")


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def owned_templates(web_views: Path = WEB_VIEWS) -> set[str]:
    """Every `t-name` declared by a template file under web's views tree."""
    names: set[str] = set()
    for xml in web_views.rglob("*.xml"):
        if "/static/tests/" in str(xml):
            continue
        names.update(T_NAME.findall(_read(xml)))
    return names


def inheritors(
    scan_roots=SCAN_ROOTS, owned: set[str] | None = None
) -> dict[tuple[str, str], str]:
    """{(target template, inheriting file): scope} for every t-inherit of an owned template.

    The inheriting file is spelled relative to its scan root, so the same
    row reads the same from any checkout.
    """
    owned = owned_templates() if owned is None else owned
    found: dict[tuple[str, str], str] = {}
    for scope, root in scan_roots:
        if not root.is_dir():
            continue
        for xml in root.rglob("*.xml"):
            text = str(xml)
            if "node_modules" in text or "/static/tests/" in text:
                continue
            if xml.is_relative_to(WEB_VIEWS):
                continue
            src = _read(xml)
            for target in T_INHERIT.findall(src):
                if target in owned:
                    found[(target, xml.relative_to(root).as_posix())] = scope
    return found


def load_pinned(path: Path = PINNED) -> dict[tuple[str, str], str]:
    pinned: dict[tuple[str, str], str] = {}
    if not path.is_file():
        return pinned
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        target, inheritor, scope = line.split()
        pinned[(target, inheritor)] = scope
    return pinned


def write_pinned(rows: dict[tuple[str, str], str], path: Path = PINNED) -> None:
    header = (
        "# Generated by tooling/architecture/qweb_inherit_surface.py --update.\n"
        "# Shrink-only. Row: <web template>  <inheriting file>  <scope>.\n"
        "# Every row is a template of web/views another file t-inherits, and\n"
        "# therefore markup a chassis change has to keep or migrate.\n"
    )
    lines = [
        f"{target}  {inheritor}  {scope}"
        for (target, inheritor), scope in sorted(rows.items())
    ]
    path.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 on drift")
    parser.add_argument("--update", action="store_true", help="rewrite the pin")
    args = parser.parse_args(argv)

    owned = owned_templates()
    if not owned:
        print("error: no template under web/views; refusing to report", file=sys.stderr)
        return 2
    measured = inheritors(owned=owned)

    if args.update:
        write_pinned(measured)
        print(f"wrote {PINNED.name}: {len(measured)} inheritor(s)")
        return 0

    by_target: dict[str, int] = {}
    for target, _ in measured:
        by_target[target] = by_target.get(target, 0) + 1
    print(f"templates of web/views inherited elsewhere: {len(by_target)}")
    for target, n in sorted(by_target.items(), key=lambda kv: (-kv[1], kv[0])):
        print(f"  {n:3d}  {target}")

    if not args.check:
        return 0

    pinned = load_pinned()
    new = sorted(set(measured) - set(pinned))
    gone = sorted(set(pinned) - set(measured))
    failures = []
    if new:
        failures.append(
            "NEW t-inherit of a web/views template, not pinned -- a controller "
            "template is an extension surface; add the row with --update only "
            "once the inheritance is a decision:\n    "
            + "\n    ".join(f"{t}  <-  {f}" for t, f in new)
        )
    if gone:
        failures.append(
            "pinned inheritor no longer exists -- shrink the pin with --update:\n    "
            + "\n    ".join(f"{t}  <-  {f}" for t, f in gone)
        )
    for f in failures:
        print(f"[FAIL] {f}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
