"""Self-test for doc_measured.py — the helper that stops a gate's own docstring
from drifting away from the numbers it quotes.

A checker whose failure mode is silence needs its silence tested, which is the
standing rule in this directory (``test_every_gate_refuses_an_empty_tree.py``).
Here the equivalents are: a module with no block must raise rather than compare
equal to nothing, and a block with no parseable pair must do the same.
"""

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

import doc_measured

MODULE = '''"""A gate.

Some prose citing the MEASURED block below.

MEASURED (regenerated by --update-doc; do not hand-edit)
    total=10 files=2

More prose after the block.
"""

X = 1
'''


class DocMeasuredTests(unittest.TestCase):
    def setUp(self):
        self.tmp = TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.path = Path(self.tmp.name) / "gate.py"
        self.path.write_text(MODULE, encoding="utf-8")

    def test_extract_reads_the_block(self):
        self.assertEqual(doc_measured.extract(MODULE), {"total": 10, "files": 2})

    def test_fresh_block_reports_no_problems(self):
        self.assertEqual(doc_measured.check(self.path, {"total": 10, "files": 2}), [])

    def test_changed_value_is_reported(self):
        problems = doc_measured.check(self.path, {"total": 11, "files": 2})
        self.assertEqual(len(problems), 1)
        self.assertIn("docstring says 10, measured 11", problems[0])

    def test_metric_missing_from_the_docstring_is_drift(self):
        # Adding a metric to the gate without adding it to the block would
        # otherwise pass: the block would describe less than the gate measures,
        # which is how a docstring becomes true-but-incomplete.
        problems = doc_measured.check(self.path, {"total": 10, "files": 2, "new": 3})
        self.assertEqual(len(problems), 1)
        self.assertIn("new: missing from the docstring", problems[0])

    def test_metric_no_longer_measured_is_drift(self):
        problems = doc_measured.check(self.path, {"total": 10})
        self.assertEqual(len(problems), 1)
        self.assertIn("files: in the docstring (2), no longer measured", problems[0])

    def test_update_rewrites_only_the_values_line(self):
        changed = doc_measured.update(self.path, {"total": 11, "files": 3})
        self.assertTrue(changed)
        text = self.path.read_text(encoding="utf-8")
        self.assertIn("    total=11 files=3", text)
        # The surrounding docstring is untouched — a rewrite that ate the
        # paragraph after the block would be the obvious way for this to go
        # wrong, and it would go unnoticed until someone read the file.
        self.assertIn("Some prose citing the MEASURED block below.", text)
        self.assertIn("More prose after the block.", text)
        self.assertIn("X = 1", text)

    def test_update_is_idempotent(self):
        self.assertFalse(doc_measured.update(self.path, {"total": 10, "files": 2}))

    def test_missing_block_raises_rather_than_passing(self):
        path = Path(self.tmp.name) / "no_block.py"
        path.write_text('"""A gate with no block."""\n', encoding="utf-8")
        with self.assertRaises(doc_measured.DocMeasuredError):
            doc_measured.check(path, {"total": 1})
        with self.assertRaises(doc_measured.DocMeasuredError):
            doc_measured.update(path, {"total": 1})

    def test_block_with_no_pairs_raises(self):
        path = Path(self.tmp.name) / "empty_block.py"
        path.write_text(
            f'"""A gate.\n\n{doc_measured.MARKER}\n    nothing here\n"""\n',
            encoding="utf-8",
        )
        with self.assertRaises(doc_measured.DocMeasuredError):
            doc_measured.extract(path.read_text(encoding="utf-8"))

    def test_negative_values_survive_a_round_trip(self):
        # A drift metric can legitimately be negative; parsing it as 0 (or
        # failing to match) would silently exempt exactly the interesting case.
        doc_measured.update(self.path, {"total": -3, "files": 2})
        self.assertEqual(
            doc_measured.extract(self.path.read_text(encoding="utf-8")),
            {"total": -3, "files": 2},
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
