#!/usr/bin/env python3
"""Every translatable string must still exist in its module's catalogue.

`_("…")` does not translate a string. It looks one up, by exact source text,
in the `.pot`/`.po` catalogue exported for that module. Edit the literal —
reflow it, fix a typo, reword it — and the lookup misses silently: the call
still returns, the string still renders, and it renders in English for every
reader who asked for something else. Nothing fails. Nothing logs.

This is not hypothetical and it is not small. `mail_alias.py`'s two bounce
bodies were the case that found it. Both are built by
`_alias_with_author_lang`, whose entire purpose is to speak the *sender's*
language, and both went out like this to a Spanish sender:

    Estimado/a remitente, The message below could not be accepted by the
    address …. Only direcciones vinculadas a contactos registrados …
    ^^^ Spanish            ^^^ English                    ^^^ Spanish

`es.po` held a perfectly good translation of that sentence. It was unreachable:
the catalogue carried the pre-fork wording, wrapped across lines with the
source's own indentation baked into the msgid, and the fork had reflowed the
literal onto one line. The test guarding that behaviour asserted only that the
*wrapper* ("Dear Sender") was translated, so it passed throughout.

The exposure is the whole tree, and it tracks how much a module has been
rewritten — which in this fork is the point of the fork. See the MEASURED block
below for the current figures; when this landed, `base_automation` could not
resolve 82% of its strings and `gamification` 66%.

WHAT THIS GATE IS NOT. It does not check that a translation *exists* — an
untranslated string is a job for a translator, not for CI. It checks that the
string a running server will look up is a string the catalogue was exported
for. A missing msgid is a defect in the checkout, repairable with one command::

    odoo-bin i18n export -c <conf> -d <db> mail      # rewrites mail/i18n/mail.pot

WHAT A REWORDING COSTS (`--cost`). The count says a string is unresolved; it does
not say whether that is free. A genuinely new string costs nothing to export and
books nothing. A *reworded* one displaces a msgid the catalogue may already have
translated — and `_()` looks up by exact text, so every one of those translations
is stranded the moment it lands, silently. `--cost` asks, per string, whether the
catalogue carries a near-identical msgid and how many of the shipped `.po` files
translate it:

    addons/mail/models/mixin_mail_render.py:957  'Template rendering supports only …'
        looks like a rewording of 'Template rendering supports only inline_te…' (0.73)
        strands 27 translation(s), of 63 catalogues: ar cs de es es_419 fa fi fr …
    addons/mail/models/mixin_mail_render.py:969  'Cannot render %(template_label)s: …'
        new: nothing near it in the catalogue, costs nothing

Both of those were live and uncommitted when this landed. The point is not that
rewording is wrong — the first is a real improvement, since it stops the engine
list drifting from the code — but that 27 is a price, and it should be chosen
rather than discovered months later by a reader who gets English. A suspicion,
never a verdict: `difflib` above `REWORD_RATIO`, reported for a person to judge.

It reads `.po` files, so it is opt-in and off the `--count` path the ratchet uses.

RED BECAUSE OF A STRING YOU JUST WROTE? EXPORT; DO NOT MOVE THE FLOOR. Moving it
books your new string as permanent debt, and the export removes it instead —
measured on `mail` on 2026-08-19, a re-export took its 69 unresolved strings to
**0** and the tree-wide count down by the same 69. The floor is for debt you are
*accepting*: a module you are not re-exporting today, or a count that moved under
you. That distinction is the whole cadence, and getting it backwards is how a
count ratchet turns into a ledger of things nobody ever fixes.

SCOPE. Every module under `addons/` and `odoo/addons/` that ships
`i18n/<module>.pot`. A module with no `.pot` has no catalogue to disagree with
and is skipped rather than counted — this gate measures drift, not coverage.
Tests are excluded: `_()` in a test is scaffolding, and Odoo's own extractor
does not ship those msgids either.

WHAT IS COUNTED. The first argument of `_(…)` / `_lt(…)`, called bare or on an
environment (`self.env._(…)`), when it is a string constant. An f-string or a
variable cannot be extracted by any exporter, so it is out of scope here too;
`test_lint` owns that rule.

Moving the `translations` floor? Run `--update-doc` in the same commit: the block
below is the second place this number lives, and `test_the_docstring_measurement_is_fresh`
is what stops it drifting quietly.

MEASURED (regenerated by --update-doc; do not hand-edit)
    modules=553 strings=8429 unresolved=509

Usage::

  python tooling/architecture/translation_catalog.py            # report
  python tooling/architecture/translation_catalog.py --count    # for the ratchet
  python tooling/architecture/translation_catalog.py --json
  python tooling/architecture/translation_catalog.py --module mail
  python tooling/architecture/translation_catalog.py --module mail --cost
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import difflib
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import doc_measured
from _repo_root import find_odoo_root

ADR = "unrecorded"

ROOT = find_odoo_root(Path(__file__).resolve(), tool="translation_catalog")

#: Both addon trees, in the order `addons_path` resolves them. A module name is
#: unique across the two, so the mapping stays flat.
ADDON_ROOTS = (ROOT / "odoo" / "addons", ROOT / "addons")

#: The names a gettext call goes by. `_lt` defers the lookup; the msgid it will
#: eventually ask for is the same one.
GETTEXT_NAMES = frozenset({"_", "_lt"})


@dataclass(frozen=True)
class Cost:
    """What a rewording would strand: the msgid it displaces, and its translations."""

    previous: str
    ratio: float
    translated: int
    catalogues: int
    languages: list[str]


@dataclass(frozen=True)
class Unresolved:
    module: str
    file: str
    line: int
    source: str

    def __str__(self) -> str:
        text = self.source if len(self.source) <= 72 else self.source[:69] + "..."
        return f"  {self.file}:{self.line}  {text!r}"


def _display(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _is_test_path(path: Path) -> bool:
    return "tests" in path.parts or path.name.startswith("test_")


def iter_modules(roots: tuple[Path, ...] = ADDON_ROOTS) -> list[tuple[str, Path, Path]]:
    """``(module, module_dir, pot_path)`` for every module shipping a catalogue."""
    found = []
    for root in roots:
        if not root.is_dir():
            continue
        for module_dir in sorted(p for p in root.iterdir() if p.is_dir()):
            pot = module_dir / "i18n" / f"{module_dir.name}.pot"
            if pot.is_file():
                found.append((module_dir.name, module_dir, pot))
    return found


def read_msgids(pot: Path) -> set[str]:
    """Every msgid in a PO/POT file, un-escaped and re-joined.

    Written out rather than taken from `babel`, which the gates may not have:
    they run under `pytest tooling/` with no Odoo and no addon requirements.
    A msgid spans one line or many, continuation lines are concatenated with no
    separator, and each is a Python string literal — so `ast.literal_eval` on
    the joined chunks is both the shortest and the most faithful reading.
    """
    msgids: set[str] = set()
    chunks: list[str] = []
    collecting = False

    def flush() -> None:
        if not chunks:
            return
        # A malformed entry is the exporter's problem, not this gate's.
        with contextlib.suppress(SyntaxError, ValueError):
            msgids.add(ast.literal_eval(" ".join(chunks)))
        chunks.clear()

    for raw in pot.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("msgid "):
            flush()
            chunks.append(line[len("msgid ") :])
            collecting = True
        elif collecting and line.startswith('"'):
            chunks.append(line)
        else:
            flush()
            collecting = False
    flush()
    return msgids


def read_translations(po: Path) -> dict[str, str]:
    """``msgid -> msgstr`` for one catalogue, continuation lines joined.

    Separate from :func:`read_msgids` because the cost lookup needs the *pairs*: a
    msgid nobody looks up is free to drop, and one translated into 27 languages is
    not, and only the msgstr tells them apart.
    """
    pairs: dict[str, str] = {}
    key: str | None = None
    chunks: list[str] = []
    mode: str | None = None

    def flush() -> None:
        nonlocal key, chunks, mode
        if mode == "id" and chunks:
            try:
                key = ast.literal_eval(" ".join(chunks))
            except SyntaxError, ValueError:
                key = None
        elif mode == "str" and chunks and key is not None:
            with contextlib.suppress(SyntaxError, ValueError):
                pairs[key] = ast.literal_eval(" ".join(chunks))
            key = None
        chunks = []

    for raw in po.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line.startswith("msgid "):
            flush()
            mode, chunks = "id", [line[len("msgid ") :]]
        elif line.startswith("msgstr "):
            flush()
            mode, chunks = "str", [line[len("msgstr ") :]]
        elif line.startswith('"') and mode:
            chunks.append(line)
        else:
            flush()
            mode = None
    flush()
    return pairs


#: How alike two strings must be before one is called a rewording of the other.
#: Deliberately reported as a suspicion, never as a fact -- the reader decides.
REWORD_RATIO = 0.6


def reword_cost(source: str, module_dir: Path, msgids: set[str]) -> Cost | None:
    """What rewording *into* ``source`` would strand, if it is a rewording at all.

    The question a floor move cannot answer. A string with no near neighbour in the
    catalogue is new: exporting it costs nothing and books nothing. A string that is a
    reworded twin of a msgid translated into 27 languages strands all 27 the moment it
    lands, silently, because `_()` looks up by exact text. That is a real price and it
    is sometimes worth paying -- but it should be chosen, not discovered months later.

    Note what this does **not** assume: a msgid absent from the Python sources is not
    thereby an orphan. Most of a `.pot` comes from XML, view arch and field labels.
    The question asked here is only "does the catalogue already carry something
    near-identical, and is it translated".
    """
    near = difflib.get_close_matches(source, msgids, n=1, cutoff=REWORD_RATIO)
    if not near:
        return None
    previous = near[0]
    catalogues = sorted((module_dir / "i18n").glob("*.po"))
    translated = [
        po.stem
        for po in catalogues
        if (read_translations(po).get(previous) or "").strip()
    ]
    return Cost(
        previous=previous,
        ratio=difflib.SequenceMatcher(None, source, previous).ratio(),
        translated=len(translated),
        catalogues=len(catalogues),
        languages=translated,
    )


def iter_gettext_literals(path: Path) -> list[tuple[int, str]]:
    """``(lineno, source_text)`` for every extractable gettext call in a file."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError, UnicodeDecodeError:
        return []
    found = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call) or not node.args:
            continue
        func = node.func
        name = (
            func.id
            if isinstance(func, ast.Name)
            else func.attr
            if isinstance(func, ast.Attribute)
            else None
        )
        if name not in GETTEXT_NAMES:
            continue
        first = node.args[0]
        if isinstance(first, ast.Constant) and isinstance(first.value, str):
            found.append((node.lineno, first.value))
    return found


def measure(roots: tuple[Path, ...] = ADDON_ROOTS) -> tuple[list[Unresolved], dict]:
    modules = iter_modules(roots)
    if not modules:
        raise RuntimeError(
            "no module ships an i18n/<module>.pot under "
            + ", ".join(_display(r) for r in roots)
            + " -- refusing to report a clean zero on a tree this gate never read"
        )
    unresolved: list[Unresolved] = []
    total = 0
    for module, module_dir, pot in modules:
        msgids = read_msgids(pot)
        for source_file in sorted(module_dir.rglob("*.py")):
            if "__pycache__" in source_file.parts or _is_test_path(source_file):
                continue
            for lineno, text in iter_gettext_literals(source_file):
                total += 1
                if text not in msgids:
                    unresolved.append(
                        Unresolved(module, _display(source_file), lineno, text)
                    )
    stats = {"modules": len(modules), "strings": total, "unresolved": len(unresolved)}
    return unresolved, stats


def by_module(found: list[Unresolved]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in found:
        counts[item.module] = counts.get(item.module, 0) + 1
    return counts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", action="store_true", help="print the count only")
    parser.add_argument("--json", action="store_true", help="machine-readable")
    parser.add_argument("--module", help="report one module in full")
    parser.add_argument(
        "--cost",
        action="store_true",
        help="for each string, what rewording into it would strand (reads the .po files)",
    )
    parser.add_argument("--top", type=int, default=20, help="0 for all")
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if anything is unresolved"
    )
    doc_measured.main_flags(parser)
    args = parser.parse_args(argv)

    try:
        found, stats = measure()
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.check_doc or args.update_doc:
        path = Path(__file__).resolve()
        if args.update_doc:
            changed = doc_measured.update(path, stats)
            print(
                f"[{'upd' if changed else ' ok'}] {doc_measured.render(stats)}",
            )
            return 0
        problems = doc_measured.check(path, stats)
        if problems:
            print("module docstring's MEASURED block is stale:")
            for problem in problems:
                print(f"  {problem}")
            print("\n  python tooling/architecture/translation_catalog.py --update-doc")
            return 1
        print(f"[ ok] MEASURED block is fresh: {doc_measured.render(stats)}")
        return 0

    if args.module:
        found = [item for item in found if item.module == args.module]

    if args.count:
        print(len(found))
        return 0
    if args.json:
        print(json.dumps([asdict(f) for f in found], indent=2))
        return 0

    print("Translatable strings with no msgid in their module's catalogue")
    print("=" * 72)
    counts = by_module(found)
    if args.module:
        shown = found if args.top == 0 else found[: args.top]
        catalogues = {}
        for item in shown:
            print(item)
            if not args.cost:
                continue
            module_dir = next(
                (d for name, d, _pot in iter_modules() if name == item.module), None
            )
            if module_dir is None:
                continue
            if item.module not in catalogues:
                catalogues[item.module] = read_msgids(
                    module_dir / "i18n" / f"{item.module}.pot"
                )
            cost = reword_cost(item.source, module_dir, catalogues[item.module])
            if cost is None:
                print("           new: nothing near it in the catalogue, costs nothing")
            else:
                print(
                    f"           looks like a rewording of {cost.previous[:56]!r}"
                    f" ({cost.ratio:.2f})"
                )
                verdict = (
                    f"strands {cost.translated} translation(s)"
                    if cost.translated
                    else "strands nothing: that msgid is untranslated everywhere"
                )
                print(
                    f"           {verdict}, of {cost.catalogues} catalogues"
                    + (f": {' '.join(cost.languages[:12])}" if cost.translated else "")
                )
        if len(found) > len(shown):
            print(f"  ... and {len(found) - len(shown)} more (--top 0 for all)")
    else:
        ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
        shown = ranked if args.top == 0 else ranked[: args.top]
        for module, count in shown:
            print(f"  {count:5d}  {module}")
        if len(ranked) > len(shown):
            print(
                f"  ... and {len(ranked) - len(shown)} more modules (--top 0 for all)"
            )
    print("-" * 72)
    print(
        f"\n{stats['unresolved']} of {stats['strings']} strings in "
        f"{stats['modules']} modules cannot be resolved"
    )
    print(
        "\nIf one of these is a string you just wrote, export -- do not move the floor:"
    )
    print("  odoo-bin i18n export -c <conf> -d <db> <module>")
    print("\nThe floor is for debt you are accepting, not for a string you introduced:")
    print("  python tooling/architecture/translation_catalog.py --count \\")
    print("      | xargs python tooling/ratchet/ratchet.py translations --count")
    return 1 if (args.check and found) else 0


if __name__ == "__main__":
    sys.exit(main())
