from . import mixin_approval_threshold  # isort: skip

from . import (
    approval_approver,
    approval_category,
    approval_category_approver,
    approval_document_requirement,
    mixin_approval,
    approval_refusal_reason,
    approval_request,
    approval_request_action,
    approval_request_compute,
    approval_request_cron,
    approval_request_helper,
    approval_request_validation,
    approval_rule,
    approval_template,
    approval_test_document,
    approval_utils,
    ir_attachment,
    mail_activity,
    mail_activity_type,
    res_groups,
    res_users,
)
