import contextlib
import logging
import re
import textwrap
import typing
from binascii import Error as binascii_error
from collections import defaultdict
from collections.abc import Collection, Sequence
from types import NotImplementedType
from typing import Any, Literal, Self

from lxml import html
from psycopg import IntegrityError

from odoo import _, api, fields, models, modules, tools
from odoo.api import DomainType, ValuesType
from odoo.exceptions import AccessError, MissingError
from odoo.fields import Command, Domain
from odoo.tools import SQL, clean_context, groupby
from odoo.tools.misc import OrderedSet

from odoo.addons.mail.tools.discuss import Store, StoreFieldsInput, StoreFieldSpec

if typing.TYPE_CHECKING:
    from .discuss.mail_guest import MailGuest
    from .mail_activity_type import MailActivityType
    from .mail_alias_domain import MailAliasDomain
    from .mail_followers import MailFollowers
    from .mail_mail import MailMail
    from .mail_message_link_preview import MessageMailLinkPreview
    from .mail_message_reaction import MailMessageReaction
    from .mail_message_subtype import MailMessageSubtype
    from .mail_notification import MailNotification
    from .mail_tracking_value import MailTrackingValue
    from .res_partner import ResPartner
    from odoo.addons.base.models.ir_mail_server import IrMail_Server
    from odoo.addons.base.models.res_company import ResCompany
    from odoo.addons.bus.models.ir_attachment import IrAttachment

_logger = logging.getLogger(__name__)
_image_dataurl = re.compile(
    r'(data:image/[a-z]+?);base64,([a-z0-9+/\n]{3,}=*)\n*([\'"])(?: data-filename="([^"]*)")?',
    re.IGNORECASE,
)


MESSAGE_FETCH_LIMIT_MAX = 100
MESSAGE_FETCH_LIMIT_DEFAULT = 30
MESSAGE_FETCH_PARAMS = frozenset(
    {"search_term", "is_notification", "before", "after", "around", "limit"}
)


class MailMessage(models.Model):
    _name = "mail.message"
    _inherit = ["bus.listener.mixin"]
    _description = "Message"
    _order = "id desc"
    _rec_name = "subject"

    _mail_partner_fields = ()

    @api.model
    def default_get(self, fields: list[str]) -> ValuesType:
        res = super().default_get(fields)
        missing_author = "author_id" in fields and "author_id" not in res
        missing_email_from = "email_from" in fields and "email_from" not in res
        if missing_author or missing_email_from:
            author_id, email_from = self.env["mail.thread"]._message_compute_author(
                res.get("author_id"), res.get("email_from")
            )
            if missing_email_from:
                res["email_from"] = email_from
            if missing_author:
                res["author_id"] = author_id
        return res

    subject = fields.Char("Subject")
    date = fields.Datetime("Date", default=fields.Datetime.now)
    body = fields.Html("Contents", default="", sanitize_style=True)
    preview = fields.Char(
        "Preview",
        compute="_compute_preview",
        help="The text-only beginning of the body used as email preview.",
    )
    message_link_preview_ids: MessageMailLinkPreview = fields.One2many(
        "mail.message.link.preview", "message_id", groups="base.group_erp_manager"
    )
    reaction_ids: MailMessageReaction = fields.One2many(
        "mail.message.reaction",
        "message_id",
        string="Reactions",
        groups="base.group_system",
    )
    attachment_ids: IrAttachment = fields.Many2many(
        "ir.attachment",
        "message_attachment_rel",
        "message_id",
        "attachment_id",
        string="Attachments",
        bypass_search_access=True,
    )
    parent_id: MailMessage = fields.Many2one(
        "mail.message", "Parent Message", index="btree_not_null", ondelete="set null"
    )
    child_ids: MailMessage = fields.One2many(
        "mail.message", "parent_id", "Child Messages"
    )
    model = fields.Char("Related Document Model")
    res_id = fields.Many2oneReference("Related Document ID", model_field="model")
    record_name = fields.Char(
        "Message Record Name", compute="_compute_record_name", store=False
    )
    record_alias_domain_id: MailAliasDomain = fields.Many2one(
        "mail.alias.domain", "Alias Domain", ondelete="set null"
    )
    record_company_id: ResCompany = fields.Many2one(
        "res.company", "Company", ondelete="set null"
    )
    message_type = fields.Selection(
        [
            ("email", "Incoming Email"),
            ("comment", "Comment"),
            ("email_outgoing", "Outgoing Email"),
            ("notification", "System notification"),
            ("auto_comment", "Automated Targeted Notification"),
            ("out_of_office", "Out-of-office Message"),
            ("user_notification", "User Specific Notification"),
        ],
        "Type",
        required=True,
        default="comment",
        help="Used to categorize message generator"
        "\n'email': generated by an incoming email e.g. mailgateway"
        "\n'comment': generated by user input e.g. through discuss or composer"
        "\n'email_outgoing': generated by a mailing"
        "\n'notification': generated by system e.g. tracking messages"
        "\n'auto_comment': generated by automated notification mechanism e.g. acknowledgment"
        "\n'user_notification': generated for a specific recipient",
    )
    subtype_id: MailMessageSubtype = fields.Many2one(
        "mail.message.subtype", "Subtype", ondelete="set null", index=True
    )
    mail_activity_type_id: MailActivityType = fields.Many2one(
        "mail.activity.type",
        "Mail Activity Type",
        index="btree_not_null",
        ondelete="set null",
    )
    is_internal = fields.Boolean(
        "Employee Only",
        help="Hide to public / portal users, independently from subtype configuration.",
    )
    email_from = fields.Char(
        "From",
        help="Email address of the sender. This field is set when no matching partner is found and replaces the author_id field in the chatter.",
    )
    author_id: ResPartner = fields.Many2one(
        "res.partner",
        "Author",
        index=True,
        ondelete="set null",
        help="Author of the message. If not set, email_from may hold an email address that did not match any partner.",
    )
    author_avatar = fields.Binary(
        "Author's avatar",
        related="author_id.avatar_128",
        depends=["author_id"],
        readonly=False,
    )
    author_guest_id: MailGuest = fields.Many2one(
        string="Guest", comodel_name="mail.guest"
    )
    is_current_user_or_guest_author = fields.Boolean(
        compute="_compute_is_current_user_or_guest_author"
    )
    partner_ids: ResPartner = fields.Many2many(
        "res.partner", string="Recipients", context={"active_test": False}
    )
    incoming_email_to = fields.Text("Emails To")
    incoming_email_cc = fields.Char("Emails Cc")
    outgoing_email_to = fields.Char("Outgoing Emails To")
    notified_partner_ids: ResPartner = fields.Many2many(
        "res.partner",
        "mail_notification",
        string="Partners with Need Action",
        context={"active_test": False},
        depends=["notification_ids"],
        copy=False,
    )
    needaction = fields.Boolean(
        "Need Action", compute="_compute_needaction", search="_search_needaction"
    )
    has_error = fields.Boolean(
        "Has error", compute="_compute_has_error", search="_search_has_error"
    )
    notification_ids: MailNotification = fields.One2many(
        "mail.notification",
        "mail_message_id",
        "Notifications",
        bypass_search_access=True,
        copy=False,
        depends=["notified_partner_ids"],
    )
    starred_partner_ids: ResPartner = fields.Many2many(
        "res.partner", "mail_message_res_partner_starred_rel", string="Favorited By"
    )
    pinned_at = fields.Datetime(
        "Pinned", help="Datetime at which the message has been pinned"
    )
    starred = fields.Boolean(
        "Starred",
        compute="_compute_starred",
        search="_search_starred",
        compute_sudo=False,
        help="Current user has a starred notification linked to this message",
    )
    tracking_value_ids: MailTrackingValue = fields.One2many(
        "mail.tracking.value",
        "mail_message_id",
        string="Tracking values",
        groups="base.group_system",
        help="Tracked values are stored in a separate model. This field allow to reconstruct "
        "the tracking and to generate statistics on the model.",
    )
    reply_to_force_new = fields.Boolean(
        "No threading for answers",
        help="If true, answers do not go in the original document discussion thread. Instead, it will check for the reply_to in tracking message-id and redirected accordingly. This has an impact on the generated message-id.",
    )
    message_id = fields.Char(
        "Message-Id",
        help="Message unique identifier",
        index="btree",
        readonly=True,
        copy=False,
    )
    reply_to = fields.Char(
        "Reply-To",
        help="Reply email address. Setting the reply_to bypasses the automatic thread creation.",
    )
    mail_server_id: IrMail_Server = fields.Many2one(
        "ir.mail_server", "Outgoing mail server"
    )
    email_layout_xmlid = fields.Char("Layout", copy=False)
    email_add_signature = fields.Boolean(default=True)
    mail_ids: MailMail = fields.One2many(
        "mail.mail", "mail_message_id", string="Mails", groups="base.group_system"
    )

    _model_res_id_id_idx = models.Index("(model, res_id, id)")

    @api.depends("body")
    def _compute_preview(self) -> None:
        for message in self:
            plaintext_ct = tools.mail.html_to_inner_content(message.body)
            message.preview = textwrap.shorten(plaintext_ct, 190)

    def _get_linked_messages(self) -> tuple[dict[int, Self], Self]:
        ids_by_message = defaultdict(list)
        for message in self:
            if tools.is_html_empty(message.body):
                continue
            str_ids = html.fromstring(message.body).xpath(
                "//a[contains(@class, 'o_message_redirect') and @data-oe-model='mail.message']/@data-oe-id",
            )
            for str_id in str_ids:
                with contextlib.suppress(ValueError, TypeError):
                    ids_by_message[message.id].append(int(str_id))
        mids = {mid for mids in ids_by_message.values() for mid in mids}
        if not mids:
            return {}, self.browse()
        linked_messages = self.sudo(False).search(Domain("id", "in", list(mids)))
        readable = set(linked_messages.ids)
        by_message = {}
        for message_id, linked_ids in ids_by_message.items():
            allowed = [mid for mid in linked_ids if mid in readable]
            if allowed:
                by_message[message_id] = linked_messages.browse(allowed)
        return by_message, linked_messages

    @api.depends("model", "res_id")
    def _compute_record_name(self) -> None:
        free = self.filtered(
            lambda m: not m.model or not m.res_id or m.model not in self.env
        )
        free.record_name = False
        for message, record in (self - free)._record_by_message().items():
            try:
                message.record_name = record.sudo().display_name
            except MissingError:
                message.record_name = False

    @api.depends("author_id", "author_guest_id")
    @api.depends_context("guest", "uid")
    def _compute_is_current_user_or_guest_author(self) -> None:
        user = self.env.user
        guest = self.env["mail.guest"]._get_guest_from_context()
        for message in self:
            if (
                not user._is_public()
                and (message.author_id and message.author_id == user.partner_id)
            ) or (message.author_guest_id and message.author_guest_id == guest):
                message.is_current_user_or_guest_author = True
            else:
                message.is_current_user_or_guest_author = False

    @api.depends("notification_ids")
    @api.depends_context("uid")
    def _compute_needaction(self) -> None:
        flagged = self._get_message_ids_with_notification(
            [
                ("res_partner_id", "=", self.env.user.partner_id.id),
                ("is_read", "=", False),
            ]
        )
        for message in self:
            message.needaction = message.id in flagged

    def _get_message_ids_with_notification(self, domain) -> set[int]:
        return set(
            self.env["mail.notification"]
            .sudo()
            .search_fetch(
                [("mail_message_id", "in", self.ids), *domain],
                ["mail_message_id"],
            )
            .mail_message_id.ids
        )

    @api.model
    def _search_needaction(
        self, operator: str, operand: Any
    ) -> list | NotImplementedType:
        if operator != "in":
            return NotImplemented
        notification_ids = self.env["mail.notification"]._search(
            [
                ("res_partner_id", "=", self.env.user.partner_id.id),
                ("is_read", "=", False),
            ]
        )
        return [("notification_ids", "in", notification_ids)]

    @api.depends("notification_ids.notification_status")
    def _compute_has_error(self) -> None:
        failed = self._get_message_ids_with_notification(
            [("notification_status", "in", ("bounce", "exception"))]
        )
        for message in self:
            message.has_error = message.id in failed

    @api.model
    def _search_has_error(
        self, operator: str, operand: Any
    ) -> list | NotImplementedType:
        if operator != "in":
            return NotImplemented
        return [("notification_ids.notification_status", "in", ("bounce", "exception"))]

    @api.depends("starred_partner_ids")
    @api.depends_context("uid")
    def _compute_starred(self) -> None:
        self.env["mail.message"].flush_model(["starred_partner_ids"])
        rows = self.env.execute_query(
            SQL(
                """ SELECT mail_message_id
                    FROM mail_message_res_partner_starred_rel
                    WHERE mail_message_id = ANY(%s) AND res_partner_id = %s """,
                self.ids,
                self.env.user.partner_id.id,
            )
        )
        starred_ids = {mid for [mid] in rows}
        for message in self:
            message.starred = message.id in starred_ids

    @api.model
    def _search_starred(self, operator: str, operand: Any) -> list | NotImplementedType:
        if operator != "in":
            return NotImplemented
        return [("starred_partner_ids", "in", self.env.user.partner_id.ids)]

    def _is_thread_model(self) -> bool:
        self.ensure_one()
        return self._is_thread_model_name(self.sudo().model)

    @api.model
    def _is_thread_model_name(self, model_name: str) -> bool:
        return bool(model_name) and isinstance(
            self.env.get(model_name), self.pool["mail.thread"]
        )

    def _get_thread_model(self) -> models.Model:
        self.ensure_one()
        return self.env[self.sudo().model if self._is_thread_model() else "mail.thread"]

    @api.model
    def _get_with_access(self, message_id: int, mode: str = "read", **kwargs) -> Self:
        message = self.browse(message_id).exists()
        if not message:
            return message

        allowed_params = message._get_thread_model()._get_allowed_access_params()
        if invalid := (set(kwargs) - allowed_params):
            _logger.warning("Invalid parameters to _get_with_access: %s", invalid)
            kwargs = {
                key: value for key, value in kwargs.items() if key in allowed_params
            }

        if (
            self.env.user._is_public()
            and self.env["mail.guest"]._get_guest_from_context()
        ):
            if not message.sudo(False)._get_forbidden_access(mode):
                return message
        elif message.sudo(False).has_access(mode):
            return message

        if message.res_id and message._is_thread_model():
            thread_su = self.env[message.model].browse(message.res_id).sudo()
            access_mode = thread_su._mail_get_operation_for_mail_message_operation(
                mode
            ).get(thread_su)
            if access_mode and self.env[message.model]._get_thread_with_access(
                message.res_id, mode=access_mode, **kwargs
            ):
                return message

        return self.browse()

    @api.model_create_multi
    def create(self, vals_list: list[ValuesType]) -> Self:
        vals_list = [dict(values) for values in vals_list]
        if not (self.env.su or self.env.user.has_group("base.group_user")):
            for values in vals_list:
                values.pop("author_id", None)
                values.pop("email_from", None)
            self = self.with_context(
                {
                    k: v
                    for k, v in self.env.context.items()
                    if k not in ["default_author_id", "default_email_from"]
                }
            )

        for values in vals_list:
            if "email_from" not in values:
                _author_id, email_from = self.env[
                    "mail.thread"
                ]._message_compute_author(values.get("author_id"), email_from=None)
                values["email_from"] = email_from

        reply_tos = self._get_reply_to_batch(vals_list)
        tracking_values_list = []
        for index, values in enumerate(vals_list):
            if not values.get("message_id"):
                values["message_id"] = self._get_message_id(values)
            if "reply_to" not in values:
                values["reply_to"] = reply_tos[index]
            if not values.get("attachment_ids", True):
                del values["attachment_ids"]
            if "body" in values:
                values["body"] = self._extract_body_attachments(values)
            tracking_values_list.append(values.pop("tracking_value_ids", False))

        messages = super().create(vals_list)

        self._check_created_attachments_access(messages, vals_list)

        for message, values, tracking_values_cmd in zip(
            messages, vals_list, tracking_values_list, strict=True
        ):
            if tracking_values_cmd:
                message._create_tracking_values(tracking_values_cmd)
            if message._is_thread_message_visible(vals=values):
                message._invalidate_documents(values.get("model"), values.get("res_id"))

        return messages

    def _get_reply_to_batch(self, vals_list: list[ValuesType]) -> list:
        out: list = [None] * len(vals_list)
        by_group = defaultdict(list)
        for index, values in enumerate(vals_list):
            if "reply_to" in values:
                continue
            model = values.get("model", self.env.context.get("default_model"))
            res_id = (
                values.get("res_id", self.env.context.get("default_res_id")) or False
            )
            if model and model not in self.env:
                _logger.warning(
                    "mail.message created with a model that is not in the registry: %s",
                    model,
                )
                model, res_id = None, False
            is_thread = self._is_thread_message(vals={"model": model, "res_id": res_id})
            if not is_thread:
                res_id = False
            by_group[(model, is_thread)].append((index, res_id, values))

        for (model, is_thread), items in by_group.items():
            if is_thread:
                records = self.env[model].browse(
                    {res_id for _index, res_id, _values in items}
                )
            else:
                records = self.env[model] if model else self.env["mail.thread"]
            records_su = records.sudo()
            addresses = records_su._notify_get_reply_to_addresses()
            self.env["res.partner"].browse(
                {
                    values["author_id"]
                    for _index, res_id, values in items
                    if values.get("author_id") and res_id in addresses
                }
            ).mapped("name")
            for index, res_id, values in items:
                address = addresses.get(res_id)
                out[index] = (
                    records_su._notify_get_reply_to_formatted_email(
                        address, author_id=values.get("author_id")
                    )
                    if address
                    else values.get("email_from")
                )
        return out

    def _extract_body_attachments(self, values: ValuesType) -> str:
        Attachments = self.env["ir.attachment"].with_context(
            clean_context(self.env.context)
        )
        data_to_url = {}

        def base64_to_boundary(match: re.Match) -> str:
            key = match.group(2)
            if not data_to_url.get(key):
                name = match.group(4) or "image%s" % len(data_to_url)
                try:
                    attachment = Attachments.create(
                        {
                            "name": name,
                            "datas": match.group(2),
                            "res_model": values.get("model"),
                            "res_id": values.get("res_id"),
                        }
                    )
                except binascii_error:
                    _logger.warning(
                        "Impossible to create an attachment out of badly formated base64 embedded image. Image has been removed."
                    )
                    return match.group(3)
                else:
                    attachment.generate_access_token()
                    attachments = values.setdefault("attachment_ids", [])
                    attachments.append((4, attachment.id))
                    data_to_url[key] = [
                        "/web/image/%s?access_token=%s"
                        % (attachment.id, attachment.access_token),
                        name,
                        attachment.id,
                    ]
            return f'{data_to_url[key][0]}{match.group(3)} alt="{data_to_url[key][1]}" data-attachment-id="{data_to_url[key][2]}"'

        return _image_dataurl.sub(base64_to_boundary, values["body"] or "")

    def _check_created_attachments_access(
        self, messages: Self, vals_list: list[ValuesType]
    ) -> None:
        doc_to_attachment_ids = defaultdict(set)
        if not all(
            isinstance(command, int) or command[0] in (4, 6)
            for values in vals_list
            for command in values.get("attachment_ids", ())
        ):
            if messages.attachment_ids:
                messages.attachment_ids.check_access("read")
            return

        for values in vals_list:
            message_attachment_ids = set()
            for command in values.get("attachment_ids", ()):
                if isinstance(command, int):
                    message_attachment_ids.add(command)
                elif command[0] == 6:
                    message_attachment_ids |= set(command[2])
                else:
                    message_attachment_ids.add(command[1])
            if message_attachment_ids:
                key = (values.get("model"), values.get("res_id"))
                doc_to_attachment_ids[key] |= message_attachment_ids

        attachment_ids_all = {
            attachment_id
            for doc_attachment_ids in doc_to_attachment_ids.values()
            for attachment_id in doc_attachment_ids
        }
        AttachmentSudo = (
            self.env["ir.attachment"].sudo().with_prefetch(list(attachment_ids_all))
        )
        attachments_tocheck = self.env["ir.attachment"]
        for (model, res_id), doc_attachment_ids in doc_to_attachment_ids.items():
            attachments_tocheck += (
                AttachmentSudo.browse(doc_attachment_ids)
                .filtered(
                    lambda att, model=model, res_id=res_id: (
                        att.res_model != model or att.res_id != res_id
                    )
                )
                .sudo(False)
            )
        if attachments_tocheck:
            attachments_tocheck.check_access("read")

    def _create_tracking_values(self, tracking_values_cmd: list) -> None:
        self.ensure_one()
        vals_lst = [
            dict(cmd[2], mail_message_id=self.id)
            for cmd in tracking_values_cmd
            if len(cmd) == 3 and cmd[0] == 0
        ]
        other_cmd = [cmd for cmd in tracking_values_cmd if len(cmd) != 3 or cmd[0] != 0]
        if vals_lst:
            self.env["mail.tracking.value"].sudo().create(vals_lst)
        if other_cmd:
            self.sudo().write({"tracking_value_ids": other_cmd})

    def read(
        self, fields: Sequence[str] | None = None, load: str = "_classic_read"
    ) -> list[dict]:
        self.check_access("read")
        return super().read(fields=fields, load=load)

    def copy_data(self, default: ValuesType | None = None) -> list[ValuesType]:
        self.check_access("read")
        return super().copy_data(default=default)

    def fetch(self, field_names: Collection[str] | None = None) -> None:
        self = self.sudo()
        return super().fetch(field_names)

    def write(self, vals: ValuesType) -> Literal[True]:
        if not (self.env.su or self.env.user.has_group("base.group_user")):
            vals = {
                key: value
                for key, value in vals.items()
                if key not in ("author_id", "email_from")
            }
        record_changed = "model" in vals or "res_id" in vals
        if record_changed and not self.env.is_system():
            raise AccessError(
                _("Only administrators can modify 'model' and 'res_id' fields.")
            )
        if record_changed or "message_type" in vals:
            self._invalidate_documents()
        res = super().write(vals)
        if vals.get("attachment_ids"):
            self.attachment_ids.check_access("read")
        if "notification_ids" in vals or record_changed:
            self._invalidate_documents()
        return res

    def unlink(self) -> Literal[True]:
        if not self:
            return True
        self.check_access("unlink")
        own_ids = set(self._ids)
        self.mapped("attachment_ids").filtered(
            lambda attach: (
                attach.res_model == self._name
                and (attach.res_id in own_ids or attach.res_id == 0)
            )
        ).unlink()
        messages_by_partner = defaultdict(lambda: self.env["mail.message"])
        partners_with_user = self.partner_ids.filtered("user_ids")
        for elem in self:
            for partner in (
                elem.partner_ids & partners_with_user | elem.notification_ids.author_id
            ):
                messages_by_partner[partner] |= elem
        for partner, messages in messages_by_partner.items():
            partner._bus_send("mail.message/delete", {"message_ids": messages.ids})
        return super().unlink()

    def export_data(self, fields_to_export: list[str]) -> dict:
        if not self.env.is_admin():
            raise AccessError(
                _("Only administrators are allowed to export mail message")
            )

        return super().export_data(fields_to_export)

    def action_open_document(self) -> dict:
        self.ensure_one()
        return {
            "res_id": self.res_id,
            "res_model": self.model,
            "target": "current",
            "type": "ir.actions.act_window",
            "view_mode": "form",
        }

    @api.model
    def mark_all_as_read(self, domain: DomainType | None = None) -> list[int]:
        if domain:
            return self.search(domain).set_message_done()
        return self.browse()._mark_notifications_read(
            [("res_partner_id", "=", self.env.user.partner_id.id)]
        )

    def set_message_done(self) -> list[int]:
        return self._mark_notifications_read(
            [
                ("mail_message_id", "in", self.ids),
                ("res_partner_id", "=", self.env.user.partner_id.id),
            ]
        )

    def _mark_notifications_read(self, domain) -> list[int]:
        notifications = (
            self.env["mail.notification"]
            .sudo()
            .search_fetch([*domain, ("is_read", "=", False)], ["mail_message_id"])
        )
        if not notifications:
            return []
        notifications.write({"is_read": True})
        message_ids = notifications.mail_message_id.ids
        self.env.user._bus_send(
            "mail.message/mark_as_read",
            {
                "message_ids": message_ids,
                "needaction_inbox_counter": self.env.user.partner_id._get_needaction_count(),
            },
        )
        return message_ids

    @api.model
    def unstar_all(self) -> None:
        starred_messages = self.search(
            [("starred_partner_ids", "in", self.env.user.partner_id.id)]
        )
        starred_messages.sudo().starred_partner_ids = [
            Command.unlink(self.env.user.partner_id.id)
        ]
        self.env.user._bus_send(
            "mail.message/toggle_star",
            {"message_ids": starred_messages.ids, "starred": False},
        )

    def toggle_message_starred(self) -> dict:
        self.ensure_one()
        self.check_access("read")
        starred = not self.starred
        if starred:
            self.sudo().starred_partner_ids = [
                Command.link(self.env.user.partner_id.id)
            ]
        else:
            self.sudo().starred_partner_ids = [
                Command.unlink(self.env.user.partner_id.id)
            ]
        self.env.user._bus_send(
            "mail.message/toggle_star", {"message_ids": [self.id], "starred": starred}
        )
        return Store().add(self, {"starred": self.starred}).get_result()

    @api.model
    def _clamp_fetch_limit(self, limit: int) -> int:
        try:
            limit = int(limit)
        except TypeError, ValueError:
            return MESSAGE_FETCH_LIMIT_DEFAULT
        return max(1, min(limit, MESSAGE_FETCH_LIMIT_MAX))

    @api.model
    def _to_message_cursor(
        self, value: int | str | Literal[False] | None
    ) -> int | None:
        if value is None or value is False:
            return None
        try:
            return int(value)
        except TypeError, ValueError:
            return None

    @api.model
    def _sanitize_fetch_params(self, fetch_params: dict | None) -> dict:
        return {
            key: value
            for key, value in (fetch_params or {}).items()
            if key in MESSAGE_FETCH_PARAMS
        }

    def _message_fetch(
        self,
        domain: DomainType | None,
        *,
        thread: models.BaseModel | None = None,
        search_term: str | None = None,
        is_notification: bool | None = None,
        before: int | Literal[False] | None = None,
        after: int | Literal[False] | None = None,
        around: int | Literal[False] | None = None,
        limit: int = MESSAGE_FETCH_LIMIT_DEFAULT,
    ) -> dict:
        limit = self._clamp_fetch_limit(limit)
        before = self._to_message_cursor(before)
        after = self._to_message_cursor(after)
        around = self._to_message_cursor(around)
        res = {}
        domain = Domain(True if domain is None else domain)
        if thread:
            domain &= (
                Domain("res_id", "=", thread.id)
                & Domain("model", "=", thread._name)
                & Domain("message_type", "!=", "user_notification")
            )
        if is_notification is True:
            domain &= Domain("message_type", "=", "notification")
        elif is_notification is False:
            domain &= Domain("message_type", "!=", "notification")
        if search_term:
            search_term = (
                search_term.replace("\\", "\\\\")
                .replace("%", "\\%")
                .replace("_", "\\_")
                .replace(" ", "%")
            )
            attachment_domain = Domain("name", "ilike", search_term)
            if thread:
                attachment_domain &= Domain("res_model", "=", thread._name) & Domain(
                    "res_id", "=", thread.id
                )
            message_domain = Domain.OR(
                [
                    [
                        (
                            "attachment_ids",
                            "in",
                            self.env["ir.attachment"].sudo()._search(attachment_domain),
                        )
                    ],
                    [("body", "ilike", search_term)],
                    [("subject", "ilike", search_term)],
                    [("subtype_id.description", "ilike", search_term)],
                ]
            )
            if thread and is_notification is not False:
                tracking_value_domain = (
                    Domain("mail_message_id.res_id", "=", thread.id)
                    & Domain("mail_message_id.model", "=", thread._name)
                    & self._get_tracking_values_domain(search_term)
                )
                tracking_values = (
                    self.env["mail.tracking.value"].sudo().search(tracking_value_domain)
                )
                accessible_tracking_value_ids = (
                    tracking_values._filter_has_field_access(self.env)
                )
                message_domain |= Domain(
                    "id", "in", accessible_tracking_value_ids.mail_message_id.ids
                )
            domain &= message_domain
        if search_term or is_notification is not None:
            res["count"] = self.search_count(domain, limit=self._SEARCH_COUNT_CAP)
        if around is not None:
            after_limit = limit // 2
            before_limit = limit - after_limit
            messages_before = self.search(
                domain & Domain("id", "<=", around),
                limit=before_limit,
                order="id DESC",
            )
            messages_after = (
                self.search(
                    domain & Domain("id", ">", around),
                    limit=after_limit,
                    order="id ASC",
                )
                if after_limit
                else self.browse()
            )
            return {
                **res,
                "messages": (messages_after + messages_before).sorted(
                    "id", reverse=True
                ),
            }
        if before:
            domain &= Domain("id", "<", before)
        if after:
            domain &= Domain("id", ">", after)
        res["messages"] = self.search(
            domain, limit=limit, order="id ASC" if after else "id DESC"
        )
        if after:
            res["messages"] = res["messages"].sorted("id", reverse=True)
        return res

    def _get_tracking_values_domain(self, search_term: str) -> Domain:
        numeric_term = None
        with contextlib.suppress(ValueError, TypeError):
            numeric_term = float(search_term)
        domain = Domain.OR(
            Domain(field_name, "ilike", search_term)
            for field_name in (
                "old_value_char",
                "new_value_char",
                "old_value_text",
                "new_value_text",
                "old_value_datetime",
                "new_value_datetime",
                "field_id.name",
                "field_id.field_description",
            )
        )
        if numeric_term is not None:
            epsilon = 1e-9
            domain |= Domain("field_id.ttype", "in", ("float", "monetary")) & Domain.OR(
                Domain(field_name, ">=", numeric_term - epsilon)
                & Domain(field_name, "<=", numeric_term + epsilon)
                for field_name in ("old_value_float", "new_value_float")
            )
            if numeric_term.is_integer():
                domain |= Domain("field_id.ttype", "=", "integer") & Domain.OR(
                    Domain(field_name, "=", int(numeric_term))
                    for field_name in ("old_value_integer", "new_value_integer")
                )
        return domain

    def _message_reaction(
        self,
        content: str,
        action: str,
        partner: ResPartner,
        guest: MailGuest,
        store: Store | None = None,
    ) -> None:
        self.ensure_one()
        if action not in ("add", "remove"):
            raise ValueError(f"Wrong reaction action ({action})")
        domain = [
            ("message_id", "=", self.id),
            ("partner_id", "=", partner.id),
            ("guest_id", "=", guest.id),
            ("content", "=", content),
        ]
        reaction = self.env["mail.message.reaction"].search(domain)
        if action == "add" and not reaction:
            create_values = {
                "message_id": self.id,
                "content": content,
                "partner_id": partner.id,
                "guest_id": guest.id,
            }
            try:
                with self.env.cr.savepoint():
                    self.env["mail.message.reaction"].create(create_values)
            except IntegrityError:
                pass
        if action == "remove" and reaction:
            reaction.unlink()
        if store:
            self._reaction_group_to_store(store, content)
        self._bus_send_reaction_group(content)

    def _bus_send_reaction_group(self, content: str) -> None:
        store = Store(bus_channel=self._bus_channel())
        self._reaction_group_to_store(store, content)
        store.bus_send()

    def _reaction_group_to_store(self, store: Store, content: str) -> None:
        group_domain = [("message_id", "=", self.id), ("content", "=", content)]
        reactions = self.env["mail.message.reaction"].search(group_domain)
        reaction_group = (
            Store.Many(reactions, mode="ADD")
            if reactions
            else [("DELETE", {"message": self.id, "content": content})]
        )
        store.add(self, {"reactions": reaction_group})

    def _field_store_repr(self, field_name: str) -> list:
        if field_name == "message_link_preview_ids":
            return [
                Store.Many(
                    "message_link_preview_ids",
                    value=lambda m: (
                        m.sudo()
                        .message_link_preview_ids.filtered(
                            lambda message_link_preview: (
                                not message_link_preview.is_hidden
                            )
                        )
                        .sorted(
                            lambda message_link_preview: (
                                message_link_preview.sequence,
                                message_link_preview.id,
                            )
                        )
                    ),
                )
            ]
        return [field_name]

    def _is_envelope_visible(self, target: Store.Target) -> bool:
        self.ensure_one()
        return target.is_internal(self.env) or not (
            self.author_id or self.author_guest_id
        )

    def _to_store_defaults(self, target: Store.Target) -> StoreFieldsInput:
        field_names = [
            Store.Many(
                "attachment_ids",
                sort="id",
                dynamic_fields=lambda m: m._get_store_attachment_fields(target),
                sudo=True,
            ),
            Store.One("author_guest_id", ["avatar_128", "name"], sudo=True),
            Store.One(
                "author_id",
                [
                    "avatar_128",
                    "is_company",
                    Store.One("main_user_id", ["partner_id", "share"]),
                ],
                dynamic_fields=lambda m: m._get_store_partner_name_fields(),
                sudo=True,
            ),
            "body",
            "create_date",
            "date",
            Store.Attr(
                "email_from", predicate=lambda m: m._is_envelope_visible(target)
            ),
            Store.Attr(
                "incoming_email_cc", predicate=lambda m: m._is_envelope_visible(target)
            ),
            Store.Attr(
                "incoming_email_to", predicate=lambda m: m._is_envelope_visible(target)
            ),
            "message_format",
            "message_link_preview_ids",
            "message_type",
            "model",
            Store.Many(
                "partner_ids",
                "avatar_128",
                dynamic_fields=lambda m: m._get_store_partner_name_fields(),
                sort="id",
                sudo=True,
            ),
            "pinned_at",
            Store.Attr("reactions", value=lambda m: Store.Many(m.sudo().reaction_ids)),
            "record_name",
            "res_id",
            "subject",
            Store.One("subtype_id", ["description"], sudo=True),
            "write_date",
            *self._get_store_linked_messages_fields(),
        ]
        if target.is_internal(self.env) and not self.env.context.get(
            "mail_notify_inbox"
        ):
            field_names.append(
                Store.Many(
                    "notification_ids",
                    value=lambda m: (
                        m.sudo().notification_ids._filtered_for_web_client()
                    ),
                ),
            )
        return field_names

    def _to_store(
        self,
        store: Store,
        fields: list[StoreFieldSpec],
        *,
        format_reply: bool = True,
        msg_vals: dict | Literal[False] = False,
        add_followers: bool = False,
        followers: MailFollowers | None = None,
    ) -> None:
        fields = list(fields)
        if "message_format" not in fields:
            store.add_records_fields(self, fields)
            return
        fields.remove("message_format")
        scheduled_dt_by_msg_id = {}
        if msg_vals:
            scheduled_dt_by_msg_id = {
                msg.id: msg_vals.get("scheduled_date", False) for msg in self
            }
        elif self:
            schedulers = (
                self.env["mail.message.schedule"]
                .sudo()
                .search([("mail_message_id", "in", self.ids)])
            )
            for scheduler in schedulers:
                scheduled_dt_by_msg_id[scheduler.mail_message_id.id] = (
                    scheduler.scheduled_datetime
                )
        record_by_message = self._record_by_message()
        records = record_by_message.values()
        non_channel_records = sorted(
            (record for record in records if record._name != "discuss.channel"),
            key=lambda record: record._name,
        )
        target_user = store.target.get_user(self.env)
        if target_user and add_followers and non_channel_records:
            if followers is None:
                domain = Domain.OR(
                    [
                        ("res_model", "=", model),
                        ("res_id", "in", [r.id for r in records]),
                    ]
                    for model, records in groupby(
                        non_channel_records, key=lambda r: r._name
                    )
                )
                domain &= Domain("partner_id", "=", target_user.partner_id.id)
                followers = self.env["mail.followers"].sudo().search(domain)
            follower_by_record_and_partner = {
                (
                    self.env[follower.res_model].browse(follower.res_id),
                    follower.partner_id,
                ): follower
                for follower in followers
                if follower.res_model in self.env
            }
        record_fields = [
            Store.Attr("display_name", sudo=True),
            Store.Attr(
                "has_mail_thread",
                lambda record: isinstance(record, self.pool["mail.thread"]),
            ),
            Store.Attr(
                "module_icon",
                lambda record: modules.module.get_module_icon(
                    self.env[record._name]._original_module
                ),
                predicate=lambda record: self.env[record._name]._original_module,
            ),
        ]
        if target_user and add_followers and non_channel_records:
            record_fields.append(
                Store.One(
                    "selfFollower",
                    ["is_active", Store.One("partner_id", [])],
                    value=lambda r: follower_by_record_and_partner.get(
                        (r, target_user.partner_id)
                    ),
                ),
            )
        for record in records:
            store.add(record, record_fields, as_thread=True)
        if store.target.is_current_user(self.env):
            fields.append("starred")
        store.add(self, fields)
        for message in self:
            record = record_by_message.get(message)
            if record:
                try:
                    if isinstance(record, self.pool["mail.thread"]):
                        default_subject = record.sudo()._message_compute_subject()
                    else:
                        default_subject = message.record_name
                except MissingError:
                    record = None
                    default_subject = False
            else:
                default_subject = False
            data = {
                "default_subject": default_subject,
                "scheduledDatetime": scheduled_dt_by_msg_id.get(message.id, False),
                "thread": Store.One(record, [], as_thread=True),
            }

            envelope_visible = message._is_envelope_visible(store.target)
            if envelope_visible and message.incoming_email_cc:
                data["incoming_email_cc"] = tools.mail.email_split_tuples(
                    message.incoming_email_cc
                )
            if envelope_visible and message.incoming_email_to:
                data["incoming_email_to"] = tools.mail.email_split_tuples(
                    message.incoming_email_to
                )
            if store.target.is_current_user(self.env):
                displayed_tracking_ids = (
                    message.sudo().tracking_value_ids._filter_has_field_access(self.env)
                )
                if record and isinstance(record, self.pool["mail.thread"]):
                    displayed_tracking_ids = record._track_filter_for_display(
                        displayed_tracking_ids
                    )
                notifications_partners = (
                    message.sudo()
                    .notification_ids.filtered(lambda n: not n.is_read)
                    .res_partner_id
                )
                data["needaction"] = (
                    not self.env.user._is_public()
                    and self.env.user.partner_id in notifications_partners
                )
                data["trackingValues"] = displayed_tracking_ids._tracking_value_format()
            store.add(message, data)
        self._extras_to_store(store, format_reply=format_reply)

    def _get_store_partner_name_fields(self) -> list[StoreFieldSpec]:
        self.ensure_one()
        return ["name"]

    def _get_store_attachment_fields(
        self, target: Store.Target
    ) -> list[StoreFieldSpec]:
        self.ensure_one()
        if target.is_current_user(self.env) and self.is_current_user_or_guest_author:
            return self.env["ir.attachment"]._get_store_ownership_fields()
        return []

    def _get_store_linked_messages_fields(self) -> list[StoreFieldSpec]:
        by_message, linked_messages = self._get_linked_messages()
        record_by_message = linked_messages._record_by_message()
        return [
            Store.Many(
                "linked_message_ids",
                [
                    "model",
                    "res_id",
                    Store.Attr(
                        "thread",
                        lambda m: Store.One(
                            record_by_message.get(m),
                            [Store.Attr("display_name", sudo=True)],
                            as_thread=True,
                        ),
                    ),
                ],
                value=lambda m: by_message.get(m.id, m.browse()),
                only_data=True,
            ),
        ]

    def _extras_to_store(self, store: Store, format_reply: bool) -> None:
        pass

    def _message_notifications_to_store(self, store: Store) -> None:
        store.add(
            self,
            [
                Store.One("author_id", []),
                Store.One("author_guest_id", []),
                "body",
                "date",
                "message_type",
                Store.Many(
                    "notification_ids",
                    value=lambda m: m.notification_ids._filtered_for_web_client(),
                ),
                Store.One(
                    "thread",
                    [
                        Store.Attr(
                            "modelName",
                            lambda thread: (
                                self.env["ir.model"]._get(thread._name).display_name
                            ),
                        ),
                        Store.Attr("display_name", sudo=True),
                    ],
                    as_thread=True,
                ),
            ],
        )

    def _notify_message_notification_update(self) -> None:
        messages = self.env["mail.message"]
        record_by_message = self._record_by_message()
        ids_by_model = defaultdict(list)
        for record in record_by_message.values():
            ids_by_model[record._name].append(record.id)
        accessible_ids_by_model = {
            model: set(
                self.env[model].browse(ids).exists()._filtered_access("read")._ids
            )
            for model, ids in ids_by_model.items()
        }
        for message in self:
            if (record := record_by_message.get(message)) and record.id in (
                accessible_ids_by_model.get(record._name, ())
            ):
                messages += message
        messages_per_partner = defaultdict(lambda: self.env["mail.message"])
        for message in messages:
            if not self.env.user._is_public():
                messages_per_partner[self.env.user.partner_id] |= message
            if message.author_id and not any(
                user._is_public()
                for user in message.author_id.with_context(active_test=False).user_ids
            ):
                messages_per_partner[message.author_id] |= message
        for partner, messages in messages_per_partner.items():
            if user := partner.main_user_id:
                store = Store(bus_channel=user)
                messages.with_user(user)._message_notifications_to_store(store)
                store.bus_send()

    def _bus_channel(self) -> models.Model:
        self.ensure_one()
        return self.env.user

    def _filter_empty(self) -> Self:
        return self.filtered(lambda message: message._is_empty())

    def _is_empty(self) -> bool:
        self.ensure_one()
        return (
            (not self.body or tools.is_html_empty(self.body))
            and (not self.subtype_id or not self.subtype_id.description)
            and not self.attachment_ids
            and not (
                self._has_field_access(self._fields["tracking_value_ids"], "read")
                and self.tracking_value_ids
            )
        )

    @api.model
    def _get_reply_to(self, values: dict) -> str:
        author_id = values.get("author_id")
        model = values.get("model", self.env.context.get("default_model"))
        res_id = values.get("res_id", self.env.context.get("default_res_id")) or False
        email_from = values.get("email_from")
        if model and model not in self.env:
            _logger.warning(
                "mail.message created with a model that is not in the registry: %s",
                model,
            )
            model, res_id = None, False
        if self._is_thread_message(vals={"model": model, "res_id": res_id}):
            records = self.env[model].browse([res_id])
        else:
            records = self.env[model] if model else self.env["mail.thread"]
            res_id = False
        return records.sudo()._notify_get_reply_to(
            default=email_from, author_id=author_id
        )[res_id]

    @api.model
    def _get_message_id(self, values: dict) -> str:
        if values.get("reply_to_force_new", False) is True:
            message_id = tools.mail.generate_tracking_message_id("reply_to")
        elif self._is_thread_message(vals=values):
            message_id = tools.mail.generate_tracking_message_id(
                "%(res_id)s-%(model)s" % values
            )
        else:
            message_id = tools.mail.generate_tracking_message_id("private")
        return message_id

    def _is_thread_message(
        self, vals: dict | Literal[False] = False, thread: models.Model | None = None
    ) -> bool:
        vals = vals or {}
        if "model" in vals:
            res_model = vals["model"]
        elif thread:
            res_model = thread._name
        else:
            res_model = self.model
        if "res_id" in vals:
            res_id = vals["res_id"]
        elif thread and thread.ids:
            res_id = thread.ids[0]
        else:
            res_id = self.res_id
        return bool(res_id) if (res_model and res_model != "mail.thread") else False

    def _is_thread_message_visible(
        self, vals: dict | Literal[False] = False, thread: models.Model | None = None
    ) -> bool:
        if not self._is_thread_message(vals=vals, thread=thread):
            return False
        if vals and "message_type" in vals:
            message_type = vals["message_type"]
        else:
            message_type = self.message_type
        return message_type != "user_notification"

    def _invalidate_documents(
        self, model: str | None = None, res_id: int | None = None
    ) -> None:
        fnames = ["message_ids", "message_needaction", "message_needaction_counter"]
        self.flush_recordset(["model", "res_id"])
        ids_by_model = defaultdict(OrderedSet)
        for record in self:
            rec_model = model or record.model
            rec_res_id = res_id or record.res_id
            if rec_res_id and self._is_thread_model_name(rec_model):
                ids_by_model[rec_model].add(rec_res_id)
        for rec_model, rec_ids in ids_by_model.items():
            self.env[rec_model].browse(rec_ids).invalidate_recordset(fnames)

    def _records_by_model_name(self) -> dict:
        ids_by_model = defaultdict(OrderedSet)
        prefetch_ids_by_model = defaultdict(OrderedSet)
        prefetch_messages = self | self.browse(self._prefetch_ids)
        own_ids = set(self._ids)
        for message in prefetch_messages.filtered(
            lambda m: m.model in self.env and m.res_id
        ):
            target = ids_by_model if message.id in own_ids else prefetch_ids_by_model
            target[message.model].add(message.res_id)
        return {
            model_name: self.env[model_name]
            .browse(ids)
            .with_prefetch(tuple(ids | prefetch_ids_by_model[model_name]))
            for model_name, ids in ids_by_model.items()
        }

    def _record_by_message(self) -> dict:
        records_by_model_name = self._records_by_model_name()
        return {
            message: self.env[message.model]
            .browse(message.res_id)
            .with_prefetch(records_by_model_name[message.model]._prefetch_ids)
            for message in self.filtered(lambda m: m.model in self.env and m.res_id)
        }
