from . import (
    account_analytic_account,
    account_analytic_applicability,
    account_move,
    account_move_line,
    account_tax,
    home_menu_badge,
    ir_actions_report,
    product_template,
    product_product,
    product_supplierinfo,
    purchase_order,
    purchase_order_line,
    res_company,
    res_partner,
    srm_tag,
)
