from . import (
    account_move,
    account_move_line,
    account_tax,
    analytic_account,
    analytic_applicability,
    ir_actions_report,
    product_template,
    product_product,
    product_supplierinfo,
    purchase_order,
    purchase_order_line,
    res_company,
    res_partner,
)
