import logging

from odoo.db import schema
from odoo.tools.module_data import rename_in_stored_expressions

_logger = logging.getLogger(__name__)

# The salary-rule columns are stored Python too: l10n_mx_edi_payslip's rules call
# hr.version._get_work_hours_domain from amount_python_compute, and a rule loaded
# noupdate keeps the text this migration rewrites.
_STORED_PYTHON = (
    ("ir_act_server", "code"),
    ("ir_actions_server_history", "code"),
    ("ir_model_fields", "compute"),
    ("hr_salary_rule", "amount_python_compute"),
    ("hr_salary_rule", "condition_python"),
)

# §2.4.1: the free-standing domain is _get_domain_<what>, and these are the
# tail-marked _get_<what>_domain spellings the widened gate of base 1.44 made
# visible, across addons/, enterprise and agromarin. The three that several
# models spell with different bodies are rewritten per model below.
_RENAMES = (
    ("_get_access_update_domain", "_get_domain_access_update"),
    (
        "_get_action_view_sale_quotation_domain",
        "_get_domain_action_view_sale_quotation",
    ),
    ("_get_active_exceptions_domain", "_get_domain_active_exceptions"),
    ("_get_active_providers_domain", "_get_domain_active_providers"),
    ("_get_allowed_payslips_domain", "_get_domain_allowed_payslips"),
    ("_get_allowed_picking_domain", "_get_domain_allowed_picking"),
    ("_get_allowed_route_domain", "_get_domain_allowed_route"),
    ("_get_amls_domain", "_get_domain_amls"),
    ("_get_amls_with_archived_tags_domain", "_get_domain_amls_with_archived_tags"),
    (
        "_get_amount_to_pay_additional_tax_domain",
        "_get_domain_amount_to_pay_additional_tax",
    ),
    ("_get_analytic_business_domain", "_get_domain_analytic_business"),
    ("_get_appointment_search_domain", "_get_domain_appointment_search"),
    ("_get_attribute_value_domain", "_get_domain_attribute_value"),
    ("_get_audit_line_domain", "_get_domain_audit_line"),
    ("_get_audit_line_groupby_domain", "_get_domain_audit_line_groupby"),
    ("_get_available_cars_domain", "_get_domain_available_cars"),
    ("_get_available_category_domain", "_get_domain_available_category"),
    ("_get_available_template_domain", "_get_domain_available_template"),
    ("_get_available_vehicles_domain", "_get_domain_available_vehicles"),
    (
        "_get_bank_miscellaneous_move_lines_domain",
        "_get_domain_bank_miscellaneous_move_lines",
    ),
    ("_get_barcode_search_domain", "_get_domain_barcode_search"),
    ("_get_base_domain", "_get_domain_base"),
    ("_get_base_server_actions_domain", "_get_domain_base_server_actions"),
    ("_get_basic_feed_product_domain", "_get_domain_basic_feed_product"),
    ("_get_billing_address_domain", "_get_domain_billing_address"),
    ("_get_binary_field_domain", "_get_domain_binary_field"),
    ("_get_budget_analytic_account_domain", "_get_domain_budget_analytic_account"),
    ("_get_can_send_domain", "_get_domain_can_send"),
    ("_get_chain_hash_domain", "_get_domain_chain_hash"),
    ("_get_channel_slides_base_domain", "_get_domain_channel_slides_base"),
    ("_get_child_of_domain", "_get_domain_child_of_documents"),
    ("_get_commission_purchase_order_domain", "_get_domain_commission_purchase_order"),
    ("_get_contact_domain", "_get_domain_contact"),
    ("_get_contact_opportunities_domain", "_get_domain_contact_opportunities"),
    ("_get_contract_type_domain", "_get_domain_contract_type"),
    ("_get_crm_default_team_domain", "_get_domain_crm_default_team"),
    ("_get_crm_utm_domain", "_get_domain_crm_utm"),
    ("_get_dashboard_warnings_domain", "_get_domain_dashboard_warnings"),
    ("_get_default_accounts_domain", "_get_domain_default_accounts"),
    ("_get_default_mailing_domain", "_get_domain_default_mailing"),
    ("_get_default_moves_domain", "_get_domain_default_moves"),
    ("_get_default_privacy_domain", "_get_domain_default_privacy"),
    ("_get_default_so_domain", "_get_domain_default_so"),
    ("_get_delivery_address_domain", "_get_domain_delivery_address"),
    ("_get_discount_product_domain", "_get_domain_discount_product"),
    (
        "_get_draft_moves_in_hashed_period_domain",
        "_get_domain_draft_moves_in_hashed_period",
    ),
    (
        "_get_draft_moves_in_locked_period_domain",
        "_get_domain_draft_moves_in_locked_period",
    ),
    ("_get_due_domain", "_get_domain_due"),
    ("_get_duplicate_key_domain", "_get_domain_duplicate_key"),
    ("_get_embeddable_server_action_domain", "_get_domain_embeddable_server_action"),
    ("_get_employee_ids_domain", "_get_domain_employee_ids"),
    ("_get_event_domain", "_get_domain_event"),
    ("_get_event_sponsors_base_domain", "_get_domain_event_sponsors_base"),
    ("_get_event_tracks_agenda_domain", "_get_domain_event_tracks_agenda"),
    ("_get_event_tracks_domain", "_get_domain_event_tracks"),
    ("_get_expiration_domain", "_get_domain_expiration"),
    ("_get_expired_quant_domain", "_get_domain_expired_quant"),
    ("_get_expired_work_entries_domain", "_get_domain_expired_work_entries"),
    ("_get_expression_audit_aml_domain", "_get_domain_expression_audit_aml"),
    ("_get_favorite_project_id_domain", "_get_domain_favorite_project_id"),
    ("_get_feed_product_domain", "_get_domain_feed_product"),
    ("_get_field_domain", "_get_domain_field"),
    ("_get_fields_reward_product_domain", "_get_domain_fields_reward_product"),
    ("_get_forced_work_entries_domain", "_get_domain_forced_work_entries"),
    ("_get_gantt_progress_bar_domain", "_get_domain_gantt_progress_bar"),
    ("_get_gather_domain", "_get_domain_gather"),
    ("_get_gc_clear_bin_domain", "_get_domain_gc_clear_bin"),
    ("_get_gst_doc_type_domain", "_get_domain_gst_doc_type"),
    (
        "_get_import_product_classification_domain",
        "_get_domain_import_product_classification",
    ),
    ("_get_invalid_no_hsn_line_domain", "_get_domain_invalid_no_hsn_line"),
    ("_get_invoice_filter_type_domain", "_get_domain_invoice_filter_type"),
    ("_get_invoices_domain", "_get_domain_invoices"),
    ("_get_items_from_invoices_domain", "_get_domain_items_from_invoices"),
    ("_get_journal_codes_domain", "_get_domain_journal_codes"),
    ("_get_json_date_domain", "_get_domain_json_date"),
    ("_get_kit_domain", "_get_domain_kit"),
    ("_get_l10n_hr_fiscal_user_id_domain", "_get_domain_l10n_hr_fiscal_user_id"),
    ("_get_l10n_in_reports_aml_domain", "_get_domain_l10n_in_reports_aml"),
    ("_get_l10n_latam_documents_domain", "_get_domain_l10n_latam_documents"),
    ("_get_last_sequence_domain", "_get_domain_last_sequence"),
    ("_get_last_sol_of_customer_domain", "_get_domain_last_sol_of_customer"),
    ("_get_last_timesheet_domain", "_get_domain_last_timesheet"),
    ("_get_last_used_search_domain", "_get_domain_last_used_search"),
    ("_get_lead_quotation_domain", "_get_domain_lead_quotation"),
    ("_get_lead_sale_order_domain", "_get_domain_lead_sale_order"),
    ("_get_lead_to_assign_domain", "_get_domain_lead_to_assign"),
    ("_get_least_packages_domain", "_get_domain_least_packages"),
    ("_get_leave_domain", "_get_domain_leave"),
    ("_get_lines_domain", "_get_domain_lines"),
    ("_get_lines_sellable_domain", "_get_domain_lines_sellable"),
    ("_get_matching_individual_skill_domain", "_get_domain_matching_individual_skill"),
    ("_get_mention_suggestions_domain", "_get_domain_mention_suggestions"),
    ("_get_microsoft_sync_domain", "_get_domain_microsoft_sync"),
    ("_get_model_domain", "_get_domain_model"),
    ("_get_modelo349_audit_aml_domain", "_get_domain_modelo349_audit_aml"),
    ("_get_modelo349_domain", "_get_domain_modelo349"),
    (
        "_get_monthly_demand_moves_location_domain",
        "_get_domain_monthly_demand_moves_location",
    ),
    ("_get_move_hash_domain", "_get_domain_move_hash"),
    ("_get_moves_domain", "_get_domain_moves"),
    ("_get_name_recall_domain", "_get_domain_name_recall"),
    ("_get_nominative_domain", "_get_domain_nominative"),
    ("_get_non_empty_message_domain", "_get_domain_non_empty_message"),
    ("_get_notification_member_domain", "_get_domain_notification_member"),
    ("_get_occupancy_domain", "_get_domain_occupancy"),
    ("_get_open_contract_domain", "_get_domain_open_contract"),
    ("_get_options_account_type_domain", "_get_domain_options_account_type"),
    ("_get_options_date_domain", "_get_domain_options_date"),
    ("_get_options_domain", "_get_domain_options"),
    ("_get_options_journals_domain", "_get_domain_options_journals"),
    ("_get_options_partner_domain", "_get_domain_options_partner"),
    ("_get_options_unreconciled_domain", "_get_domain_options_unreconciled"),
    (
        "_get_order_fiscal_position_recompute_domain",
        "_get_domain_order_fiscal_position_recompute",
    ),
    ("_get_orderpoint_domain", "_get_domain_orderpoint"),
    ("_get_oss_custom_domain", "_get_domain_oss_custom"),
    ("_get_overdue_invoices_domain", "_get_domain_overdue_invoices"),
    ("_get_payment_method_domain", "_get_domain_payment_method"),
    ("_get_payslip_domain", "_get_domain_payslip"),
    ("_get_picking_type_code_domain", "_get_domain_picking_type_code"),
    ("_get_picking_type_domain", "_get_domain_picking_type"),
    ("_get_plan_available_base_domain", "_get_domain_plan_available_base"),
    ("_get_portal_default_domain", "_get_domain_portal_default"),
    ("_get_portal_message_fetch_domain", "_get_domain_portal_message_fetch"),
    ("_get_portal_message_non_empty_domain", "_get_domain_portal_message_non_empty"),
    ("_get_possible_model_domain", "_get_domain_possible_model"),
    ("_get_privacy_domain", "_get_domain_privacy"),
    ("_get_product_catalog_domain", "_get_domain_product_catalog"),
    ("_get_product_document_domain", "_get_domain_product_document"),
    ("_get_product_from_sol_name_domain", "_get_domain_product_from_sol_name"),
    (
        "_get_profitability_sale_order_items_domain",
        "_get_domain_profitability_sale_order_items",
    ),
    ("_get_project_task_from_domain", "_get_project_and_task_ids"),
    ("_get_propagation_domain", "_get_domain_propagation"),
    ("_get_provider_domain", "_get_domain_provider"),
    ("_get_purchase_order_domain", "_get_domain_purchase_order"),
    ("_get_qty_in_rent_domain", "_get_domain_qty_in_rent"),
    ("_get_quality_check_domain", "_get_domain_quality_check"),
    ("_get_quant_domain", "_get_domain_quant"),
    ("_get_read_domain", "_get_domain_read"),
    ("_get_realign_order_domain", "_get_domain_realign_order"),
    ("_get_recipients_domain", "_get_domain_recipients"),
    ("_get_reference_move_domain", "_get_domain_reference_move"),
    ("_get_remaining_rules_domain", "_get_domain_remaining_rules"),
    ("_get_replenishment_source_domain", "_get_domain_replenishment_source"),
    ("_get_results_page_user_input_domain", "_get_domain_results_page_user_input"),
    ("_get_resupply_mto_leg_domain", "_get_domain_resupply_mto_leg"),
    ("_get_reversed_moves_domain", "_get_domain_reversed_moves"),
    ("_get_rfq_domain", "_get_domain_rfq"),
    ("_get_route_domain", "_get_domain_route"),
    ("_get_rtc_invite_members_domain", "_get_domain_rtc_invite_members"),
    ("_get_rule_by_domain", "_get_domain_rule_by"),
    ("_get_rule_domain", "_get_domain_rule"),
    ("_get_rule_location_domain", "_get_domain_rule_location"),
    ("_get_rule_scope_domain", "_get_domain_rule_scope"),
    ("_get_sale_items_domain", "_get_domain_sale_items"),
    ("_get_sale_orders_domain", "_get_domain_sale_orders"),
    ("_get_sale_utm_domain", "_get_domain_sale_utm"),
    ("_get_sat_recheck_domain", "_get_domain_sat_recheck"),
    ("_get_scope_domain", "_get_domain_scope"),
    ("_get_search_domain", "_get_domain_search"),
    ("_get_section_domain", "_get_domain_section"),
    ("_get_sequence_scope_domain", "_get_domain_sequence_scope"),
    ("_get_shifts_to_plan_domain", "_get_domain_shifts_to_plan"),
    ("_get_shop_domain", "_get_domain_shop"),
    ("_get_similar_applicants_domain", "_get_domain_similar_applicants"),
    ("_get_similar_users_domain", "_get_domain_similar_users"),
    ("_get_skip_domain", "_get_domain_skip"),
    ("_get_slot_domain", "_get_domain_slot"),
    ("_get_so_mapping_domain", "_get_domain_so_mapping"),
    ("_get_social_media_accounts_domain", "_get_domain_social_media_accounts"),
    ("_get_social_posts_domain", "_get_domain_social_posts"),
    (
        "_get_staff_user_appointment_invite_domain",
        "_get_domain_staff_user_appointment_invite",
    ),
    ("_get_stale_expiration_domain", "_get_domain_stale_expiration"),
    ("_get_stock_user_domain", "_get_domain_stock_user"),
    ("_get_stream_post_domain", "_get_domain_stream_post"),
    ("_get_struct_id_domain", "_get_domain_struct_id"),
    ("_get_sub_leave_domain", "_get_domain_sub_leave"),
    ("_get_subscription_domain", "_get_domain_subscription"),
    ("_get_suitable_move_domain", "_get_domain_suitable_move"),
    ("_get_suitable_so_domain", "_get_domain_suitable_so"),
    ("_get_sync_domain", "_get_domain_sync"),
    ("_get_tax_domain", "_get_domain_tax"),
    ("_get_tax_exigible_domain", "_get_domain_tax_exigible"),
    ("_get_tax_rate_domain", "_get_domain_tax_rate"),
    ("_get_text_search_domain", "_get_domain_text_search"),
    ("_get_timesheet_domain", "_get_domain_timesheet"),
    ("_get_timesheet_manager_id_domain", "_get_domain_timesheet_manager_id"),
    ("_get_timesheet_reminder_domain", "_get_domain_timesheet_reminder"),
    ("_get_tracking_values_domain", "_get_domain_tracking_values"),
    ("_get_transactions_domain", "_get_domain_transactions"),
    (
        "_get_translation_frontend_modules_domain",
        "_get_domain_translation_frontend_modules",
    ),
    (
        "_get_unallocated_earnings_lines_domain",
        "_get_domain_unallocated_earnings_lines",
    ),
    (
        "_get_unhashed_moves_in_hashed_period_domain",
        "_get_domain_unhashed_moves_in_hashed_period",
    ),
    ("_get_unreconciled_aml_domain", "_get_domain_unreconciled_aml"),
    ("_get_unset_route_candidate_domain", "_get_domain_unset_route_candidate"),
    ("_get_update_sat_status_domain", "_get_domain_update_sat_status"),
    ("_get_used_folder_ids_domain", "_get_domain_used_folder_ids"),
    ("_get_user_domain", "_get_domain_user"),
    ("_get_valid_product_domain", "_get_domain_valid_product"),
    (
        "_get_vat_closing_entry_additional_domain",
        "_get_domain_vat_closing_entry_additional",
    ),
    (
        "_get_vehicles_without_current_drivers_domain",
        "_get_domain_vehicles_without_current_drivers",
    ),
    ("_get_website_domain", "_get_domain_not_rejected"),
    ("_get_whatsapp_gc_domain", "_get_domain_whatsapp_gc"),
    ("_get_withholding_tax_domain", "_get_domain_withholding_tax"),
    ("_get_work_entry_domain", "_get_domain_work_entry"),
    ("_get_work_entry_type_domain", "_get_domain_work_entry_type"),
    ("_get_work_hours_domain", "_get_domain_work_hours"),
    ("_need_renew_discount_domain", "_get_domain_renew_discount"),
    ("get_account_domain", "get_domain_account"),
    ("get_date_domain", "get_domain_date"),
    ("get_default_domain", "get_domain_default_filter"),
    ("get_month_filter_domain", "get_domain_month_filter"),
    ("get_planned_and_worked_hours_domain", "get_domain_planned_and_worked_hours"),
    ("get_themes_domain", "get_domain_themes"),
)

_RENAMES_BY_MODEL = (
    ("_get_default_domain", "_get_domain_default", "quality.point"),
    ("_get_default_domain", "_get_domain_default", "quality.point.test_type"),
    ("_get_company_domain", "_get_company_domain_name", "res.company"),
    ("get_domain", "get_domain_for_field", "date.range"),
    ("_get_domain", "_get_domain_orders", "report.point_of_sale.report_saledetails"),
    ("_get_domain", "_get_domain_orders", "report.pos_hr.single_employee_sales_report"),
    ("_get_domain", "_get_domain_for_periods", "resource.calendar.leaves"),
    ("_get_domain", "_get_domain_deferred_lines", "account.deferred.report.handler"),
    ("_get_domain", "_get_domain_partner_lines", "l10n_co.report.handler"),
    ("_get_domain", "_get_domain_partner_lines", "l10n_co.fuente.report.handler"),
    ("_get_domain", "_get_domain_partner_lines", "l10n_co.iva.report.handler"),
    ("_get_domain", "_get_domain_partner_lines", "l10n_co.libro.diario.report.handler"),
    ("_get_domain", "_get_domain_partner_lines", "l10n_co.ica.report.handler"),
    ("_get_domain", "_get_domain_employees", "yearly.salary.detail"),
    ("_get_domain", "_get_domain_quality_points", "quality.point"),
)


def _pattern(name):
    return r"\." + name + r"\M"


def migrate(cr, version):
    if not version:
        return
    for table, column in _STORED_PYTHON:
        if not schema.table_exists(cr, table) or not schema.column_exists(
            cr, table, column
        ):
            continue
        for old, new in _RENAMES:
            cr.execute(
                f"UPDATE {table} SET {column} ="
                f" regexp_replace({column}, %(pat)s, %(new)s, 'g')"
                f" WHERE {column} ~ %(pat)s",
                {"pat": _pattern(old), "new": "." + new},
            )
            if cr.rowcount:
                _logger.info(
                    "base 1.47: %s.%s %s -> %s (%d row(s))",
                    table,
                    column,
                    old,
                    new,
                    cr.rowcount,
                )
    for old, new, model in _RENAMES_BY_MODEL:
        rename_in_stored_expressions(cr, old, new, model=model)
