from . import test_attachment_access
from . import test_attachment_split
from . import test_controllers
from . import test_documents_access
from . import test_documents_attachment_link
from . import test_documents_chatter
from . import test_documents_common
from . import test_documents_document
from . import test_documents_document_folder
from . import test_documents_download
from . import test_documents_embedded_actions
from . import test_documents_gc
from . import test_documents_multicompany
from . import test_documents_multipage
from . import test_documents_permission_algebra
from . import test_documents_permissions
from . import test_documents_public_routes
from . import test_documents_request
from . import test_documents_search_panel
from . import test_documents_shortcut
from . import test_documents_tag
from . import test_documents_thumbnail
from . import test_documents_upload
from . import test_documents_user_folder
from . import test_documents_versioning
from . import test_js
from . import test_mail_activity
from . import test_mail_gateway
from . import test_tools
from .tours import *
