from . import test_documents_common
from . import test_attachment_access
from . import test_attachment_split
from . import test_controllers
from . import test_documents_access
from . import test_documents_audit_fixes
from . import test_documents_audit_round3
from . import test_documents_audit_round4
from . import test_documents_audit_round5
from . import test_documents_audit_round5_http
from . import test_documents_compound_fixes
from . import test_documents_dedup_fixes
from . import test_documents_document
from . import test_documents_document_folder
from . import test_documents_multicompany
from . import test_documents_multipage
from . import test_documents_permission_algebra
from . import test_documents_request
from . import test_documents_review_fixes
from . import test_documents_tag
from . import test_documents_user_folder
from . import test_js
from . import test_mail_activity
from . import test_mail_gateway
from . import test_tools
from .tours import *
