from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.fields import Domain
from odoo.tools import float_compare
from odoo.tools.misc import get_lang

from .exception_activity import group_by_order, notify_orders_of_exception


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    purchase_line_ids = fields.One2many(
        "purchase.order.line",
        "sale_line_id",
        string="Generated Purchase Lines",
        readonly=True,
        help="Purchase line generated by this Sales item on order confirmation, or when the quantity was increased.",
    )
    purchase_line_count = fields.Integer(
        "Number of generated purchase items", compute="_compute_purchase_line_count"
    )

    @api.depends("purchase_line_ids")
    def _compute_purchase_line_count(self):
        counts = dict(
            self.env["purchase.order.line"]
            .sudo()
            ._read_group(
                [("sale_line_id", "in", self.ids)], ["sale_line_id"], ["__count"]
            )
        )
        for line in self:
            line.purchase_line_count = counts.get(line, 0)

    @api.onchange("product_qty")
    def _onchange_product_qty(self):
        if not self._is_service_purchase_decrease():
            return {}
        return {
            "warning": {
                "title": _("Ordered quantity decreased!"),
                "message": _(
                    "You are decreasing the ordered quantity! Do not forget to manually update the purchase order if needed."
                ),
            }
        }

    def _is_service_purchase_decrease(self):
        if self.state != "done" or self.product_id.type != "service":
            return False
        if not self.product_id.with_company(
            self._purchase_service_get_company()
        ).service_to_purchase:
            return False
        return (
            self.product_qty < self._origin.product_qty
            and self.product_qty >= self.qty_transferred
        )

    # --------------------------
    # CRUD
    # --------------------------

    def _hook_on_created_confirmed_lines(self):
        super()._hook_on_created_confirmed_lines()
        # Expense lines are already delivered, so they must not create a purchase.
        self.filtered(
            lambda line: not line.is_expense
        ).sudo()._purchase_service_generation()

    def _post_quantity_changes(self, field_name, changes):
        super()._post_quantity_changes(field_name, changes)
        if field_name != "product_qty":
            return
        # A sale person may not write on the purchase side; the system still must.
        purchased = (
            self.browse([change["line"].id for change in changes])
            .sudo()
            ._filter_subcontracted_services()
        )
        if not purchased:
            return
        precision = self.env["decimal.precision"].get_precision("Product Unit")
        increased, decreased = {}, {}
        for change in changes:
            if change["line"].id not in purchased._ids:
                continue
            direction = float_compare(
                change["new_qty"], change["old_qty"], precision_digits=precision
            )
            if direction > 0:
                increased[change["line"].id] = change["old_qty"]
            elif direction < 0:
                decreased[change["line"].id] = change["old_qty"]
        if increased:
            purchased.browse(list(increased))._purchase_increase_ordered_qty(increased)
        if decreased:
            purchased.browse(list(decreased))._purchase_decrease_ordered_qty(decreased)

    # --------------------------
    # Business Methods
    # --------------------------

    def _purchase_decrease_ordered_qty(self, origin_values):
        """Warn the buyer that a sale line they purchased for was cut back.

        :param origin_values: map from sale line id to the ordered quantity before
            the change, in the UoM of the sale line
        """
        notify_orders_of_exception(
            group_by_order(self._get_open_purchase_lines(), lambda pol: pol.order_id),
            "sale_purchase.exception_purchase_on_sale_quantity_decreased",
            lambda purchase_lines: {
                "sale_lines": purchase_lines.sale_line_id,
                "sale_orders": purchase_lines.sale_line_id.order_id,
                "origin_values": origin_values,
            },
        )

    def _purchase_increase_ordered_qty(self, origin_values):
        """Carry an increase of the ordered quantity over to the purchase side.

        A still-draft RfQ line is raised to the new total; once the purchase is
        confirmed or cancelled the difference is bought on a new line instead.

        :param origin_values: map from sale line id to the ordered quantity before
            the change, in the UoM of the sale line
        """
        for line in self:
            last_purchase_line = line._purchase_service_get_last_line()
            if last_purchase_line.state == "draft":
                # Earlier purchases already cover part of the order; the open RfQ
                # carries only what is left of the new total. Never negative: a
                # confirmed purchase can exceed the sale line, and a negative line
                # would corrupt the purchase totals rather than report the anomaly.
                remaining = max(
                    line.product_qty
                    - line._purchase_service_get_ordered_qty(
                        line._get_open_purchase_lines() - last_purchase_line
                    ),
                    0.0,
                )
                last_purchase_line.product_qty = line.product_uom_id._compute_quantity(
                    remaining, last_purchase_line.product_uom_id
                )
            else:
                line._purchase_service_create(
                    quantity=line.product_qty - origin_values[line.id]
                )

    def _filter_subcontracted_services(self):
        """Lines this module is responsible for keeping in step with a purchase.

        A line can carry `purchase_line_ids` it did not create -- an MTO or dropship
        product is bought by the procurement engine, which links its purchase line
        back to the sale line all the same. Driving those from here means two
        mechanisms buying the same quantity, so the product's own setting, read in
        the order's company, is what says which ones are ours.
        """
        return self.filtered("purchase_line_count").filtered(
            lambda line: (
                line.product_id.with_company(
                    line._purchase_service_get_company()
                ).service_to_purchase
            )
        )

    def _get_open_purchase_lines(self):
        return self.purchase_line_ids.filtered(lambda pol: pol.state != "cancel")

    def _purchase_service_get_last_line(self):
        self.check_singleton()
        # Ordered by id, not create_date: two lines created in the same transaction
        # share a create_date, and the tie would pick an arbitrary one.
        return self._get_open_purchase_lines().sorted("id", reverse=True)[:1]

    def _purchase_service_get_ordered_qty(self, purchase_lines):
        """Sum of `purchase_lines` expressed in the UoM of this sale line."""
        self.check_singleton()
        return sum(
            purchase_line.product_uom_id._compute_quantity(
                purchase_line.product_qty, self.product_uom_id
            )
            for purchase_line in purchase_lines
        )

    def _purchase_service_get_date_order(self, supplierinfo):
        """return the ordered date for the purchase order, computed as : SO commitment date - supplier delay"""
        date_commitment = fields.Datetime.from_string(
            self.order_id.date_commitment or fields.Datetime.now()
        )
        return date_commitment - relativedelta(days=int(supplierinfo.delay))

    def _purchase_service_get_company(self):
        return self.company_id

    def _purchase_service_prepare_order_values(self, supplierinfo):
        """Returns the values to create the purchase order from the current SO line.
        :param supplierinfo: record of product.supplierinfo
        :rtype: dict
        """
        self.check_singleton()
        company = self._purchase_service_get_company()
        partner_supplier = supplierinfo.partner_id.with_company(company)
        fpos = (
            self.env["account.fiscal.position"]
            .sudo()
            .with_company(company)
            ._get_fiscal_position(partner_supplier)
        )
        return {
            "partner_id": partner_supplier.id,
            "partner_ref": partner_supplier.ref,
            "company_id": company.id,
            "currency_id": partner_supplier.property_purchase_currency_id.id
            or company.currency_id.id,
            "dest_address_id": False,  # False since only supported in stock
            "origin": self.order_id.name,
            "payment_term_id": partner_supplier.property_supplier_payment_term_id.id,
            "date_order": self._purchase_service_get_date_order(supplierinfo),
            "fiscal_position_id": fpos.id,
        }

    def _purchase_service_prepare_line_values(
        self, purchase_order, quantity=False, supplierinfo=None
    ):
        """Returns the values to create the purchase order line from the current SO line.
        :param purchase_order: record of purchase.order
        :param quantity: the quantity to force on the PO line, expressed in SO line UoM
        :param supplierinfo: the vendor pricelist line the purchase order was chosen
            from; resolved here when the caller has none
        :rtype: dict
        """
        self.check_singleton()
        if supplierinfo is None:
            supplierinfo = self._purchase_service_match_supplier(
                partner=purchase_order.partner_id, warning=False
            )
        purchase_uom = supplierinfo.product_uom_id or self.product_id.uom_id
        purchase_qty = self.product_uom_id._compute_quantity(
            quantity or self.product_qty, purchase_uom
        )
        purchase_line_vals = self.env[
            "purchase.order.line"
        ]._prepare_purchase_order_line(
            self.product_id,
            purchase_qty,
            purchase_uom,
            purchase_order.company_id,
            purchase_order.partner_id,
            purchase_order,
            seller=supplierinfo,
        )
        purchase_line_vals["sale_line_id"] = self.id
        # The variants belong on the vendor's document in the vendor's language, the
        # same one `_prepare_purchase_order_line` described the product in.
        variants = self.with_context(
            lang=get_lang(self.env, purchase_order.partner_id.lang).code
        )._get_line_multiline_description_variants()
        if variants:
            purchase_line_vals["name"] += variants
        if self.analytic_distribution:
            purchase_line_vals["analytic_distribution"] = self.analytic_distribution
        return purchase_line_vals

    def _purchase_service_match_supplier(self, partner=None, warning=True):
        """The vendor pricelist line this sale line buys from.

        :param partner: restrict to this vendor. Left out when the question is
            *which* vendor to buy from; passed once a purchase order has settled it.
        :param warning: raise UserError when no vendor matches; pass False to test for one silently
        """
        supplier = self.product_id._select_seller(
            partner_id=partner or self._get_purchase_partner(),
            quantity=self.product_qty,
            uom_id=self.product_uom_id,
        )
        if warning and not supplier:
            raise UserError(
                _(
                    "There is no vendor associated to the product %s. Please define a vendor for this product.",
                    self.product_id.display_name,
                )
            )
        return supplier

    def _get_additional_domain_for_purchase_order_line(self):
        return [("sale_order_id", "=", self.order_id.id)]

    def _purchase_service_match_purchase_order(self, partner, company=False):
        return (
            self.env["purchase.order.line"]
            .search(
                Domain.AND(
                    [
                        [
                            ("partner_id", "=", partner.id),
                            ("state", "=", "draft"),
                            (
                                "company_id",
                                "=",
                                (company or self._purchase_service_get_company()).id,
                            ),
                        ],
                        self._get_additional_domain_for_purchase_order_line(),
                    ]
                ),
                order="order_id",
                limit=1,
            )
            .order_id
        )

    def _create_purchase_order(self, supplierinfo):
        values = self._purchase_service_prepare_order_values(supplierinfo)
        return (
            self.env["purchase.order"]
            .with_context(mail_create_nosubscribe=True)
            .create(values)
        )

    def _match_or_create_purchase_order(self, supplierinfo):
        purchase_order = self._purchase_service_match_purchase_order(
            supplierinfo.partner_id
        )
        if not purchase_order:
            purchase_order = self._create_purchase_order(supplierinfo)
        return purchase_order

    def _get_purchase_partner(self):
        """In case we want to explicitly name a partner from whom we want to buy or receive products"""
        self.check_singleton()
        return False

    def _purchase_service_add_origin(self, purchase_order):
        origins = [
            origin for origin in (purchase_order.origin or "").split(", ") if origin
        ]
        if self.order_id.name not in origins:
            purchase_order.origin = ", ".join([*origins, self.order_id.name])

    def _purchase_service_create(self, quantity=False):
        """Create a purchase order line (and maybe a purchase order) for `quantity` of this sale line.
        If a line should create a RFQ, it will check for existing PO. If no one is find, the SO line will create one, then adds
        a new PO line. The created purchase order line will be linked to the SO line.
        :param quantity: the quantity to force on the PO line, expressed in SO line UoM
        :return: map of sale.order.line to the created purchase.order.line records
        :rtype: dict
        """
        sale_line_purchase_map = {}
        for line in self:
            line = line.with_company(line._purchase_service_get_company())
            supplierinfo = line._purchase_service_match_supplier()
            purchase_order = line._match_or_create_purchase_order(supplierinfo)
            line._purchase_service_add_origin(purchase_order)

            values = line._purchase_service_prepare_line_values(
                purchase_order, quantity=quantity, supplierinfo=supplierinfo
            )
            purchase_line = line.env["purchase.order.line"].create(values)

            sale_line_purchase_map.setdefault(line, line.env["purchase.order.line"])
            sale_line_purchase_map[line] |= purchase_line
        return sale_line_purchase_map

    def _purchase_service_generation(self):
        """Create a Purchase for the first time from the sale line. If the SO line already created a PO, it
        will not create a second one.

        :return: map of sale.order.line to the created purchase.order.line records
        :rtype: dict
        """
        sale_line_purchase_map = {}
        for line in self:
            line = line.with_company(line._purchase_service_get_company())
            # Do not regenerate PO line if the SO line has already created one in the past (SO cancel/reconfirmation case)
            if line.product_id.service_to_purchase and not line.purchase_line_count:
                sale_line_purchase_map.update(line._purchase_service_create())
        return sale_line_purchase_map
