import logging

from odoo.db import schema
from odoo.tools.module_data import rename_in_stored_expressions

_logger = logging.getLogger(__name__)

_STORED_PYTHON = (
    ("ir_act_server", "code"),
    ("ir_actions_server_history", "code"),
    ("ir_model_fields", "compute"),
    ("hr_salary_rule", "amount_python_compute"),
    ("hr_salary_rule", "condition_python"),
)

# The enterprise and agromarin names the naming gate saw once it governed every
# file under a manifest (§2.4.13) and after the 2026-09-10 rules, renamed by
# their rows; both floors read 0 after. A name only one model declares is
# rewritten wherever a stored block reaches it by attribute access, on 1.29's
# terms; _generate_pdf is spelled by two models with two bodies and is
# rewritten per model.
_RENAMES = (
    ("_append_additional_benefit_info", "_add_additional_benefit_info"),
    ("_append_boe_button", "_add_boe_button"),
    ("_append_cap_table_entry", "_add_cap_table_entry"),
    ("append_country_and_taxes_lines", "add_country_and_taxes_lines"),
    ("append_detail", "add_detail"),
    ("_append_error_messages_partner_vat", "_add_error_messages_partner_vat"),
    ("_append_error_messages_seq", "_add_error_messages_seq"),
    ("_append_historic_valuation_lines", "_add_historic_valuation_lines"),
    ("append_leaf", "add_leaf"),
    ("append_slot", "add_slot"),
    ("append_text", "add_text"),
    ("_append_valuation_line", "_add_valuation_line"),
    ("_assign_answer_fields", "_update_answer_fields"),
    ("_assign_codes_demo", "_update_demo_codes"),
    ("_assign_codes_uom", "_update_uom_codes"),
    ("_assign_factors_to_move_lines", "_update_move_line_factors"),
    ("_assign_journal", "_update_journal"),
    ("assign_node_ids_for_diff", "update_node_ids_for_diff"),
    ("assign_official_id", "update_official_id"),
    ("_assign_open_rental", "_update_open_rental"),
    ("_assign_packages_to_methods", "_get_method_by_package"),
    ("_assign_sequence_names", "_update_sequence_names"),
    ("assign_slot", "update_slot_resource"),
    ("_assign_token", "_update_token"),
    ("_assign_vals_by_tags", "_update_vals_by_tags"),
    ("_build_and_send_request", "_send_request"),
    ("build_article_index", "get_article_index"),
    ("build_column", "get_column"),
    ("_build_data_per_month", "_get_data_per_month"),
    ("_build_data_per_scope", "_get_data_per_scope"),
    ("build_error_message", "get_error_message"),
    ("build_feed", "get_feed"),
    ("build_feed_messages", "add_feed_messages"),
    ("_build_file_block", "_get_file_block"),
    ("_build_file", "_get_file"),
    ("_build_graph_config", "_get_graph_config"),
    ("_build_graph_config_per_month", "_get_graph_config_per_month"),
    ("_build_graph_config_per_scope", "_get_graph_config_per_scope"),
    ("build_json_feed", "get_json_feed"),
    ("build_partners_action", "get_partners_action"),
    ("build_result", "get_result"),
    ("_build_tool_call_response", "_get_tool_call_response"),
    ("_build_tools", "_get_tools"),
    ("_build_tree_from_input", "_get_tree_from_input"),
    ("_build_xpath_operations", "_get_xpath_operations"),
    ("_build_xpaths_attributes", "_get_xpaths_attributes"),
    ("build_dict", "prepare_dict"),
    ("build_result_dict", "prepare_result_dict"),
    ("_calculate_aba_hash", "_get_aba_hash"),
    ("_calculate_aba_hash_for_payments", "_get_aba_hash_for_payments"),
    ("_calculate_fiscalyear_result", "_get_fiscalyear_result"),
    ("_calculate_l10n_ke_item_code", "_get_l10n_ke_item_code"),
    ("_calculate_next_month_date", "_get_next_month_date"),
    ("_calculate_next_week_date", "_get_next_week_date"),
    (
        "_calculate_previous_years_unallocated_earnings",
        "_get_previous_years_unallocated_earnings",
    ),
    ("calculate_rate", "get_rate"),
    ("calculate_scale_checksum", "get_scale_checksum"),
    ("_calculate_settlement_period", "_get_settlement_period"),
    ("_calculate_slot_duration", "_get_slot_duration_capped"),
    ("_calculate_start_end_dates", "_get_start_end_dates"),
    (
        "_calculate_timesheet_mail_employee_nextdate",
        "_update_timesheet_mail_employee_nextdate",
    ),
    ("_calculate_timesheet_mail_nextdate", "_update_timesheet_mail_nextdate"),
    ("_calculate_totals", "_get_totals"),
    ("calculate_totals", "get_totals"),
    ("_calculate_unallocated_earnings_value", "_get_unallocated_earnings_value"),
    ("_cal_monthly_amt", "_get_monthly_amount"),
    ("_cal_move_line_weight", "_update_move_line_weight"),
    ("delete_all_annotations", "remove_all_annotations"),
    ("delete_approval", "remove_approval"),
    ("delete_call_activity", "remove_call_activity"),
    ("_delete_collaborative_data", "_remove_collaborative_data"),
    ("_delete_comments_from_commands", "_remove_comments_from_commands"),
    ("_delete_comments_from_data", "_remove_comments_from_data"),
    ("_delete_entries", "_remove_entries"),
    ("_delete_linked_resources", "_remove_linked_resources"),
    ("_delete_order", "_remove_order"),
    ("_delete_post", "_remove_post"),
    ("delete_shipment", "remove_shipment"),
    ("_delete_slot", "_remove_slot"),
    ("detect_reference_type", "get_reference_type"),
    ("_determine_inclusion", "_get_inclusion"),
    ("_determine_stage", "_get_stage"),
    ("_determine_start_date", "_get_start_date"),
    ("_determine_user_to_assign", "_get_user_to_assign"),
    ("_ensure_account_documents_exist", "_create_missing_account_documents"),
    ("ensure_account_is_set_up", "check_account_is_set_up"),
    ("_ensure_documents_project_tags_exist", "_create_missing_documents_project_tags"),
    ("_ensure_help_center_is_activated", "_check_help_center_activated"),
    ("_ensure_l10n_co_edi_no_journal_entries", "_check_l10n_co_edi_no_journal_entries"),
    ("_ensure_partner", "_check_partner"),
    ("_ensure_rental_stock_moves_consistency", "_sync_rental_stock_moves"),
    ("_ensure_required_data", "_check_required_data"),
    ("_ensure_service_linked_to_project", "_check_service_linked_to_project"),
    ("_ensure_submit_form_view", "_create_missing_submit_form_view"),
    ("_ensure_unique_email_alias", "_get_unique_email_alias"),
    ("_ensure_utm_source", "_create_missing_utm_source"),
    ("_ensure_website_menu", "_create_missing_website_menu"),
    ("_fetch_accounts", "_sync_accounts"),
    (
        "_fetch_and_check_private_appointment_types",
        "_get_checked_private_appointment_types",
    ),
    ("_fetch_and_save_feed_data", "_sync_feed_data"),
    ("_fetch_appointment", "_get_appointment"),
    ("fetch_before_outermost", "get_before_outermost"),
    ("_fetch_booking", "_get_booking"),
    ("_fetch_channel_videos", "_sync_channel_videos"),
    ("_fetch_content", "_get_content"),
    ("_fetch_create_partner_from_stripe", "_get_or_create_partner_from_stripe"),
    ("_fetch_database_info", "_get_database_info"),
    ("fetch_easypost_carrier", "get_easypost_carrier"),
    ("fetch_easypost_user", "get_easypost_user"),
    ("_fetch_envia_carriers", "_get_envia_carriers"),
    (
        "_fetch_esg_account_move_lines_linked_to_account",
        "_get_esg_account_move_lines_linked_to_account",
    ),
    (
        "_fetch_esg_assignation_lines_linked_to_account",
        "_get_esg_assignation_lines_linked_to_account",
    ),
    ("_fetch_files", "_get_files"),
    ("fetch_fiskaly_closing_receipt_data", "get_fiskaly_closing_receipt_data"),
    ("_fetch_image_urls_from_barcode_lookup", "_get_image_urls_from_barcode_lookup"),
    ("_fetch_instagram_posts", "_sync_instagram_posts"),
    ("_fetch_lazada_products", "_get_lazada_products"),
    ("_fetch_lazada_shipping_label", "_get_lazada_shipping_label"),
    ("_fetch_matching_post", "_get_matching_post"),
    ("_fetch_odoo_fin", "_get_odoo_fin"),
    (
        "fetch_online_sync_favorite_institutions",
        "get_online_sync_favorite_institutions",
    ),
    ("_fetch_online_transactions", "_sync_online_transactions"),
    ("_fetch_order_list", "_get_order_list"),
    ("_fetch_orders_detail", "_get_orders_detail"),
    ("_fetch_orders_items", "_get_orders_items"),
    ("_fetch_page_posts", "_sync_page_posts"),
    ("_fetch_partner_tickets", "_get_partner_tickets"),
    ("fetch_push_configuration", "get_push_configuration"),
    ("_fetch_room_from_access_token", "_get_room_from_access_token"),
    ("_fetch_seller_information", "_get_seller_information"),
    ("_fetch_shipment_label", "_update_shipment_label"),
    ("_fetch_shipment_provider", "_get_shipment_provider_data"),
    ("_fetch_shipping_label_status", "_update_shipping_label_status"),
    ("_fetch_shiprocket_channels", "_get_shiprocket_channels"),
    ("_fetch_shiprocket_couriers", "_get_shiprocket_couriers"),
    ("_fetch_stream_data", "_sync_stream_data"),
    ("fetch_ticket_by_keyword", "get_ticket_by_keyword"),
    ("_fetch_transactions", "_get_transactions"),
    ("_fetch_tweets", "_sync_tweets"),
    ("_fetch_url", "_get_url"),
    ("_fetch_values_from_report", "_get_values_from_report"),
    ("fetch_version", "get_version"),
    ("_fill_ai_field", "_update_ai_field"),
    ("_fill_ai_property", "_update_ai_property"),
    ("_fill_cufe_cude_cuds", "_update_cufe_cude_cuds"),
    ("fill_header", "update_header"),
    (
        "_fill_l10n_lu_saft_report_invoices_values",
        "_update_l10n_lu_saft_report_invoices_values",
    ),
    ("_fill_missing_values", "_update_missing_values"),
    ("_fill_signature", "_update_signature"),
    ("fill_signature", "update_signature"),
    ("_fill_transaction_vals_line_ofx", "_prepare_transaction_vals_line_ofx"),
    ("_fill_value_errors", "_update_value_errors"),
    ("_fill_xml_scheme", "_update_xml_scheme"),
    ("fill_xpath_node", "update_xpath_node"),
    ("generate_ahv_report", "action_generate_ahv_report"),
    ("_generate_attendances", "_create_attendances"),
    ("generate_fak_report", "action_generate_fak_report"),
    ("generate_free_ahv_report", "action_generate_free_ahv_report"),
    ("generate_goals", "create_goals"),
    ("generate_is_statement", "action_generate_is_statement"),
    ("generate_ktg_report", "action_generate_ktg_report"),
    ("generate_laac_report", "action_generate_laac_report"),
    ("generate_laa_report", "action_generate_laa_report"),
    ("_generate_payslips", "_create_payslips"),
    ("_generate_services", "_create_services"),
    ("generate_statistic_report", "action_generate_statistic_report"),
    ("generate_st_report", "action_generate_st_report"),
    ("generate_tax_accounting_reports", "action_generate_tax_accounting_reports"),
    ("_generate_tutorial_articles", "_create_tutorial_articles"),
    ("generate_txb_report", "action_generate_txb_report"),
    ("_generate_access_token", "_update_access_token"),
    ("_generate_assessment_note_ids", "_create_assessment_notes"),
    ("_generate_completed_document", "_update_completed_document"),
    ("_generate_completed_documents", "_create_completed_documents"),
    ("_generate_currency_rates", "_create_currency_rates"),
    ("_generate_declarations", "_update_declarations"),
    ("_generate_delay_line", "_create_delay_line"),
    ("generate_dmfa_pdf_report", "action_generate_dmfa_pdf_report"),
    ("generate_dmfa_xml_report", "action_generate_dmfa_xml_report"),
    ("_generate_employee_documents_folders", "_create_employee_documents_folders"),
    (
        "_generate_employee_documents_subfolders",
        "_create_employee_documents_subfolders",
    ),
    ("_generate_envelope_data", "_update_envelope_data"),
    ("_generate_form_281_50", "_create_form_281_50"),
    ("generate_lot", "action_generate_lot"),
    ("_generate_pages", "_create_pages"),
    ("generate_proof_of_insurance", "action_generate_proof_of_insurance"),
    ("_generate_qweb_report_template", "_create_qweb_report_template"),
    ("_generate_shipping_label", "_update_shipping_label"),
    ("_generate_start_of_year_columns", "_update_start_of_year_columns"),
    ("_generate_stock_moves", "_create_stock_moves"),
    ("_generate_total_amounts_columns", "_update_total_amounts_columns"),
    ("_generate_worksheet_model", "_create_worksheet_model"),
    ("_get_employees_with_invalid_ifsc", "_filtered_invalid_ifsc"),
    ("_get_sendable_payslips", "_filtered_sendable"),
    ("_get_stock_subscription_lines", "_filtered_stock_subscription_lines"),
    ("_get_timesheets_to_merge", "_filtered_to_merge"),
    ("_get_timesheet_subscription_lines", "_filtered_timesheet_subscription_lines"),
    ("_get_company_domain", "_get_domain_company"),
    ("interpret_error_code", "get_error_message_from_response"),
    ("_make_api_request", "_send_api_request"),
    ("__make_api_request", "__send_api_request"),
    ("_make_approval_method", "_get_approval_method"),
    ("make_lazada_api_request", "send_lazada_api_request"),
    ("make_proxy_request", "send_proxy_request"),
    ("make_public_user", "create_public_user"),
    ("make_request_stripe_proxy", "send_request_stripe_proxy"),
    ("_make_session", "_prepare_session"),
    ("make_shopee_api_request", "send_shopee_api_request"),
    ("make_sp_api_request", "send_sp_api_request"),
    ("make_null_data", "prepare_null_data"),
    ("make_sample_data", "prepare_sample_data"),
    ("need_tax_data_to_be_reported", "is_tax_data_report_required"),
    ("_populate_constant_items", "_update_constant_items"),
    ("_populate_partner_details", "_get_partner_details"),
    ("_populate_skills_for_confirmed", "_update_skills_for_confirmed"),
    ("_retrieve_boe_manual_wizard", "_get_boe_manual_wizard"),
    ("_retrieve_casilla_lines", "_get_casilla_lines"),
    ("_retrieve_chat_history", "_get_chat_history"),
    ("retrieve_dashboard", "get_dashboard"),
    ("_retrieve_fr_intrastat_wizard", "_get_fr_intrastat_wizard"),
    ("retrieve_line_difference", "get_line_difference"),
    ("_retrieve_period_and_year", "_get_period_and_year"),
    ("retrieve_referral_data", "get_referral_data"),
    ("retrieve_referral_welcome_screen", "get_referral_welcome_screen"),
    ("_retrieve_report_expression", "_get_report_expression"),
    ("_retrieve_transactions", "_get_transactions_from_provider"),
    ("retrieve_vat_obligations", "get_vat_obligations"),
    ("_retrieve_warehouse_name", "_get_warehouse_name"),
    ("_seed_unset_journals", "_update_unset_journals"),
    ("_should_be_snapshotted", "_is_snapshot_required"),
    ("_should_create_order", "_is_order_creation_required"),
    ("_should_execute", "_is_execution_required"),
    ("_should_generate_planning_slot", "_is_planning_slot_required"),
    ("_should_load_all_annexes", "_is_load_all_annexes_required"),
    ("_should_not_display_timer", "_is_timer_hidden"),
    ("_should_post_invoice", "_is_invoice_post_required"),
    ("_should_unlink_on_close", "_is_unlink_on_close_required"),
    ("_sum_category", "_get_category_sum"),
    ("_sum_salary_rule_category", "_get_salary_rule_category_sum"),
    ("_sum_tax_categories", "_get_tax_categories_sum"),
    ("_sum_worked_days", "_get_worked_days_sum"),
    ("_validate_aba_fic", "_check_aba_fic"),
    ("_validate_abn", "_get_abn_errors"),
    ("_validate_account_journal_id", "_check_account_journal_id"),
    ("_validate_aec_creation_conditions", "_check_aec_creation_conditions"),
    ("validate_and_send_invoice", "post_and_send_invoice"),
    ("_validate_auth_method", "_get_auth_method_result"),
    ("validate_bacs_direct_credit_sun", "check_bacs_direct_credit_sun"),
    ("_validate_bank_account_for_zengin", "_check_bank_account_for_zengin"),
    ("_validate_bank_for_nacha", "_check_bank_for_nacha"),
    ("validate_batch_button", "action_confirm_batch"),
    ("validate_batch", "confirm_batch"),
    ("validate_bic", "check_bic"),
    ("_validate_company_data", "_check_company_data"),
    ("validate_connection", "action_check_connection"),
    ("_validate_create_account_data", "_check_create_account_data"),
    ("_validate_credentials", "_resolve_credentials_error"),
    ("validate_czech_company_fields", "check_czech_company_fields"),
    ("_validate_debtor_id_code", "_check_debtor_id_code"),
    ("_validate_declaration", "_check_declaration"),
    ("_validate_ecdf_prefix", "_check_ecdf_prefix"),
    ("_validate_employee_addresses", "_resolve_employee_addresses_error"),
    ("_validate_employee_identification", "_resolve_employee_identification_error"),
    ("_validate_employee_personal_info", "_resolve_employee_personal_info_error"),
    ("_validate_employee_rental_records", "_resolve_employee_rental_records_error"),
    ("_validate_end_date", "_check_end_date"),
    ("_validate_expiry", "_is_expiry_valid"),
    ("validate_export", "check_export"),
    ("_validate_form", "_mark_form_generated"),
    ("_validate_fraud_prevention_headers", "_check_fraud_prevention_headers"),
    ("validate_groupbys", "check_groupbys"),
    ("_validate_helper_for_foreign_tax_codes", "_get_foreign_tax_codes_error"),
    ("validate_input", "check_input"),
    ("_validate_invoices_data_on_open", "_check_invoices_data_on_open"),
    ("_validate_journal_for_nacha", "_check_journal_for_nacha"),
    ("_validate_l10n_de_datev_account_length", "_check_l10n_de_datev_account_length"),
    ("validate_measures", "check_measures"),
    ("_validate_niss", "_check_niss"),
    ("_validate_object_properties", "_check_object_properties"),
    ("validate_otp_and_do_next_action", "action_confirm_otp"),
    ("validate_otp", "confirm_otp"),
    ("validate_params_llm_values_with_schema", "check_params_llm_values_with_schema"),
    ("validate_partner_bank_id", "check_partner_bank_id"),
    ("_validate_partner_details", "_check_partner_details"),
    ("_validate_partner", "_check_partner"),
    ("_validate_partner_fields", "_check_partner_fields"),
    ("_validate_partner_id", "_check_partner_id"),
    ("_validate_pre_notification_period", "_check_pre_notification_period"),
    ("_validate_reference", "_check_reference"),
    ("_validate_response", "_check_response"),
    ("_validate_route", "_resolve_route_error"),
    ("validate_schema", "check_schema"),
    ("_validate_script_steps", "_check_script_steps"),
    ("validate_sdd_creditor_identifier", "check_sdd_creditor_identifier"),
    ("_validate_sdd_mandate_id", "_check_sdd_mandate_id"),
    ("validate_search_terms", "check_search_terms"),
    ("validate_second_operand", "check_second_operand"),
    ("_validate_sender_for_zengin", "_check_sender_for_zengin"),
    ("_validate_shipping_product_max_weight", "_is_shipping_product_weight_valid"),
    ("_validate_signature", "_is_signature_valid"),
    ("validate_signature", "action_confirm_signature"),
    ("_validate_stock", "_mark_stock_moves_done"),
    ("_validate_sv_as_number", "_check_sv_as_number"),
    ("validate_termination", "action_confirm_termination"),
    ("validate_tfn", "is_tfn_valid"),
    ("validate_unique_taxpayer_reference", "check_unique_taxpayer_reference"),
    ("_validate_user_number", "_check_user_number"),
    ("_validate_user_spec", "_check_user_spec"),
    ("_validate_with_superchoice", "_check_with_superchoice"),
    ("validate_xmldsig_signature", "check_xmldsig_signature"),
    (
        "_verify_company_errors_cron_l10n_uy_edi_get_vendor_bills",
        "_check_company_errors_cron_l10n_uy_edi_get_vendor_bills",
    ),
    ("verify_quality_checks", "check_quality_checks"),
    ("_verify_required_fields", "_check_required_fields"),
    ("_verify_token", "_is_token_valid"),
    ("_assign_asset_privileges", "_update_asset_privileges"),
    (
        "_assign_consolidated_customer_documents",
        "_update_consolidated_customer_documents",
    ),
    ("_assign_consolidated_vendor_documents", "_update_consolidated_vendor_documents"),
    ("_assign_external_module_privileges", "_update_external_module_privileges"),
    ("_assign_order_lock_privileges", "_update_order_lock_privileges"),
    ("_assign_privileges_to_groups", "_update_group_privileges"),
    ("_assign_user_roles", "_update_user_roles"),
    ("_build_bug_hint", "_get_bug_hint"),
    ("build_catalog", "get_catalog"),
    ("_build_certificate", "_create_certificate"),
    ("_build_code_generation_prompt", "_get_code_generation_prompt"),
    ("_build_endpoint", "_get_endpoint"),
    ("_build_fallback_draft", "_get_fallback_draft"),
    ("build_interactions", "insert_interactions"),
    ("_build_line_commands", "_prepare_line_commands"),
    ("_build_payment_html", "_get_payment_html"),
    ("build_plots_from_geofences", "create_plots_from_geofences"),
    ("_build_reason_html", "_get_reason_html"),
    ("_build_system_preamble", "_get_system_preamble"),
    ("_build_system_prompt", "_get_system_prompt"),
    ("_build_approval_vals", "_prepare_approval_vals"),
    ("build_hds_vals", "prepare_hds_vals"),
    ("_build_vals", "_prepare_vals"),
    ("build_vals", "prepare_vals"),
    ("_calculate_actual_route_cost", "_update_actual_route_cost"),
    ("_calculate_and_allocate_delivery_costs", "_update_delivery_cost_allocation"),
    ("calculate_centroid", "get_centroid"),
    ("_calculate_centroids", "_update_centroids"),
    ("_calculate_cost_allocation", "_get_cost_allocation"),
    ("_calculate_distance_from_coordinates", "_get_distance_from_coordinates"),
    ("calculate_distance_to", "get_distance_to"),
    ("_calculate_growth_percentage", "_get_growth_percentage"),
    ("calculate_heading", "get_heading"),
    ("_calculate_period_dates", "_get_period_dates"),
    ("_calculate_times_circuit_method", "_update_times_circuit_method"),
    ("_calculate_times_zigzag_method", "_update_times_zigzag_method"),
    ("_calculate_v1_time", "_get_v1_time"),
    ("_calculate_v1_time_hybrid", "_get_v1_time_hybrid"),
    ("_calculate_v2_time", "_get_v2_time"),
    ("_calculate_v2_time_hybrid", "_get_v2_time_hybrid"),
    ("_calculate_v3_time", "_get_v3_time"),
    ("_calculate_v4_time", "_get_v4_time"),
    ("_calculate_v4_time_hybrid", "_get_v4_time_hybrid"),
    ("_calculate_v5_time", "_get_v5_time"),
    ("_calculate_v5_time_hybrid", "_get_v5_time_hybrid"),
    ("_calculate_vertical_time", "_get_vertical_time"),
    ("_delete_approval_product_orphan_acls", "_remove_approval_product_orphan_acls"),
    ("_delete_card", "_remove_card"),
    ("_delete_deprecated_groups", "_remove_deprecated_groups"),
    ("_delete_deprecated_privileges", "_remove_deprecated_privileges"),
    ("_delete_event", "_remove_event"),
    ("_delete_group_cascade", "_remove_group_cascade"),
    (
        "_delete_orphan_pos_price_control_privilege",
        "_remove_orphan_pos_price_control_privilege",
    ),
    ("_delete_orphan_sequence", "_remove_orphan_sequence"),
    ("_delete_orphan_team_leader_rule", "_remove_orphan_team_leader_rule"),
    ("_delete_residual_access", "_remove_residual_access"),
    ("_delete_sensitive_acls", "_remove_sensitive_acls"),
    ("delete_webhook", "remove_webhook"),
    ("_detect_coast_complexity", "_get_coast_complexity"),
    ("detect_conflict", "has_conflict"),
    ("_detect_current_branch_pr", "_get_current_branch_pr"),
    ("_detect_ignition_anomaly", "_add_ignition_anomaly"),
    ("_detect_lang", "_get_lang"),
    ("_detect_seasonality_strength", "_get_seasonality_strength"),
    ("_detect_srid", "_get_srid"),
    ("_detect_trend", "_get_trend"),
    ("_determine_classification_level", "_get_classification_level"),
    ("_drop_blanket_sale_user_rules", "_remove_blanket_sale_user_rules"),
    ("_drop_blanket_stock_user_rules", "_remove_blanket_stock_user_rules"),
    ("_drop_never_posted_subtype", "_remove_never_posted_subtype"),
    ("ensure_brand", "update_brand"),
    ("ensure_brand_phone", "update_brand_phone"),
    ("_ensure_centroids", "_update_centroids"),
    ("_ensure_enabled", "_resolve_disabled_response"),
    ("_ensure_new_columns", "_add_new_columns"),
    ("ensure_products", "get_or_create_products"),
    ("fetch_balances", "get_balances"),
    ("fetch_export", "get_export"),
    ("fetch_remote", "sync_remote_refs"),
    ("_fill_capture", "_update_capture"),
    ("_fill_keyboard", "_get_keyboard"),
    ("_fill_prompt", "_update_prompt"),
    ("fill_task_from_narrative", "update_task_from_narrative"),
    ("_generate_overtimes", "_create_overtimes"),
    ("generate_forecast", "action_generate_forecast"),
    ("_generate_seasonal_indices", "_update_seasonal_indices"),
    ("_get_credit_limit_orders", "_filtered_credit_limit_orders"),
    ("_get_fiscal_treatment_moves", "_filtered_fiscal_treatment"),
    ("_get_moves_awaiting_approval", "_filtered_awaiting_approval"),
    ("make_cached_json_response", "prepare_cached_json_response"),
    ("_needs_device_info", "_is_device_info_required"),
    ("_needs_sale_access_bypass", "_is_sale_access_bypass_required"),
    ("_populate_gps_tracking", "_create_gps_tracking"),
    ("_populate_retail_machines", "_create_retail_machines"),
    ("_scan_existing_numbers", "_get_existing_numbers"),
    ("_scan_models_directory", "_get_models_in_directory"),
    ("_seed_bascula_credentials", "_create_bascula_credentials"),
    ("_seed_catalog_weights", "_create_catalog_weights"),
    ("should_block_request", "is_request_blocked"),
    ("_should_exclude", "_is_excluded"),
    ("_validate_amount", "_get_amount_or_error"),
    ("validate_auth", "get_auth_status"),
    ("_validate_choice", "_resolve_choice_error"),
    ("_validate_code_structure", "_check_code_structure"),
    ("validate_commit_message", "is_commit_message_valid"),
    ("_validate_date", "_get_date_or_error"),
    ("_validate_date_format", "_is_date_format_valid"),
    ("_validate_employee_access", "_has_employee_access"),
    ("validate_file", "get_file_validation_result"),
    ("validate_files", "get_files_validation_summary"),
    ("_validate_init_data", "_resolve_init_data"),
    ("validate_module", "get_module_validation_summary"),
    ("_validate_partner_access", "_has_partner_access"),
    ("validate_picking", "mark_picking_done"),
    ("_validate_room", "_inspect_room_request"),
    ("validate_target", "check_target"),
    ("_verify_init_data", "_resolve_init_data"),
    ("_verify_leaf_flags", "_check_leaf_flags"),
    ("_verify_migration", "_check_migration"),
    ("_verify_results", "_log_results"),
    ("_wants_address_data", "_is_address_data_wanted"),
    ("_wants_calendar_data", "_is_calendar_data_wanted"),
)

_RENAMES_BY_MODEL = (
    ("_generate_pdf", "_create_pdf_attachments", "hr.payslip"),
    ("_generate_pdf", "_update_pdf", "hr.payroll.employee.declaration"),
)


def _pattern(name):
    return r"\." + name + r"\M"


def migrate(cr, version):
    if not version:
        return
    for table, column in _STORED_PYTHON:
        if not schema.table_exists(cr, table) or not schema.column_exists(
            cr, table, column
        ):
            continue
        for old, new in _RENAMES:
            cr.execute(
                f"UPDATE {table} SET {column} ="
                f" regexp_replace({column}, %(pat)s, %(new)s, 'g')"
                f" WHERE {column} ~ %(pat)s",
                {"pat": _pattern(old), "new": "." + new},
            )
            if cr.rowcount:
                _logger.info(
                    "base 1.48: %s.%s %s -> %s (%d row(s))",
                    table,
                    column,
                    old,
                    new,
                    cr.rowcount,
                )
    for old, new, model in _RENAMES_BY_MODEL:
        rename_in_stored_expressions(cr, old, new, model=model)
