from odoo.models import BaseModel
from odoo.tools import consteq


def resolve_message_thread(message: BaseModel) -> BaseModel:
    """Resolve the thread a ``mail.message`` points at, or an empty recordset.

    Single answer to "what record does this message belong to" for the portal
    controllers that need the thread only to check a credential against it.

    The "is this a usable thread model" question is owned by
    :meth:`mail.message._is_thread_model` -- ``model`` is mail's column, and
    mail's own access path has to ask exactly the same thing one step earlier.
    Portal defers to it rather than keeping a second copy of the rule.

    Returns an empty ``mail.thread`` recordset -- not ``None`` -- when the
    message names no usable thread. That keeps the result usable with the ORM
    idioms the callers already use: it is falsy, and :func:`get_portal_partner`
    short-circuits on it through :func:`resolve_thread_for_credentials` without
    ever touching a token field.

    :param message: single ``mail.message`` record
    :return: the thread record, or an empty ``mail.thread`` recordset
    """
    if not message.res_id or not message._is_thread_model():
        return message.env["mail.thread"]
    return message._get_thread_model().browse(message.res_id)


def resolve_thread_for_credentials(thread: BaseModel) -> BaseModel:
    """Narrow a client-addressed thread to the rows that actually exist.

    Both validators below have to read the thread's token field to compare
    against, and the ORM raises ``MissingError`` when a field is read on an id
    with no row. Callers get that id straight from the client — a chatter
    route's ``thread_id``, or a ``mail.message.res_id`` whose record was deleted
    after the message was posted — so "the record is gone" is ordinary input,
    not an anomaly, and it must not become an error response that confirms to an
    anonymous caller which ids exist.

    The check belongs here, at the step that turns an untrusted id into a
    recordset, rather than inside the validators: they are pure predicates over
    an *already resolved* thread, and a credential presented against a record
    that does not exist proves nothing either way.

    ``exists()`` is skipped for an empty recordset — there is no id to look up,
    and reading a field on an empty set is well-defined (it yields the field's
    falsy default, which the validators already reject).

    :param thread: thread recordset addressed by a client-supplied id
    :return: ``thread`` when it exists, an empty recordset otherwise
    """
    return thread.exists() if thread.ids else thread


def validate_thread_with_hash_pid(
    thread: BaseModel,
    _hash: str | None,
    pid: int | str | None,
) -> bool:
    """Verify an HMAC token binding a portal partner to a thread.

    :param thread: a single-record mail-thread (sale.order, account.move, ...)
    :param str _hash: HMAC token generated by ``_sign_token`` or
                      ``_portal_get_parent_hash_token``
    :param pid: ``res.partner`` id encoded in the URL (str or int)
    :return: True iff the hash matches the thread or its parent thread token
    :rtype: bool

    Uses :func:`consteq` (constant-time compare) on every branch to avoid
    leaking token bytes via timing.

    A ``mail.thread`` that does not declare the configured token field cannot
    produce a signature (``_sign_token`` raises ``NotImplementedError``), so no
    ``_hash`` can ever validate against it. Short-circuit to ``False`` instead
    of letting that exception surface as HTTP 500 on the public chatter routes
    (reachable via e.g. ``res.partner``, a ``mail.thread`` without
    ``access_token``). Mirrors the guard in :func:`validate_thread_with_token`.

    Both credentials are type-checked before use. These routes are ``jsonrpc``,
    so the caller picks the JSON *type* of every parameter, not just its value:
    a ``hash`` sent as a number reaches ``consteq`` (``TypeError``) and a ``pid``
    sent as a list reaches ``int()`` (``TypeError``) — each an HTTP 500 with a
    traceback on an anonymous route. A credential of the wrong type is simply
    not a credential, so it validates as ``False``. ``bool`` is rejected
    explicitly because it is an ``int`` subclass, and ``float`` because
    truncating ``1.9`` to partner 1 would be a silent reinterpretation of the
    caller's input rather than a rejection of it.

    ``thread`` itself is *not* validated here: it must already be a resolved,
    existing record, because ``_sign_token`` reads its token field and that
    raises ``MissingError`` on a phantom id. Callers holding a client-supplied
    id must pass it through :func:`resolve_thread_for_credentials` first.
    """
    if not isinstance(_hash, str) or not _hash or not pid:
        return False
    if thread._mail_post_token_field not in thread._fields:
        return False
    if isinstance(pid, bool) or not isinstance(pid, (int, str)):
        return False
    try:
        pid = int(pid)
    except ValueError:
        return False
    if consteq(_hash, thread._sign_token(pid)):
        return True
    parent_sign_token = thread._portal_get_parent_hash_token(pid)
    return bool(parent_sign_token) and consteq(_hash, parent_sign_token)


def validate_thread_with_token(thread: BaseModel, token: str | None) -> bool:
    """Verify a per-thread access token (e.g. sale order ``access_token``).

    :param thread: single-record mail-thread; expected to declare the field
                   named by ``_mail_post_token_field``
    :param str token: token provided by the unauthenticated request
    :return: True iff ``token`` matches the thread's stored token; False when
             the token is empty, the thread does not declare the configured
             token field, or the stored value does not match
    :rtype: bool

    The field-presence check is required because ``_mail_post_token_field``
    defaults to ``"access_token"`` on the base ``mail.thread`` model, but the
    matching field only exists on models that inherit ``portal.mixin``. A
    bare ``mail.thread`` (e.g. ``res.partner``) reached through a public
    controller would otherwise raise ``KeyError`` from ``self._fields[name]``
    and surface as HTTP 500. Mirrors the guard already present in
    :meth:`portal.mail_thread.MailThread._sign_token`.

    ``bool(stored_token)`` guards the ``consteq`` call: an unshared record has
    ``access_token == False``, and ``consteq(str, False)`` raises ``TypeError``
    (HTTP 500 on a public route). A falsy stored token cannot match any
    client-supplied token anyway, so short-circuiting to ``False`` is both
    correct and safe — there is no secret whose comparison timing could leak.

    The ``isinstance`` check guards the same ``consteq`` call from the other
    side: over ``jsonrpc`` the caller chooses the token's JSON type, and a
    number or list would raise ``TypeError`` there. See
    :func:`validate_thread_with_hash_pid` for the full rationale, including why
    ``thread`` must already be resolved via
    :func:`resolve_thread_for_credentials` when its id came from a client.
    """
    token_field = thread._mail_post_token_field
    if not isinstance(token, str) or not token or token_field not in thread._fields:
        return False
    stored_token = thread[token_field]
    return bool(stored_token) and consteq(token, stored_token)


def get_portal_partner(
    thread: BaseModel,
    _hash: str | None,
    pid: int | str | None,
    token: str | None,
) -> BaseModel:
    """Resolve the ``res.partner`` proven by an HMAC hash+pid pair or a thread token.

    :param thread: single-record mail-thread
    :param str _hash: HMAC token (see :func:`validate_thread_with_hash_pid`)
    :param pid: ``res.partner`` id matching ``_hash``
    :param str token: thread access token (see :func:`validate_thread_with_token`)
    :return: the proven partner, or an empty ``res.partner`` recordset if
             neither credential validates
    :rtype: res.partner

    This is the entry point the chatter controllers reach with a thread browsed
    from a client-supplied id (``mail.message.res_id`` of a record that may
    since have been deleted), so it resolves the thread once here rather than
    letting each validator read a field off a phantom row and raise
    ``MissingError``.
    """
    thread = resolve_thread_for_credentials(thread)
    if not thread:
        return thread.env["res.partner"]
    if validate_thread_with_hash_pid(thread, _hash, pid):
        return thread.env["res.partner"].sudo().browse(int(pid))
    if validate_thread_with_token(thread, token):
        if partner := thread._mail_get_partners()[thread.id][:1]:
            return partner
    return thread.env["res.partner"]
