from odoo.models import BaseModel
from odoo.tools import consteq


def validate_thread_with_hash_pid(
    thread: BaseModel,
    _hash: str | None,
    pid: int | str | None,
) -> bool:
    """Verify an HMAC token binding a portal partner to a thread.

    :param thread: a single-record mail-thread (sale.order, account.move, ...)
    :param str _hash: HMAC token generated by ``_sign_token`` or
                      ``_portal_get_parent_hash_token``
    :param pid: ``res.partner`` id encoded in the URL (str or int)
    :return: True iff the hash matches the thread or its parent thread token
    :rtype: bool

    Uses :func:`consteq` (constant-time compare) on every branch to avoid
    leaking token bytes via timing.
    """
    if not _hash or not pid:
        return False
    try:
        pid = int(pid)
    except ValueError:
        return False
    if consteq(_hash, thread._sign_token(pid)):
        return True
    parent_sign_token = thread._portal_get_parent_hash_token(pid)
    return bool(parent_sign_token) and consteq(_hash, parent_sign_token)


def validate_thread_with_token(thread: BaseModel, token: str | None) -> bool:
    """Verify a per-thread access token (e.g. sale order ``access_token``).

    :param thread: single-record mail-thread; expected to declare the field
                   named by ``_mail_post_token_field``
    :param str token: token provided by the unauthenticated request
    :return: True iff ``token`` matches the thread's stored token; False when
             the token is empty, the thread does not declare the configured
             token field, or the stored value does not match
    :rtype: bool

    The field-presence check is required because ``_mail_post_token_field``
    defaults to ``"access_token"`` on the base ``mail.thread`` model, but the
    matching field only exists on models that inherit ``portal.mixin``. A
    bare ``mail.thread`` (e.g. ``res.partner``) reached through a public
    controller would otherwise raise ``KeyError`` from ``self._fields[name]``
    and surface as HTTP 500. Mirrors the guard already present in
    :meth:`portal.mail_thread.MailThread._sign_token`.
    """
    token_field = thread._mail_post_token_field
    return (
        bool(token)
        and token_field in thread._fields
        and consteq(token, thread[token_field])
    )


def get_portal_partner(
    thread: BaseModel,
    _hash: str | None,
    pid: int | str | None,
    token: str | None,
) -> BaseModel:
    """Resolve the ``res.partner`` proven by an HMAC hash+pid pair or a thread token.

    :param thread: single-record mail-thread
    :param str _hash: HMAC token (see :func:`validate_thread_with_hash_pid`)
    :param pid: ``res.partner`` id matching ``_hash``
    :param str token: thread access token (see :func:`validate_thread_with_token`)
    :return: the proven partner, or an empty ``res.partner`` recordset if
             neither credential validates
    :rtype: res.partner
    """
    if validate_thread_with_hash_pid(thread, _hash, pid):
        return thread.env["res.partner"].sudo().browse(int(pid))
    if validate_thread_with_token(thread, token):
        if partner := thread._mail_get_partners()[thread.id][:1]:
            return partner
    return thread.env["res.partner"]
